# 新增账号锁定时间到了之后自动解锁定时任务 by zhangruoyu 250110
INSERT INTO bmos_scheduler.xxl_job_info (id, job_group, job_desc, add_time, update_time, author, alarm_email, schedule_type, schedule_conf, misfire_strategy, executor_route_strategy, executor_handler, executor_param, executor_block_strategy, executor_timeout, executor_fail_retry_count, glue_type, glue_source, glue_remark, glue_updatetime, child_jobid, trigger_status, trigger_last_time, trigger_next_time) VALUES (8, 3, '账号锁定时间到了之后自动解锁', now(), now(), 'admin', '', 'CRON', '0 * * * * ?', 'DO_NOTHING', 'FIRST', 'userUnLockExpireValid', '', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化', '2024-12-23 13:52:42', '', 1, 1736478960000, 1736479020000);
# 物料临期提醒消息发送 by yigaohui 250114
INSERT INTO bmos_scheduler.xxl_job_info (id, job_group, job_desc, add_time, update_time, author, alarm_email, schedule_type, schedule_conf, misfire_strategy, executor_route_strategy, executor_handler, executor_param, executor_block_strategy, executor_timeout, executor_fail_retry_count, glue_type, glue_source, glue_remark, glue_updatetime, child_jobid, trigger_status, trigger_last_time, trigger_next_time) VALUES (9, 1, '物料临期提醒消息发送', '2025-01-09 14:30:52', '2025-01-13 17:11:31', 'admin', '', 'CRON', '* * 2 * * ?', 'DO_NOTHING', 'FIRST', 'MaterialExpireForeWarning', '', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化', '2025-01-09 14:30:52', '', 1, 1736794799000, 1736877600000);
delete from bmos_scheduler.xxl_job_info where id = 9;
INSERT INTO bmos_scheduler.xxl_job_info (id, job_group, job_desc, add_time, update_time, author, alarm_email, schedule_type, schedule_conf, misfire_strategy, executor_route_strategy, executor_handler, executor_param, executor_block_strategy, executor_timeout, executor_fail_retry_count, glue_type, glue_source, glue_remark, glue_updatetime, child_jobid, trigger_status, trigger_last_time, trigger_next_time) VALUES (9, 1, '物料临期提醒消息发送', now(), now(), 'admin', '', 'CRON', '0 0 2 * * ?', 'DO_NOTHING', 'FIRST', 'MaterialExpireForeWarning', '', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化', now(), '', 1, 1737053999000, 1737136800000);

# 称量中心定时刷新称量需求过期 by liang 250207
INSERT INTO bmos_scheduler.xxl_job_info (id, job_group, job_desc, add_time, update_time, author, alarm_email, schedule_type, schedule_conf, misfire_strategy, executor_route_strategy, executor_handler, executor_param, executor_block_strategy, executor_timeout, executor_fail_retry_count, glue_type, glue_source, glue_remark, glue_updatetime, child_jobid, trigger_status, trigger_last_time, trigger_next_time) VALUES (10, 1, '称量中心定时刷新称量需求过期', now(), now(), 'admin', '', 'CRON', '0 0 0 * * ?', 'DO_NOTHING', 'FIRST', 'updateWeighCenterRequirementExpired', '', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化', now(), '', 1, 1737053999000, 1737136800000);
