import { objectToArray } from '@bmos/utils';
import {
  BATCH_QUANTITY_PICK_BATCH_CHILDREN,
  BATCH_QUANTITY_PICK_BATCH_SUMMARY,
  BATCH_QUANTITY_PICK_SUMMARY_CHILDREN,
  BUSINESS_FORMULA_INFO_MATERIAL,
  BUSINESS_FORMULA_INFO_MATERIAL_CHILDREN,
  BUSINESS_NODE,
  BUSINESS_NODE_INFO_TYPE,
  BUSINESS_PRODUCT_INFO_CHILDREN,
  CLEAN_CHECK,
  CLEAN_CHECK_GROUP_CHILDREN,
  CLEAN_IMPLEMENT,
  CLEAN_IMPLEMENT_GROUP_CHILDREN,
  CLEAN_INFO_CHILDREN,
  CUSTOM_FIELD,
  EQUIPMENT_DATA_ACQUISITION,
  EQUIPMENT_DATA_ACQUISITION_CHILDREN,
  EQUIPMENT_DATA_ACQUISITION_DYNAMIC_TABLE,
  EQUIPMENT_DATA_DRAW,
  EQUIPMENT_DATA_DRAW_LIST,
  EQUIPMENT_INFO,
  EQUIPMENT_INFO_CHILDREN,
  FEED_RECYCLE,
  FEED_RECYCLE_FEEDING_DETAILS_CHILDREN,
  FEED_RECYCLE_SUMMARY_CHILDREN,
  INGREDIENTS_INPUT,
  INGREDIENTS_INPUT_FEEDING_DETAILS_CHILDREN,
  INGREDIENTS_INPUT_SUMMARY_CHILDREN,
  INGREDIENTS_PLAN_MATERIAL,
  INGREDIENTS_PLAN_MATERIAL_CHILDREN,
  INSPECTION_RESULTS,
  INSPECTION_RESULTS_CHILDREN,
  LIQUID_PREPARATION_INPUT,
  LIQUID_PREPARATION_INPUT_DETAIL,
  LIQUID_PREPARATION_INPUT_SUMMARY,
  LIQUID_PREPARATION_MEASURE,
  LIQUID_PREPARATION_MEASURE_DETAIL_CHILDREN,
  LIQUID_PREPARATION_MEASURE_SUMMARY_CHILDREN,
  LIQUID_PREPARATION_OUTPUT,
  LIQUID_PREPARATION_OUTPUT_DETAILS_CHILDREN,
  LIQUID_PREPARATION_OUTPUT_SUMMARY_CHILDREN,
  LIQUID_PREPARATION_PLAN,
  LIQUID_PREPARATION_PLAN_BATCH_CHILDREN,
  LIQUID_PREPARATION_PLAN_SUMMARY_CHILDREN,
  MATERIAL_INFO,
  MATERIAL_INFO_CHILDREN,
  MATERIAL_INPUT,
  MATERIAL_INPUT_DETAILS_CHILDREN,
  MATERIAL_INPUT_SUMMARY_CHILDREN,
  MATERIAL_QUANTITY_PICK_CHILDREN,
  MATERIAL_QUANTITY_PICK_MATERIAL,
  MATERIAL_RESERVE,
  MATERIAL_RESERVE_BATCH_CHILDREN,
  MATERIAL_RESERVE_SUMMARY_CHILDREN,
  NODE_INFO,
  OUTPUT_WEIGHING_CHILDREN,
  OUTPUT_WEIGHING_DETAILS_CHILDREN,
  OUTPUT_WEIGHING_SUMMARY_CHILDREN,
  PICKING_RECEIVING_BATCH_CHILDREN,
  PICKING_RECEIVING_CHILDREN,
  PICKING_RECEIVING_SUMMARY_CHILDREN,
  PRODUCT_OUTPUT_CHILDREN,
  PRODUCT_OUTPUT_DETAILS_CHILDREN,
  PRODUCT_OUTPUT_SUMMARY_CHILDREN,
  WEIGHING_DATA,
  WEIGHING_DATA_DETAIL_CHILDREN,
  WEIGHING_INGREDIENTS_CHILDREN,
  WEIGHING_INGREDIENTS_DETAILS_CHILDREN,
  WEIGHING_INGREDIENTS_SUMMARY_CHILDREN,
} from './enums/index';

export * from './enums/index';

// 业务组件
export const BUSINESS_NODE_INFO: BUSINESS_NODE_INFO_TYPE = {
  BUSINESS_PRODUCT_INFO: {
    componentType: 'BUSINESS_PRODUCT_INFO',
    componentName: t('生产信息'),
    node_type: '',
    permission: '120020001002001',
    children: objectToArray(BUSINESS_PRODUCT_INFO_CHILDREN) as BUSINESS_NODE[],
  },
  BUSINESS_FORMULA_INFO: {
    componentType: 'BUSINESS_FORMULA_INFO',
    componentName: t('生产BOM信息'),
    node_type: '',
    permission: '120020001002002',
    children: objectToArray(BUSINESS_FORMULA_INFO_MATERIAL) as BUSINESS_NODE[],
  },
  MATERIAL_INPUT: {
    componentType: 'MATERIAL_INPUT',
    componentName: t('物料投入'),
    node_type: '',
    permission: '120020001002022',
    children: objectToArray(MATERIAL_INPUT) as BUSINESS_NODE[],
  },
  BATCH_QUANTITY_PICK: {
    componentType: 'BATCH_QUANTITY_PICK',
    componentName: t('批次量领料'),
    node_type: '',
    permission: '120020001002003',
    children: objectToArray(BATCH_QUANTITY_PICK_BATCH_SUMMARY) as BUSINESS_NODE[],
  },
  MATERIAL_QUANTITY_PICK: {
    componentType: 'MATERIAL_QUANTITY_PICK',
    componentName: t('物料量领料'),
    node_type: '',
    permission: '120020001002004',
    children: objectToArray(MATERIAL_QUANTITY_PICK_MATERIAL) as BUSINESS_NODE[],
  },
  // 领料接收
  PICKING_RECEIVING: {
    componentType: 'PICKING_RECEIVING',
    componentName: t('领料接收'),
    node_type: '',
    permission: '120020001002005',
    children: objectToArray(PICKING_RECEIVING_CHILDREN) as BUSINESS_NODE[],
  },
  // 配料计划
  INGREDIENTS_PLAN: {
    componentType: 'INGREDIENTS_PLAN',
    componentName: t('配料计划'),
    node_type: '',
    permission: '120020001002006',
    children: objectToArray(INGREDIENTS_PLAN_MATERIAL) as BUSINESS_NODE[],
  },
  // 配料称量
  WEIGHING_INGREDIENTS: {
    componentType: 'WEIGHING_INGREDIENTS',
    componentName: t('配料称量'),
    node_type: '',
    permission: '120020001002007',
    children: objectToArray(WEIGHING_INGREDIENTS_CHILDREN) as BUSINESS_NODE[],
  },
  // 配料投入
  INGREDIENTS_INPUT: {
    componentType: 'INGREDIENTS_INPUT',
    componentName: t('配料投入'),
    node_type: '',
    permission: '120020001002008',
    children: objectToArray(INGREDIENTS_INPUT) as BUSINESS_NODE[],
  },
  // 生产投料
  FEED_RECYCLE: {
    componentType: 'FEED_RECYCLE',
    componentName: t('生产投料'),
    node_type: '',
    permission: '120020001002009',
    children: objectToArray(FEED_RECYCLE) as BUSINESS_NODE[],
  },
  // 成品产出
  PRODUCT_OUTPUT: {
    componentType: 'PRODUCT_OUTPUT',
    componentName: t('成品产出'),
    node_type: '',
    permission: '120020001002010',
    children: objectToArray(PRODUCT_OUTPUT_CHILDREN) as BUSINESS_NODE[],
  },
  // 中间品产出
  OUTPUT_WEIGHING: {
    componentType: 'OUTPUT_WEIGHING',
    componentName: t('中间品产出'),
    node_type: '',
    permission: '120020001002011',
    children: objectToArray(OUTPUT_WEIGHING_CHILDREN) as BUSINESS_NODE[],
  },
  // 物料预定
  MATERIAL_RESERVE: {
    componentType: 'MATERIAL_RESERVE',
    componentName: t('物料预定'),
    node_type: '',
    permission: '120020001002012',
    children: objectToArray(MATERIAL_RESERVE) as BUSINESS_NODE[],
  },
  // 配液计划
  LIQUID_PREPARATION_PLAN: {
    componentType: 'LIQUID_PREPARATION_PLAN',
    componentName: t('配液计划'),
    node_type: '',
    permission: '120020001002018',
    children: objectToArray(LIQUID_PREPARATION_PLAN) as BUSINESS_NODE[],
  },
  // 配液量取
  LIQUID_PREPARATION_MEASURE: {
    componentType: 'LIQUID_PREPARATION_MEASURE',
    componentName: t('配液量取'),
    node_type: '',
    permission: '120020001002019',
    children: objectToArray(LIQUID_PREPARATION_MEASURE) as BUSINESS_NODE[],
  },
  // 配液投入
  LIQUID_PREPARATION_INPUT: {
    componentType: 'LIQUID_PREPARATION_INPUT',
    componentName: t('配液投入'),
    node_type: '',
    permission: '120020001002020',
    children: objectToArray(LIQUID_PREPARATION_INPUT) as BUSINESS_NODE[],
  },
  // 配液产出
  LIQUID_PREPARATION_OUTPUT: {
    componentType: 'LIQUID_PREPARATION_OUTPUT',
    componentName: t('配液产出'),
    node_type: '',
    permission: '120020001002021',
    children: objectToArray(LIQUID_PREPARATION_OUTPUT) as BUSINESS_NODE[],
  },
  // 物料件信息
  MATERIAL_INFO: {
    componentType: 'MATERIAL_INFO',
    componentName: t('物料件信息'),
    node_type: '',
    permission: '120020001002023',
    children: objectToArray(MATERIAL_INFO) as BUSINESS_NODE[],
  },
  // 称量数据
  WEIGHING_DATA: {
    componentType: 'WEIGHING_DATA',
    componentName: t('称量数据'),
    node_type: '',
    permission: '120020001002024',
    children: objectToArray(WEIGHING_DATA) as BUSINESS_NODE[],
  },
  // 物料件信息
  INSPECTION_RESULTS: {
    componentType: 'INSPECTION_RESULTS',
    componentName: t('检验结果'),
    node_type: '',
    permission: '120020001002026',
    children: objectToArray(INSPECTION_RESULTS) as BUSINESS_NODE[],
  },
};
// 设备组件
export const EQUIPMENT_NODE_INFO: BUSINESS_NODE_INFO_TYPE = {
  // 设备信息
  EQUIPMENT_INFO: {
    componentType: 'EQUIPMENT_INFO',
    componentName: t('设备信息'),
    node_type: '',
    permission: '120020001002013',
    children: objectToArray(EQUIPMENT_INFO) as BUSINESS_NODE[],
  },
  // 设备数采
  EQUIPMENT_DATA_ACQUISITION: {
    componentType: 'EQUIPMENT_DATA_ACQUISITION',
    componentName: t('设备数采'),
    node_type: '',
    permission: '120020001002014',
    children: objectToArray(EQUIPMENT_DATA_ACQUISITION) as BUSINESS_NODE[],
  },
  // 数采绘图
  EQUIPMENT_DATA_DRAW_LIST: {
    componentType: 'EQUIPMENT_DATA_DRAW_LIST',
    componentName: t('设备数采绘图'),
    node_type: '',
    permission: '120020001002025',
    children: objectToArray(EQUIPMENT_DATA_DRAW_LIST) as BUSINESS_NODE[],
  },
};
// 清场组件
export const CLEAN_NODE_INFO: BUSINESS_NODE_INFO_TYPE = {
  CLEAN_INFO: {
    componentType: 'CLEAN_INFO',
    componentName: t('清场信息'),
    node_type: '',
    permission: '120020001002015',
    children: objectToArray(CLEAN_INFO_CHILDREN) as BUSINESS_NODE[],
  },
  CLEAN_CHECK: {
    componentType: 'CLEAN_CHECK',
    componentName: t('清场检查'),
    node_type: '',
    permission: '120020001002016',
    children: objectToArray(CLEAN_CHECK) as BUSINESS_NODE[],
  },
  CLEAN_IMPLEMENT: {
    componentType: 'CLEAN_IMPLEMENT',
    componentName: t('清场执行'),
    node_type: '',
    permission: '120020001002017',
    children: objectToArray(CLEAN_IMPLEMENT) as BUSINESS_NODE[],
  },
};
// 所有的业务根节点信息(不可删除)
export const ALL_BUSINESS_NODE_INFO = {
  ...BUSINESS_PRODUCT_INFO_CHILDREN,
  ...BUSINESS_FORMULA_INFO_MATERIAL_CHILDREN,
  ...BATCH_QUANTITY_PICK_BATCH_CHILDREN,
  ...BATCH_QUANTITY_PICK_SUMMARY_CHILDREN,
  ...PRODUCT_OUTPUT_DETAILS_CHILDREN,
  ...PRODUCT_OUTPUT_SUMMARY_CHILDREN,
  ...MATERIAL_QUANTITY_PICK_CHILDREN,
  ...INSPECTION_RESULTS_CHILDREN,
  ...PICKING_RECEIVING_BATCH_CHILDREN,
  ...PICKING_RECEIVING_SUMMARY_CHILDREN,
  ...INGREDIENTS_PLAN_MATERIAL_CHILDREN,
  ...WEIGHING_INGREDIENTS_DETAILS_CHILDREN,
  ...WEIGHING_INGREDIENTS_SUMMARY_CHILDREN,
  ...INGREDIENTS_INPUT_FEEDING_DETAILS_CHILDREN,
  ...INGREDIENTS_INPUT_SUMMARY_CHILDREN,
  ...MATERIAL_INPUT_SUMMARY_CHILDREN,
  ...MATERIAL_INPUT_DETAILS_CHILDREN,
  ...OUTPUT_WEIGHING_DETAILS_CHILDREN,
  ...OUTPUT_WEIGHING_SUMMARY_CHILDREN,
  ...EQUIPMENT_DATA_ACQUISITION_CHILDREN,
  ...EQUIPMENT_INFO_CHILDREN,
  ...MATERIAL_INFO_CHILDREN,
  ...FEED_RECYCLE_FEEDING_DETAILS_CHILDREN,
  ...FEED_RECYCLE_SUMMARY_CHILDREN,
  ...CLEAN_IMPLEMENT_GROUP_CHILDREN,
  ...CLEAN_CHECK_GROUP_CHILDREN,
  ...CLEAN_INFO_CHILDREN,
  ...MATERIAL_RESERVE_SUMMARY_CHILDREN,
  ...MATERIAL_RESERVE_BATCH_CHILDREN,
  ...LIQUID_PREPARATION_PLAN_BATCH_CHILDREN,
  ...LIQUID_PREPARATION_PLAN_SUMMARY_CHILDREN,
  ...LIQUID_PREPARATION_INPUT_DETAIL,
  ...LIQUID_PREPARATION_INPUT_SUMMARY,
  ...LIQUID_PREPARATION_MEASURE_DETAIL_CHILDREN,
  ...LIQUID_PREPARATION_MEASURE_SUMMARY_CHILDREN,
  ...LIQUID_PREPARATION_OUTPUT_DETAILS_CHILDREN,
  ...LIQUID_PREPARATION_OUTPUT_SUMMARY_CHILDREN,
  ...WEIGHING_DATA_DETAIL_CHILDREN,
  ...EQUIPMENT_DATA_DRAW,
  FEED_RECYCLE_BUTTON: FEED_RECYCLE.FEED_RECYCLE_BUTTON, // 生产投料按钮
  OUTPUT_BUTTON_ASSEMBLY: OUTPUT_WEIGHING_CHILDREN.OUTPUT_BUTTON_ASSEMBLY, // 中间品产出按钮
  PRODUCT_OUTPUT_BUTTON: PRODUCT_OUTPUT_CHILDREN.PRODUCT_OUTPUT_BUTTON, // 成品产出按钮
  MATERIAL_INPUT_BUTTON: MATERIAL_INPUT.MATERIAL_INPUT_BUTTON, // 物料投入按钮
  BATCH_RECEIVE_BUTTON: BATCH_QUANTITY_PICK_BATCH_SUMMARY.BATCH_RECEIVE_BUTTON, // 批次量领料按钮
  MATERIAL_RECEIVE_BUTTON: MATERIAL_QUANTITY_PICK_MATERIAL.MATERIAL_RECEIVE_BUTTON, // 物料量领料按钮
  PICKING_RECEIVE_BUTTON: PICKING_RECEIVING_CHILDREN.PICKING_RECEIVE_BUTTON, // 领料接收按钮
  INGREDIENTS_PLAN_BUTTON: INGREDIENTS_PLAN_MATERIAL.INGREDIENTS_PLAN_BUTTON, // 配料计划按钮
  WEIGHING_INGREDIENTS_BUTTON: WEIGHING_INGREDIENTS_CHILDREN.WEIGHING_INGREDIENTS_BUTTON, // 配料称量按钮
  INGREDIENTS_INPUT_BUTTON: INGREDIENTS_INPUT.INGREDIENTS_INPUT_BUTTON, // 配料投入按钮
  MATERIAL_RESERVE_BUTTON: MATERIAL_RESERVE.MATERIAL_RESERVE_BUTTON, // 物料预订按钮
  LIQUID_PLAN_BUTTON: LIQUID_PREPARATION_PLAN.LIQUID_PLAN_BUTTON, // 配液计划按钮
  LIQUID_MEASURE_BUTTON: LIQUID_PREPARATION_MEASURE.LIQUID_MEASURE_BUTTON, // 配液量取按钮
  LIQUID_INPUT_BUTTON: LIQUID_PREPARATION_INPUT.LIQUID_INPUT_BUTTON, // 配液投入按钮
  LIQUID_OUTPUT_BUTTON: LIQUID_PREPARATION_OUTPUT.LIQUID_OUTPUT_BUTTON, // 配液产出按钮
} as any;

export const OUTPUT_BUTTON_INFO = {
  FEED_RECYCLE_BUTTON: FEED_RECYCLE.FEED_RECYCLE_BUTTON, // 生产投料按钮
  MATERIAL_INPUT_BUTTON: MATERIAL_INPUT.MATERIAL_INPUT_BUTTON, // 物料投入按钮
  OUTPUT_BUTTON_ASSEMBLY: OUTPUT_WEIGHING_CHILDREN.OUTPUT_BUTTON_ASSEMBLY, // 中间品产出按钮
  PRODUCT_OUTPUT_BUTTON: PRODUCT_OUTPUT_CHILDREN.PRODUCT_OUTPUT_BUTTON, // 成品产出按钮
  BATCH_RECEIVE_BUTTON: BATCH_QUANTITY_PICK_BATCH_SUMMARY.BATCH_RECEIVE_BUTTON, // 批次量领料按钮
  MATERIAL_RECEIVE_BUTTON: MATERIAL_QUANTITY_PICK_MATERIAL.MATERIAL_RECEIVE_BUTTON, // 物料量领料按钮
  PICKING_RECEIVE_BUTTON: PICKING_RECEIVING_CHILDREN.PICKING_RECEIVE_BUTTON, // 领料接收按钮
  INGREDIENTS_PLAN_BUTTON: INGREDIENTS_PLAN_MATERIAL.INGREDIENTS_PLAN_BUTTON, // 配料计划按钮
  WEIGHING_INGREDIENTS_BUTTON: WEIGHING_INGREDIENTS_CHILDREN.WEIGHING_INGREDIENTS_BUTTON, // 配料称量按钮
  INGREDIENTS_INPUT_BUTTON: INGREDIENTS_INPUT.INGREDIENTS_INPUT_BUTTON, // 配料投入按钮
  MATERIAL_RESERVE_BUTTON: MATERIAL_RESERVE.MATERIAL_RESERVE_BUTTON, // 物料预订按钮
  LIQUID_PLAN_BUTTON: LIQUID_PREPARATION_PLAN.LIQUID_PLAN_BUTTON, // 配液计划按钮
  LIQUID_MEASURE_BUTTON: LIQUID_PREPARATION_MEASURE.LIQUID_MEASURE_BUTTON, // 配液量取按钮
  LIQUID_INPUT_BUTTON: LIQUID_PREPARATION_INPUT.LIQUID_INPUT_BUTTON, // 配液投入按钮
  LIQUID_OUTPUT_BUTTON: LIQUID_PREPARATION_OUTPUT.LIQUID_OUTPUT_BUTTON, // 配液产出按钮
} as any;

// 所有自定义表格节点
export const ALL_DYNAMIC_TABLE_NODE = ['EQUIPMENT_DATA_ACQUISITION_DYNAMIC_TABLE'];
export const ALL_ADD_DELETE_NODE = ['EQUIPMENT_DATA_DRAW'];
// 所有根节点信息(可点击、used标识)
export const ALL_NODE_INFO = {
  CUSTOM_FIELD,
  ...NODE_INFO, // 基础组件
  ...ALL_BUSINESS_NODE_INFO, // 业务根节点组件
};

// 所有的按钮节点
export const ALL_BUTTON_INFO = [
  'CUSTOM_FIELD_BUTTON',
  'BATCH_QUANTITY_PICK_BATCH_BUTTON',
  'BATCH_QUANTITY_PICK_SUMMARY_BUTTON',
  'BUSINESS_FORMULA_INFO_MATERIAL_BUTTON',
  'MATERIAL_QUANTITY_PICK_BUTTON',
  'PICKING_RECEIVING_BATCH_BUTTON',
  'PICKING_RECEIVING_SUMMARY_BUTTON',
  'INGREDIENTS_PLAN_MATERIAL_BUTTON',
  'WEIGHING_INGREDIENTS_DETAILS_BUTTON',
  'WEIGHING_INGREDIENTS_SUMMARY_BUTTON',
  'OUTPUT_WEIGHING_DETAILS_BUTTON',
  'OUTPUT_WEIGHING_SUMMARY_BUTTON',
  'OUTPUT_BUTTON',
  'INGREDIENTS_INPUT_FEEDING_DETAILS_BUTTON',
  'INGREDIENTS_INPUT_SUMMARY_BUTTON',
  'MATERIAL_INPUT_DETAILS_BUTTON',
  'MATERIAL_INPUT_SUMMARY_BUTTON',
  'EQUIPMENT_INFO_BUTTON',
  'EQUIPMENT_DATA_ACQUISITION_GROUP_BUTTON',
  'FEED_RECYCLE_FEEDING_DETAILS_BUTTON',
  'FEED_RECYCLE_SUMMARY_BUTTON',
  'FEED_BUTTON',
  'ADD_MATERIAL_INPUT_BUTTON',
  'ADD_BATCH_RECEIVE_BUTTON',
  'ADD_MATERIAL_RECEIVE_BUTTON',
  'ADD_PICKING_RECEIVE_BUTTON',
  'ADD_INGREDIENTS_PLAN_BUTTON',
  'ADD_WEIGHING_INGREDIENTS_BUTTON',
  'ADD_INGREDIENTS_INPUT_BUTTON',
  'ADD_MATERIAL_RESERVE_BUTTON',
  'ADD_LIQUID_PLAN_BUTTON',
  'ADD_LIQUID_MEASURE_BUTTON',
  'ADD_LIQUID_INPUT_BUTTON',
  'ADD_LIQUID_OUTPUT_BUTTON',
  'PRODUCT_OUTPUT_DETAILS_BUTTON',
  'PRODUCT_OUTPUT_SUMMARY_BUTTON',
  'PRODUCT_ADD_BUTTON',
  'CLEAN_IMPLEMENT_GROUP_BUTTON',
  'CLEAN_CHECK_GROUP_BUTTON',
  'MATERIAL_RESERVE_SUMMARY_BUTTON',
  'MATERIAL_RESERVE_BATCH_BUTTON',
  'LIQUID_PREPARATION_PLAN_BATCH_BUTTON',
  'LIQUID_PREPARATION_PLAN_SUMMARY_BUTTON',
  'LIQUID_PREPARATION_MEASURE_DETAIL_BUTTON',
  'LIQUID_PREPARATION_MEASURE_SUMMARY_BUTTON',
  'LIQUID_PREPARATION_INPUT_BATCH_BUTTON',
  'LIQUID_PREPARATION_INPUT_SUMMARY_BUTTON',
  'LIQUID_PREPARATION_OUTPUT_DETAILS_BUTTON',
  'LIQUID_PREPARATION_OUTPUT_SUMMARY_BUTTON',
  'WEIGHING_DATA_DETAIL_BUTTON',
  'EQUIPMENT_DATA_DRAW_BUTTON',
  'EQUIPMENT_DATA_ACQUISITION_DYNAMIC_TABLE_BUTTON',
  'BATCH_INSPECTION_RESULTS_BUTTON',
];

// 按钮对应的子节点(按钮点击的时候使用)
export const BUTTON_CHILDREN = {
  BUSINESS_FORMULA_INFO_MATERIAL_BUTTON: BUSINESS_FORMULA_INFO_MATERIAL.BUSINESS_FORMULA_INFO_MATERIAL,
  BATCH_QUANTITY_PICK_BATCH_BUTTON: BATCH_QUANTITY_PICK_BATCH_SUMMARY.BATCH_QUANTITY_PICK_BATCH,
  BATCH_QUANTITY_PICK_SUMMARY_BUTTON: BATCH_QUANTITY_PICK_BATCH_SUMMARY.BATCH_QUANTITY_PICK_SUMMARY,
  ADD_BATCH_RECEIVE_BUTTON: BATCH_QUANTITY_PICK_BATCH_SUMMARY.BATCH_RECEIVE_BUTTON,
  MATERIAL_QUANTITY_PICK_BUTTON: MATERIAL_QUANTITY_PICK_MATERIAL.MATERIAL_QUANTITY_PICK,
  BATCH_INSPECTION_RESULTS_BUTTON: INSPECTION_RESULTS.BATCH_INSPECTION_RESULTS,
  PICKING_RECEIVING_BATCH_BUTTON: PICKING_RECEIVING_CHILDREN.PICKING_RECEIVING_BATCH,
  PICKING_RECEIVING_SUMMARY_BUTTON: PICKING_RECEIVING_CHILDREN.PICKING_RECEIVING_SUMMARY,
  INGREDIENTS_PLAN_MATERIAL_BUTTON: INGREDIENTS_PLAN_MATERIAL.INGREDIENTS_PLAN_MATERIAL,
  WEIGHING_INGREDIENTS_DETAILS_BUTTON: WEIGHING_INGREDIENTS_CHILDREN.WEIGHING_INGREDIENTS_DETAILS,
  WEIGHING_INGREDIENTS_SUMMARY_BUTTON: WEIGHING_INGREDIENTS_CHILDREN.WEIGHING_INGREDIENTS_SUMMARY,
  OUTPUT_WEIGHING_DETAILS_BUTTON: OUTPUT_WEIGHING_CHILDREN.OUTPUT_WEIGHING_DETAILS,
  OUTPUT_WEIGHING_SUMMARY_BUTTON: OUTPUT_WEIGHING_CHILDREN.OUTPUT_WEIGHING_SUMMARY,
  OUTPUT_BUTTON: OUTPUT_WEIGHING_CHILDREN.OUTPUT_BUTTON_ASSEMBLY,
  INGREDIENTS_INPUT_FEEDING_DETAILS_BUTTON: INGREDIENTS_INPUT.INGREDIENTS_INPUT_FEEDING_DETAILS,
  INGREDIENTS_INPUT_SUMMARY_BUTTON: INGREDIENTS_INPUT.INGREDIENTS_INPUT_SUMMARY,
  EQUIPMENT_INFO_BUTTON: EQUIPMENT_INFO.EQUIPMENT_INFO_BASIC,
  EQUIPMENT_DATA_ACQUISITION_GROUP_BUTTON: EQUIPMENT_DATA_ACQUISITION.EQUIPMENT_DATA_ACQUISITION_GROUP,
  EQUIPMENT_DATA_DRAW_BUTTON: EQUIPMENT_DATA_DRAW_LIST.EQUIPMENT_DATA_DRAW,
  EQUIPMENT_DATA_ACQUISITION_DYNAMIC_TABLE_BUTTON:
    EQUIPMENT_DATA_ACQUISITION_DYNAMIC_TABLE.EQUIPMENT_DATA_ACQUISITION_DYNAMIC_TABLE,
  FEED_RECYCLE_FEEDING_DETAILS_BUTTON: FEED_RECYCLE.FEED_RECYCLE_FEEDING_DETAILS,
  FEED_RECYCLE_SUMMARY_BUTTON: FEED_RECYCLE.FEED_RECYCLE_SUMMARY,
  FEED_BUTTON: FEED_RECYCLE.FEED_RECYCLE_BUTTON,
  ADD_INGREDIENTS_PLAN_BUTTON: INGREDIENTS_PLAN_MATERIAL.INGREDIENTS_PLAN_BUTTON,
  ADD_MATERIAL_RECEIVE_BUTTON: MATERIAL_QUANTITY_PICK_MATERIAL.MATERIAL_RECEIVE_BUTTON,
  ADD_PICKING_RECEIVE_BUTTON: PICKING_RECEIVING_CHILDREN.PICKING_RECEIVE_BUTTON,
  ADD_WEIGHING_INGREDIENTS_BUTTON: WEIGHING_INGREDIENTS_CHILDREN.WEIGHING_INGREDIENTS_BUTTON,
  ADD_INGREDIENTS_INPUT_BUTTON: INGREDIENTS_INPUT.INGREDIENTS_INPUT_BUTTON,
  ADD_MATERIAL_RESERVE_BUTTON: MATERIAL_RESERVE.MATERIAL_RESERVE_BUTTON,
  ADD_LIQUID_PLAN_BUTTON: LIQUID_PREPARATION_PLAN.LIQUID_PLAN_BUTTON,
  ADD_LIQUID_MEASURE_BUTTON: LIQUID_PREPARATION_MEASURE.LIQUID_MEASURE_BUTTON,
  ADD_LIQUID_INPUT_BUTTON: LIQUID_PREPARATION_INPUT.LIQUID_INPUT_BUTTON,
  ADD_LIQUID_OUTPUT_BUTTON: LIQUID_PREPARATION_OUTPUT.LIQUID_OUTPUT_BUTTON,
  PRODUCT_OUTPUT_DETAILS_BUTTON: PRODUCT_OUTPUT_CHILDREN.PRODUCT_OUTPUT_DETAILS,
  PRODUCT_OUTPUT_SUMMARY_BUTTON: PRODUCT_OUTPUT_CHILDREN.PRODUCT_OUTPUT_SUMMARY,
  PRODUCT_ADD_BUTTON: PRODUCT_OUTPUT_CHILDREN.PRODUCT_OUTPUT_BUTTON,
  CLEAN_IMPLEMENT_GROUP_BUTTON: CLEAN_IMPLEMENT.CLEAN_IMPLEMENT_GROUP,
  CLEAN_CHECK_GROUP_BUTTON: CLEAN_CHECK.CLEAN_CHECK_GROUP,
  MATERIAL_RESERVE_SUMMARY_BUTTON: MATERIAL_RESERVE.MATERIAL_RESERVE_SUMMARY,
  MATERIAL_RESERVE_BATCH_BUTTON: MATERIAL_RESERVE.MATERIAL_RESERVE_BATCH,
  MATERIAL_INPUT_DETAILS_BUTTON: MATERIAL_INPUT.MATERIAL_INPUT_DETAILS,
  MATERIAL_INPUT_SUMMARY_BUTTON: MATERIAL_INPUT.MATERIAL_INPUT_SUMMARY,
  ADD_MATERIAL_INPUT_BUTTON: MATERIAL_INPUT.MATERIAL_INPUT_BUTTON,
  LIQUID_PREPARATION_PLAN_BATCH_BUTTON: LIQUID_PREPARATION_PLAN.LIQUID_PREPARATION_PLAN_BATCH,
  LIQUID_PREPARATION_PLAN_SUMMARY_BUTTON: LIQUID_PREPARATION_PLAN.LIQUID_PREPARATION_PLAN_SUMMARY,
  LIQUID_PREPARATION_MEASURE_DETAIL_BUTTON: LIQUID_PREPARATION_MEASURE.LIQUID_PREPARATION_MEASURE_DETAIL,
  LIQUID_PREPARATION_MEASURE_SUMMARY_BUTTON: LIQUID_PREPARATION_MEASURE.LIQUID_PREPARATION_MEASURE_SUMMARY,
  LIQUID_PREPARATION_INPUT_BATCH_BUTTON: LIQUID_PREPARATION_INPUT.LIQUID_PREPARATION_INPUT_DETAIL,
  LIQUID_PREPARATION_INPUT_SUMMARY_BUTTON: LIQUID_PREPARATION_INPUT.LIQUID_PREPARATION_INPUT_SUMMARY,
  LIQUID_PREPARATION_OUTPUT_DETAILS_BUTTON: LIQUID_PREPARATION_OUTPUT.LIQUID_PREPARATION_OUTPUT_DETAILS,
  LIQUID_PREPARATION_OUTPUT_SUMMARY_BUTTON: LIQUID_PREPARATION_OUTPUT.LIQUID_PREPARATION_OUTPUT_SUMMARY,
  WEIGHING_DATA_DETAIL_BUTTON: WEIGHING_DATA.WEIGHING_DATA_DETAIL,
} as any;

export const COPY_BUSINESS_NODE_INFO = {
  BUSINESS_FORMULA_INFO_MATERIAL: 'BUSINESS_FORMULA_INFO_MATERIAL_BUTTON',
  BATCH_QUANTITY_PICK_BATCH: 'BATCH_QUANTITY_PICK_BATCH_BUTTON',
  BATCH_QUANTITY_PICK_SUMMARY: 'BATCH_QUANTITY_PICK_SUMMARY_BUTTON',
  MATERIAL_QUANTITY_PICK_MATERIAL: 'MATERIAL_QUANTITY_PICK_BUTTON',
  BATCH_INSPECTION_RESULTS: 'BATCH_INSPECTION_RESULTS_BUTTON',
  PICKING_RECEIVING_BATCH: 'PICKING_RECEIVING_BATCH_BUTTON',
  PICKING_RECEIVING_SUMMARY: 'PICKING_RECEIVING_SUMMARY_BUTTON',
  INGREDIENTS_PLAN_MATERIAL: 'INGREDIENTS_PLAN_MATERIAL_BUTTON',
  WEIGHING_INGREDIENTS_DETAILS: 'WEIGHING_INGREDIENTS_DETAILS_BUTTON',
  WEIGHING_INGREDIENTS_SUMMARY: 'WEIGHING_INGREDIENTS_SUMMARY_BUTTON',
  OUTPUT_WEIGHING_DETAILS: 'OUTPUT_WEIGHING_DETAILS_BUTTON',
  OUTPUT_WEIGHING_SUMMARY: 'OUTPUT_WEIGHING_SUMMARY_BUTTON',
  INGREDIENTS_INPUT_FEEDING_DETAILS: 'INGREDIENTS_INPUT_FEEDING_DETAILS_BUTTON',
  INGREDIENTS_INPUT_SUMMARY: 'INGREDIENTS_INPUT_SUMMARY_BUTTON',
  EQUIPMENT_INFO_BASIC: 'EQUIPMENT_INFO_BUTTON',
  EQUIPMENT_DATA_ACQUISITION_GROUP: 'EQUIPMENT_DATA_ACQUISITION_GROUP_BUTTON',
  FEED_RECYCLE_FEEDING_DETAILS: 'FEED_RECYCLE_FEEDING_DETAILS_BUTTON',
  FEED_RECYCLE_SUMMARY: 'FEED_RECYCLE_SUMMARY_BUTTON',
  PRODUCT_OUTPUT_DETAILS: 'PRODUCT_OUTPUT_DETAILS_BUTTON',
  PRODUCT_OUTPUT_SUMMARY: 'PRODUCT_OUTPUT_SUMMARY_BUTTON',
  CLEAN_IMPLEMENT_GROUP: 'CLEAN_IMPLEMENT_GROUP_BUTTON',
  CLEAN_CHECK_GROUP: 'CLEAN_CHECK_GROUP_BUTTON',
  MATERIAL_RESERVE_SUMMARY: 'MATERIAL_RESERVE_SUMMARY_BUTTON',
  MATERIAL_RESERVE_BATCH: 'MATERIAL_RESERVE_BATCH_BUTTON',
  MATERIAL_INPUT_DETAILS: 'MATERIAL_INPUT_DETAILS_BUTTON',
  MATERIAL_INPUT_SUMMARY: 'MATERIAL_INPUT_SUMMARY_BUTTON',
  LIQUID_PREPARATION_PLAN_BATCH: 'LIQUID_PREPARATION_PLAN_BATCH_BUTTON',
  LIQUID_PREPARATION_PLAN_SUMMARY: 'LIQUID_PREPARATION_PLAN_SUMMARY_BUTTON',
  LIQUID_PREPARATION_MEASURE_DETAIL: 'LIQUID_PREPARATION_MEASURE_DETAIL_BUTTON',
  LIQUID_PREPARATION_MEASURE_SUMMARY: 'LIQUID_PREPARATION_MEASURE_SUMMARY_BUTTON',
  LIQUID_PREPARATION_INPUT_DETAIL: 'LIQUID_PREPARATION_INPUT_BATCH_BUTTON',
  LIQUID_PREPARATION_INPUT_SUMMARY: 'LIQUID_PREPARATION_INPUT_SUMMARY_BUTTON',
  LIQUID_PREPARATION_OUTPUT_DETAILS: 'LIQUID_PREPARATION_OUTPUT_DETAILS_BUTTON',
  LIQUID_PREPARATION_OUTPUT_SUMMARY: 'LIQUID_PREPARATION_OUTPUT_SUMMARY_BUTTON',
  WEIGHING_DATA_DETAIL: 'WEIGHING_DATA_DETAIL_BUTTON',
} as any;

// 如果业务组件中包含组添加按钮，则在此处添加
// apps\bmos-mes-web\src\pages\TemplateEdit\hooks\useTree.tsx
// 编辑时在addButtonForBusinessComponent中添加业务组件按钮

// 以下主要为公式使用的组件类型
// 文字类型组件数组
export const TEXT_COMPONENT = [
  'TEXT',
  // 生产信息
  'BUSINESS_PRODUCT_INFO_NAME',
  'BUSINESS_PRODUCT_INFO_CODE',
  'BUSINESS_PRODUCT_INFO_SPECIFICATION',
  'BUSINESS_PRODUCT_INFO_PROCESS_NAME',
  'BUSINESS_PRODUCT_INFO_BATCHNO',
  'BUSINESS_PRODUCT_INFO_UNIT',
  // 生产BOM信息
  'BUSINESS_FORMULA_INFO_MATERIAL_NAME',
  'BUSINESS_FORMULA_INFO_MATERIAL_CODE',
  'BUSINESS_FORMULA_INFO_MATERIAL_SPECIFICATION',
  'BUSINESS_FORMULA_INFO_UNIT',
  // 物料量领料
  'MATERIAL_QUANTITY_PICK_MATERIAL_NAME',
  'MATERIAL_QUANTITY_PICK_MATERIAL_CODE',
  'MATERIAL_QUANTITY_PICK_MATERIAL_SPECIFICATION',
  'MATERIAL_QUANTITY_PICK_MATERIAL_UNIT',
  'MATERIAL_QUANTITY_PICK_MATERIAL_SUPPLIER',
  'MATERIAL_QUANTITY_PICK_MATERIAL_MANUFACTURER',
  // 批次量领料
  'BATCH_QUANTITY_PICK_BATCH_NAME',
  'BATCH_QUANTITY_PICK_BATCH_CODE',
  'BATCH_QUANTITY_PICK_BATCH_SPECIFICATION',
  'BATCH_QUANTITY_PICK_BATCH_BATCHNO',
  'BATCH_QUANTITY_PICK_UNIT',
  'BATCH_QUANTITY_PICK_SUPPLIER',
  'BATCH_QUANTITY_PICK_PRODUCER',
  'BATCH_QUANTITY_PICK_ORIGIN_BATCHNO',
  'BATCH_QUANTITY_PICK_ORIGIN_CODE',
  'BATCH_QUANTITY_PICK_BATCH_SUMMARY_NAME',
  'BATCH_QUANTITY_PICK_BATCH_SUMMARY_CODE',
  'BATCH_QUANTITY_PICK_BATCH_SUMMARY_SPECIFICATION',
  'BATCH_QUANTITY_PICK_BATCH_SUMMARY_UNIT',
  // 领料接收
  'PICKING_RECEIVING_BATCH_NAME',
  'PICKING_RECEIVING_BATCH_CODE',
  'PICKING_RECEIVING_BATCH_SPECIFICATION',
  'PICKING_RECEIVING_BATCH_BATCHNO',
  'PICKING_RECEIVING_BATCH_UNIT',
  'PICKING_RECEIVING_BATCH_SUPPLIER',
  'PICKING_RECEIVING_BATCH_PRODUCER',
  'PICKING_RECEIVING_BATCH_ORIGINAL_BATCHNO',
  'PICKING_RECEIVING_BATCH_ORIGINAL_CODE',
  'PICKING_RECEIVING_SUMMARY_NAME',
  'PICKING_RECEIVING_SUMMARY_CODE',
  'PICKING_RECEIVING_SUMMARY_SPECIFICATION',
  'PICKING_RECEIVING_SUMMARY_UNIT',
  // 配料计划
  'INGREDIENTS_PLAN_MATERIAL_NAME',
  'INGREDIENTS_PLAN_MATERIAL_CODE',
  'INGREDIENTS_PLAN_MATERIAL_SPECIFICATION',
  'INGREDIENTS_PLAN_MATERIAL_BATCHNO',
  'INGREDIENTS_PLAN_MATERIAL_UNIT',
  'INGREDIENTS_PLAN_MATERIAL_SUPPLIER',
  'INGREDIENTS_PLAN_MATERIAL_MANUFACTURER',
  'INGREDIENTS_PLAN_MATERIAL_ORIGINAL_BATCHNO',
  'INGREDIENTS_PLAN_MATERIAL_ORIGINAL_CODE',
  'INGREDIENTS_PLAN_MATERIAL_REPORT_NO',
  'INGREDIENTS_PLAN_MATERIAL_RELEASE_NO',
  // 配料称量
  'WEIGHING_INGREDIENTS_DETAILS_NAME',
  'WEIGHING_INGREDIENTS_DETAILS_CODE',
  'WEIGHING_INGREDIENTS_DETAILS_SPECIFICATION',
  'WEIGHING_INGREDIENTS_DETAILS_BATCHNO',
  'WEIGHING_INGREDIENTS_DETAILS_PART_NUMBER',
  'WEIGHING_INGREDIENTS_DETAILS_UNIT',
  'WEIGHING_INGREDIENTS_DETAILS_WEIGHER',
  'WEIGHING_INGREDIENTS_DETAILS_REVIEWER',
  'WEIGHING_INGREDIENTS_SUMMARY_NAME',
  'WEIGHING_INGREDIENTS_SUMMARY_CODE',
  'WEIGHING_INGREDIENTS_SUMMARY_SPECIFICATION',
  'WEIGHING_INGREDIENTS_SUMMARY_UNIT',
  // 产出称量
  'OUTPUT_WEIGHING_DETAILS_NAME',
  'OUTPUT_WEIGHING_DETAILS_CODE',
  'OUTPUT_WEIGHING_DETAILS_SPECIFICATION',
  'OUTPUT_WEIGHING_DETAILS_BATCHNO',
  'OUTPUT_WEIGHING_DETAILS_PART_NUMBER',
  'OUTPUT_WEIGHING_DETAILS_UNIT',
  'OUTPUT_WEIGHING_DETAILS_WEIGHER',
  'OUTPUT_WEIGHING_DETAILS_REVIEWER',
  'OUTPUT_WEIGHING_SUMMARY_NAME',
  'OUTPUT_WEIGHING_SUMMARY_CODE',
  'OUTPUT_WEIGHING_SUMMARY_SPECIFICATION',
  'OUTPUT_WEIGHING_SUMMARY_UNIT',
  // 配料投入
  'INGREDIENTS_INPUT_FEEDING_DETAILS_MATERIAL_NAME',
  'INGREDIENTS_INPUT_FEEDING_DETAILS_MATERIAL_CODE',
  'INGREDIENTS_INPUT_FEEDING_DETAILS_MATERIAL_SPECIFICATION',
  'INGREDIENTS_INPUT_FEEDING_DETAILS_MATERIAL_BATCHNO',
  'INGREDIENTS_INPUT_FEEDING_DETAILS_MATERIAL_PARTNO',
  'INGREDIENTS_INPUT_FEEDING_DETAILS_UNIT',
  'INGREDIENTS_INPUT_FEEDING_DETAILS_FEEDER',
  'INGREDIENTS_INPUT_FEEDING_DETAILS_DEVICE_NAME',
  'INGREDIENTS_INPUT_FEEDING_DETAILS_DEVICE_CODE',
  'INGREDIENTS_INPUT_SUMMARY_MATERIAL_NAME',
  'INGREDIENTS_INPUT_SUMMARY_MATERIAL_CODE',
  'INGREDIENTS_INPUT_SUMMARY_MATERIAL_SPECIFICATION',
  'INGREDIENTS_INPUT_SUMMARY_UNIT',
  // 生产投料
  'FEED_RECYCLE_FEEDING_DETAILS_MATERIAL_NAME',
  'FEED_RECYCLE_FEEDING_DETAILS_MATERIAL_CODE',
  'FEED_RECYCLE_FEEDING_DETAILS_MATERIAL_SPECIFICATION',
  'FEED_RECYCLE_FEEDING_DETAILS_MATERIAL_BATCHNO',
  'FEED_RECYCLE_FEEDING_DETAILS_MATERIAL_PARTNO',
  'FEED_RECYCLE_FEEDING_DETAILS_UNIT',
  'FEED_RECYCLE_FEEDING_DETAILS_OPERATION_TYPE',
  'FEED_RECYCLE_FEEDING_DETAILS_OPERATOR',
  'FEED_RECYCLE_FEEDING_DETAILS_DEVICE_NAME',
  'FEED_RECYCLE_FEEDING_DETAILS_DEVICE_CODE',
  'FEED_RECYCLE_SUMMARY_MATERIAL_NAME',
  'FEED_RECYCLE_SUMMARY_MATERIAL_CODE',
  'FEED_RECYCLE_SUMMARY_MATERIAL_SPECIFICATION',
  'FEED_RECYCLE_SUMMARY_UNIT',
  // 成品产出
  'PRODUCT_OUTPUT_DETAILS_NAME',
  'PRODUCT_OUTPUT_DETAILS_CODE',
  'PRODUCT_OUTPUT_DETAILS_SPECIFICATION',
  'PRODUCT_OUTPUT_DETAILS_BATCH_NO',
  'PRODUCT_OUTPUT_DETAILS_UNIT',
  'PRODUCT_OUTPUT_DETAILS_OPERATOR',
  'PRODUCT_OUTPUT_SUMMARY_NAME',
  'PRODUCT_OUTPUT_SUMMARY_CODE',
  'PRODUCT_OUTPUT_SUMMARY_SPECIFICATION',
  'PRODUCT_OUTPUT_SUMMARY_OUTPUT_TOTAL',
  // 设备信息
  'EQUIPMENT_INFO_NAME',
  'EQUIPMENT_INFO_CODE',
  'EQUIPMENT_INFO_BASIC',
  // 清场执行
  'CLEAN_IMPLEMENT_BATCHNO',
  'CLEAN_IMPLEMENT_PRODUCT_NAME',
  'CLEAN_IMPLEMENT_PRODUCT_NO',
  'CLEAN_IMPLEMENT_PROCEDURE',
  'CLEAN_IMPLEMENT_ROOM_CODE',
  // 清场检查
  'CLEAN_CHECK_BATCHNO',
  'CLEAN_CHECK_PRODUCT_NAME',
  'CLEAN_CHECK_PRODUCT_NO',
  'CLEAN_CHECK_PROCEDURE',
  'CLEAN_CHECK_ROOM_CODE',
  // 清场信息
  'CLEAN_INFO_BATCHNO',
  'CLEAN_INFO_PRODUCT_NAME',
  'CLEAN_INFO_PRODUCT_NO',
  'CLEAN_INFO_PROCEDURE',
  'CLEAN_INFO_ROOM_CODE',
  // 物料预定
  'MATERIAL_RESERVE_MATERIAL_NAME',
  'MATERIAL_RESERVE_MATERIAL_CODE',
  'MATERIAL_RESERVE_MATERIAL_SPECIFICATION',
  'MATERIAL_RESERVE_BATCH_NO',
  'MATERIAL_RESERVE_UNIT',
  'MATERIAL_RESERVE_SUPPLIER',
  'MATERIAL_RESERVE_MANUFACTURER',
  'MATERIAL_RESERVE_ORIGINAL_BATCH_NO',
  'MATERIAL_RESERVE_ORIGINAL_CODE',
  'MATERIAL_RESERVE_REPORT_NO',
  'MATERIAL_RESERVE_RELEASE_NO',
  'MATERIAL_RESERVE_BATCH_MATERIAL_NAME',
  'MATERIAL_RESERVE_BATCH_MATERIAL_CODE',
  'MATERIAL_RESERVE_BATCH_MATERIAL_SPECIFICATION',
  'MATERIAL_RESERVE_BATCH_BATCH_NO',
  'MATERIAL_RESERVE_BATCH_UNIT',
  'MATERIAL_RESERVE_BATCH_SUPPLIER',
  'MATERIAL_RESERVE_BATCH_MANUFACTURER',
  'MATERIAL_RESERVE_BATCH_ORIGINAL_BATCH_NO',
  'MATERIAL_RESERVE_BATCH_ORIGINAL_CODE',
  'MATERIAL_RESERVE_BATCH_REPORT_NO',
  'MATERIAL_RESERVE_BATCH_RELEASE_NO',
  // 生产投料
  'MATERIAL_INPUT_DETAILS_MATERIAL_NAME',
  'MATERIAL_INPUT_DETAILS_MATERIAL_CODE',
  'MATERIAL_INPUT_DETAILS_MATERIAL_SPECIFICATION',
  'MATERIAL_INPUT_DETAILS_MATERIAL_BATCHNO',
  'MATERIAL_INPUT_DETAILS_MATERIAL_PARTNO',
  'MATERIAL_INPUT_DETAILS_UNIT',
  'MATERIAL_INPUT_DETAILS_FEEDER',
  'MATERIAL_INPUT_DETAILS_DEVICE_NAME',
  'MATERIAL_INPUT_DETAILS_DEVICE_CODE',
  'MATERIAL_INPUT_SUMMARY_MATERIAL_NAME',
  'MATERIAL_INPUT_SUMMARY_MATERIAL_CODE',
  'MATERIAL_INPUT_SUMMARY_MATERIAL_SPECIFICATION',
  'MATERIAL_INPUT_SUMMARY_UNIT',
  // 配液计划
  'LIQUID_PREPARATION_PLAN_BATCH_NAME',
  'LIQUID_PREPARATION_PLAN_BATCH_CODE',
  'LIQUID_PREPARATION_PLAN_BATCH_SPECIFICATION',
  'LIQUID_PREPARATION_PLAN_BATCH_BATCHNO',
  'LIQUID_PREPARATION_PLAN_BATCH_UNIT',
  'LIQUID_PREPARATION_PLAN_BATCH_SUPPLIER',
  'LIQUID_PREPARATION_PLAN_BATCH_MANUFACTURER',
  'LIQUID_PREPARATION_PLAN_BATCH_ORIGINAL_BATCHNO',
  'LIQUID_PREPARATION_PLAN_BATCH_ORIGINAL_CODE',
  'LIQUID_PREPARATION_PLAN_BATCH_REPORT_NO',
  'LIQUID_PREPARATION_PLAN_BATCH_RELEASE_NO',
  'LIQUID_PREPARATION_PLAN_SUMMARY_NAME',
  'LIQUID_PREPARATION_PLAN_SUMMARY_CODE',
  'LIQUID_PREPARATION_PLAN_SUMMARY_SPECIFICATION',
  'LIQUID_PREPARATION_PLAN_SUMMARY_BATCHNO',
  'LIQUID_PREPARATION_PLAN_SUMMARY_UNIT',
  'LIQUID_PREPARATION_PLAN_SUMMARY_SUPPLIER',
  'LIQUID_PREPARATION_PLAN_SUMMARY_MANUFACTURER',
  'LIQUID_PREPARATION_PLAN_SUMMARY_ORIGINAL_BATCHNO',
  'LIQUID_PREPARATION_PLAN_SUMMARY_ORIGINAL_CODE',
  'LIQUID_PREPARATION_PLAN_SUMMARY_REPORT_NO',
  'LIQUID_PREPARATION_PLAN_SUMMARY_RELEASE_NO',
  // 配液量取
  'LIQUID_PREPARATION_MEASURE_DETAIL_NAME',
  'LIQUID_PREPARATION_MEASURE_DETAIL_CODE',
  'LIQUID_PREPARATION_MEASURE_DETAIL_SPECIFICATION',
  'LIQUID_PREPARATION_MEASURE_DETAIL_BATCHNO',
  'LIQUID_PREPARATION_MEASURE_DETAIL_PARTNO',
  'LIQUID_PREPARATION_MEASURE_DETAIL_UNIT',
  'LIQUID_PREPARATION_MEASURE_DETAIL_OPERATOR',
  'LIQUID_PREPARATION_MEASURE_DETAIL_REVIEWER',
  'LIQUID_PREPARATION_MEASURE_SUMMARY_NAME',
  'LIQUID_PREPARATION_MEASURE_SUMMARY_CODE',
  'LIQUID_PREPARATION_MEASURE_SUMMARY_SPECIFICATION',
  'LIQUID_PREPARATION_MEASURE_SUMMARY_UNIT',
  // 配液投入
  'LIQUID_PREPARATION_INPUT_DETAIL_NAME',
  'LIQUID_PREPARATION_INPUT_DETAIL_CODE',
  'LIQUID_PREPARATION_INPUT_DETAIL_SPECIFICATION',
  'LIQUID_PREPARATION_INPUT_DETAIL_BATCH_NO',
  'LIQUID_PREPARATION_INPUT_DETAIL_PART_NO',
  'LIQUID_PREPARATION_INPUT_DETAIL_UNIT',
  'LIQUID_PREPARATION_INPUT_DETAIL_IMPORTER',
  'LIQUID_PREPARATION_INPUT_DETAIL_CONTAINER_NAME',
  'LIQUID_PREPARATION_INPUT_DETAIL_DEVICE_NO',
  'LIQUID_PREPARATION_INPUT_BATCH_ORIGINAL_CODE',
  'LIQUID_PREPARATION_INPUT_BATCH_REPORT_NO',
  'LIQUID_PREPARATION_INPUT_BATCH_RELEASE_NO',
  'LIQUID_PREPARATION_INPUT_SUMMARY_NAME',
  'LIQUID_PREPARATION_INPUT_SUMMARY_CODE',
  'LIQUID_PREPARATION_INPUT_SUMMARY_SPECIFICATION',
  'LIQUID_PREPARATION_INPUT_SUMMARY_UNIT',
  // 配液产出
  'LIQUID_PREPARATION_OUTPUT_DETAILS_NAME',
  'LIQUID_PREPARATION_OUTPUT_DETAILS_CODE',
  'LIQUID_PREPARATION_OUTPUT_DETAILS_SPECIFICATION',
  'LIQUID_PREPARATION_OUTPUT_DETAILS_BATCHNO',
  'LIQUID_PREPARATION_OUTPUT_DETAILS_PARTNO',
  'LIQUID_PREPARATION_OUTPUT_DETAILS_UNIT',
  'LIQUID_PREPARATION_OUTPUT_DETAILS_OPERATOR',
  'LIQUID_PREPARATION_OUTPUT_DETAILS_REVIEWER',
  'LIQUID_PREPARATION_OUTPUT_SUMMARY_NAME',
  'LIQUID_PREPARATION_OUTPUT_SUMMARY_CODE',
  'LIQUID_PREPARATION_OUTPUT_SUMMARY_SPECIFICATION',
  'LIQUID_PREPARATION_OUTPUT_SUMMARY_UNIT',
  // 物料件信息
  'MATERIAL_INFO_MATERIAL_NAME',
  'MATERIAL_INFO_MATERIAL_CODE',
  'MATERIAL_INFO_MATERIAL_BATCHNO',
  'MATERIAL_INFO_MATERIAL_PARTNO',
  'MATERIAL_INFO_UNIT',
  // 称量数据
  'WEIGHING_DATA_DETAIL_UNIT',
  'WEIGHING_DATA_DETAIL_OPERATOR',
];

// 日期类型组件数组
export const DATE_COMPONENT = [
  'DATE',
  // 批次量领料
  'BATCH_QUANTITY_PICK_EXPIRATION_DATE',
  // 领料接收
  'PICKING_RECEIVING_BATCH_EXPIRATION_DATE',
  // 配料计划
  'INGREDIENTS_PLAN_MATERIAL_EXPIRATION_DATE',
  // 配料称量
  'WEIGHING_INGREDIENTS_DETAILS_WEIGHING_TIME',
  // 产出称量
  'OUTPUT_WEIGHING_DETAILS_WEIGHING_TIME',
  // 配料投入
  'INGREDIENTS_INPUT_FEEDING_DETAILS_FEEDING_TIME',
  // 设备数采
  'EQUIPMENT_DATA_ACQUISITION_TIME',
  // 生产投料
  'FEED_RECYCLE_FEEDING_DETAILS_OPERATION_TIME',
  // 成品产出
  'PRODUCT_OUTPUT_DETAILS_OPERATE_TIME',
  // 清场执行
  'CLEAN_IMPLEMENT_CLEAN_DATE',
  'CLEAN_IMPLEMENT_ROOM_QUALITY_INSPECTION_DATE',
  'CLEAN_IMPLEMENT_START_TIME',
  'CLEAN_IMPLEMENT_END_TIME',
  'CLEAN_IMPLEMENT_EXPIRATION_DATE',
  // 清场检查
  'CLEAN_CHECK_CLEAN_DATE',
  'CLEAN_CHECK_ROOM_QUALITY_INSPECTION_DATE',
  'CLEAN_CHECK_START_TIME',
  'CLEAN_CHECK_END_TIME',
  'CLEAN_CHECK_EXPIRATION_DATE',
  // 清场信息
  'CLEAN_INFO_START_TIME',
  'CLEAN_INFO_END_TIME',
  'CLEAN_INFO_EXPIRATION_DATE',
  'CLEAN_INFO_CLEAN_DATE',
  'CLEAN_INFO_ROOM_QUALITY_INSPECTION_DATE',
  // 物料预定
  'MATERIAL_RESERVE_EXPIRATION_DATE',
  'MATERIAL_RESERVE_BATCH_EXPIRATION_DATE',
  // 生产投料
  'MATERIAL_INPUT_DETAILS_FEEDING_TIME',
  // 配液计划
  'LIQUID_PREPARATION_PLAN_BATCH_EXPIRY_DATE',
  'LIQUID_PREPARATION_PLAN_SUMMARY_EXPIRY_DATE',
  // 配液量取
  'LIQUID_PREPARATION_MEASURE_DETAIL_OPERATION_TIME',
  // 配液投入
  'LIQUID_PREPARATION_INPUT_DETAIL_INPUT_TIME',
  // 配液产出
  'LIQUID_PREPARATION_OUTPUT_DETAILS_OUTPUT_TIME',
  // 称量数据
  'WEIGHING_DATA_DETAIL_TIME',
];

// 时间类型组件数组
export const TIME_COMPONENT = ['TIME'];

// 数字类型组件数组
export const NUMBER_COMPONENT = [
  'NUMBER',
  // 生产信息
  'BUSINESS_PRODUCT_INFO_BATCH',
  'BUSINESS_PRODUCT_INFO_REVISION_NUMBER',
  // 生产BOM信息
  'BUSINESS_FORMULA_INFO_THEORETICAL_QUANTITY',
  // 物料量领料
  'MATERIAL_QUANTITY_PICK_MATERIAL_PICK',
  // 批次量领料
  'BATCH_QUANTITY_PICK_PLAN_PICK',
  'BATCH_QUANTITY_PICK_THEORY_MATERIAL',
  'BATCH_QUANTITY_PICK_MOISTURE',
  'BATCH_QUANTITY_PICK_CONTENT',
  'BATCH_QUANTITY_PICK_BATCH_SUMMARY_PLAN_PICK',
  'BATCH_QUANTITY_PICK_BATCH_SUMMARY_THEORY_MATERIAL',
  // 领料接收
  'PICKING_RECEIVING_BATCH_PICK',
  'PICKING_RECEIVING_SUMMARY_PICK',
  // 配料计划
  'INGREDIENTS_PLAN_MATERIAL_QUANTITY',
  'INGREDIENTS_PLAN_MATERIAL_TOTAL',
  'INGREDIENTS_PLAN_MATERIAL_MOISTURE',
  'INGREDIENTS_PLAN_MATERIAL_CONTENT',
  // 配料称量
  'WEIGHING_INGREDIENTS_DETAILS_NET_WEIGHT',
  'WEIGHING_INGREDIENTS_DETAILS_TARE_WEIGHT',
  'WEIGHING_INGREDIENTS_DETAILS_GROSS_WEIGHT',
  'WEIGHING_INGREDIENTS_SUMMARY_NET_WEIGHT',
  'WEIGHING_INGREDIENTS_SUMMARY_TARE_WEIGHT',
  'WEIGHING_INGREDIENTS_SUMMARY_GROSS_WEIGHT',
  'WEIGHING_INGREDIENTS_SUMMARY_TOTAL_NUMBER',
  // 产出称量
  'OUTPUT_WEIGHING_DETAILS_NET_WEIGHT',
  'OUTPUT_WEIGHING_DETAILS_TARE_WEIGHT',
  'OUTPUT_WEIGHING_DETAILS_GROSS_WEIGHT',
  'OUTPUT_WEIGHING_SUMMARY_NET_WEIGHT',
  'OUTPUT_WEIGHING_SUMMARY_TARE_WEIGHT',
  'OUTPUT_WEIGHING_SUMMARY_GROSS_WEIGHT',
  'OUTPUT_WEIGHING_SUMMARY_TOTAL_NUMBER',
  'OUTPUT_WEIGHING_DETAILS_QUANTITY',
  'OUTPUT_WEIGHING_SUMMARY_TOTAL_QUANTITY',
  // 配料投入
  'INGREDIENTS_INPUT_FEEDING_DETAILS_MATERIAL_QUANTITY',
  'INGREDIENTS_INPUT_SUMMARY_TOTAL_QUANTITY',
  'INGREDIENTS_INPUT_SUMMARY_TOTAL_NUMBER',
  // 生产投料
  'FEED_RECYCLE_FEEDING_DETAILS_MATERIAL_QUANTITY',
  'FEED_RECYCLE_SUMMARY_TOTAL_QUANTITY',
  'FEED_RECYCLE_SUMMARY_RECYCLE_TOTAL_QUANTITY',
  'FEED_RECYCLE_SUMMARY_USE_TOTAL_QUANTITY',
  'FEED_RECYCLE_SUMMARY_TOTAL_NUMBER',
  'FEED_RECYCLE_SUMMARY_RECYCLE_TOTAL_NUMBER',
  // 设备数采-数采点
  'EQUIPMENT_DATA_ACQUISITION_POINT',
  // 成品产出
  'PRODUCT_OUTPUT_DETAILS_SINGLE_QUANTITY',
  'PRODUCT_OUTPUT_DETAILS_SIZE',
  'PRODUCT_OUTPUT_SUMMARY_SIZE_TOTAL',
  // 物料预定
  'MATERIAL_RESERVE_BATCH_RESERVE_QUANTITY',
  'MATERIAL_RESERVE_RESERVE_TOTAL_QUANTITY',
  'MATERIAL_RESERVE_BATCH_CURRENT_RESERVE_QUANTITY',
  'MATERIAL_RESERVE_CURRENT_RESERVE_TOTAL_QUANTITY',
  'MATERIAL_RESERVE_MOISTURE',
  'MATERIAL_RESERVE_CONTENT',
  'MATERIAL_RESERVE_BATCH_BATCH_RESERVE_QUANTITY',
  'MATERIAL_RESERVE_BATCH_MOISTURE',
  'MATERIAL_RESERVE_BATCH_CONTENT',
  // 生产投料
  'MATERIAL_INPUT_DETAILS_MATERIAL_QUANTITY',
  'MATERIAL_INPUT_SUMMARY_TOTAL_QUANTITY',
  'MATERIAL_INPUT_SUMMARY_TOTAL_NUMBER',
  // 配液计划
  'LIQUID_PREPARATION_PLAN_BATCH_QUANTITY',
  'LIQUID_PREPARATION_PLAN_SUMMARY_QUANTITY',
  'LIQUID_PREPARATION_PLAN_SUMMARY_TOTAL_QUANTITY',
  // 配液量取
  'LIQUID_PREPARATION_MEASURE_DETAIL_QUANTITY',
  'LIQUID_PREPARATION_MEASURE_SUMMARY_TOTAL_QUANTITY',
  'LIQUID_PREPARATION_MEASURE_SUMMARY_TOTAL_COUNT',
  // 配液投入
  'LIQUID_PREPARATION_INPUT_DETAIL_QUANTITY',
  'LIQUID_PREPARATION_INPUT_SUMMARY_TOTAL_QUANTITY',
  'LIQUID_PREPARATION_INPUT_SUMMARY_TOTAL_COUNT',
  // 配液产出
  'LIQUID_PREPARATION_OUTPUT_DETAILS_QUANTITY',
  'LIQUID_PREPARATION_OUTPUT_SUMMARY_TOTAL_QUANTITY',
  'LIQUID_PREPARATION_OUTPUT_SUMMARY_PARTNO',
  // 物料件信息
  'MATERIAL_INFO_MATERIAL_QUANTITY',
  'MATERIAL_INFO_NET_WEIGHT',
  'MATERIAL_INFO_TARE_WEIGHT',
  'MATERIAL_INFO_GROSS_WEIGHT',
  // 称量数据
  'WEIGHING_DATA_DETAIL_WEIGHT',
];

// 选择类型组件数组
export const SELECT_COMPONENT = [
  'SELECT',
  // 清场执行
  'CLEAN_IMPLEMENT_ROOM_NAME',
  // 清场检查
  'CLEAN_CHECK_ROOM_NAME',
  // 清场信息
  'CLEAN_INFO_ROOM_NAME',
];

// 签名类型组件数组
export const SUBMIT_SIGN_COMPONENT = [
  'SUBMIT_SIGN',
  // 清场执行
  'CLEAN_IMPLEMENT_CLEAN_PERSON',
  'CLEAN_IMPLEMENT_QUALITY_INSPECTION_PERSON',
  // 清场检查
  'CLEAN_CHECK_CLEAN_PERSON',
  'CLEAN_CHECK_QUALITY_INSPECTION_PERSON',
  // 清场信息
  'CLEAN_INFO_CLEAN_PERSON',
  'CLEAN_INFO_QUALITY_INSPECTION_PERSON',
];
export const REVIEW_SIGN_COMPONENT = ['SUBMIT_SIGN', 'REVIEW_SIGN'];
export const HANDLE_REVIEW_SIGN_COMPONENT = ['HANDLE_REVIEW_SIGN'];
export const HANDLE_SUBMIT_SIGN_COMPONENT = ['HANDLE_SUBMIT_SIGN'];
export const CUSTOM_FIELD_COMPONENT = ['CUSTOM_FIELD'];
