export const constantRoutes = [
  {
    path: '/',
    name: 'Index',
    meta: {
      title: '首页',
      code: '首页',
      // hiddenMenu: true,
    },
    redirect: '/home',
    component: () => import('../pages/Main/index.vue'),
    children: [
      { path: '/home', component: () => import('../pages/Home/index.vue') },
      {
        path: '/product-config/process-approval/process-audit-schedule',
        component: () => import('@/pages/ProductConfig/ProcessApproval/components/SchedulePage/index.vue'),
        meta: {
          title: '工艺审核进度',
          code: '120020007',
          id: '120020007',
          hidden: false,
          parentPath: '/product-config/process-approval',
        },
        name: 'process-audit-schedule',
      },
      {
        path: '/product-config/process-config/process-config-schedule',
        component: () => import('@/pages/ProductConfig/ProcessApproval/components/SchedulePage/index.vue'),
        meta: {
          title: '工艺审核进度',
          code: '120020006',
          id: '120020006',
          hidden: false,
          parentPath: '/product-config/process-config',
        },
        name: 'process-config-schedule',
      },
      {
        path: '/exception/information',
        component: () => import('@/pages/Exception/information/index.vue'),
        meta: {
          title: '批次异常管理',
          code: '120090002',
          id: '120090002',
          hidden: false,
          parentPath: '/exception',
        },
        name: 'exceptionInformation',
      },
      {
        path: '/product-config/record-config/record-config-schedule',
        component: () => import('@/pages/ProductConfig/RecordReview/components/SchedulePage/index.vue'),
        meta: {
          title: '记录配置审核进度',
          code: '120020001',
          id: '120020001',
          hidden: false,
          parentPath: '/product-config/record-config',
        },
        name: 'record-config-schedule',
      },
      {
        path: '/product-config/record-review/record-audit-schedule',
        component: () => import('@/pages/ProductConfig/RecordReview/components/SchedulePage/index.vue'),
        meta: {
          title: '记录审核进度',
          code: '120020002',
          id: '120020002',
          hidden: false,
          parentPath: '/product-config/record-review',
        },
        name: 'record-audit-schedule',
      },
      {
        path: '/product-config/formula-approval/formula-audit-schedule',
        component: () => import('@/pages/ProductConfig/FormulaApproval/components/SchedulePage/index.vue'),
        meta: {
          title: '生产BOM审核进度',
          code: '120020005',
          id: '120020005',
          hidden: false,
          parentPath: '/product-config/formula-approval',
        },
        name: 'formula-audit-schedule',
      },
      {
        path: '/product-config/formula-configuration/formula-config-schedule',
        component: () => import('@/pages/ProductConfig/FormulaApproval/components/SchedulePage/index.vue'),
        meta: {
          title: '生产BOM审核进度',
          code: '120020004',
          id: '120020004',
          hidden: false,
          parentPath: '/product-config/formula-configuration',
        },
        name: 'formula-config-schedule',
      },
      {
        path: '/product-refer/product-progress/procedure-progress',
        component: () => import('@/pages/ProductionRefer/ProductProgress/procedure.vue'),
        meta: {
          title: '生产进度',
          code: '120050008',
          id: '120050008',
          hidden: false,
          parentPath: '/product-refer/product-progress',
        },
        name: 'product-progress-procedure',
      },
      {
        path: '/product-refer/product-progress/procedure-step-progress',
        component: () => import('@/pages/ProductionRefer/ProductProgress/procedureStep.vue'),
        meta: {
          title: '生产进度',
          code: '120050008',
          id: '120050008',
          hidden: false,
          parentPath: '/product-refer/product-progress',
        },
        name: 'product-progress-procedure-step',
      },
      {
        path: '/product-config/operating-approval/operating-audit-schedule',
        component: () => import('@/pages/ProductConfig/OperatingApproval/components/SchedulePage/index.vue'),
        meta: {
          title: '操作规程审核进度',
          code: '120020007',
          id: '120020007',
          hidden: false,
          parentPath: '/product-config/operating-approval',
        },
        name: 'operating-audit-schedule',
      },
      {
        path: '/product-config/operating-procedures/operating-audit-schedule',
        component: () => import('@/pages/ProductConfig/OperatingApproval/components/SchedulePage/index.vue'),
        meta: {
          title: '操作规程审核进度',
          code: '120020011',
          id: '120020011',
          hidden: false,
          parentPath: '/product-config/operating-procedures',
        },
        name: 'operating-procedures-schedule',
      },
      {
        path: '/product-refer/product-audit-progress/detail',
        component: () => import('@/pages/ProductionRefer/ProductAuditProgress/Detail.vue'),
        meta: {
          title: '生产审核进度详情',
          code: '120050009',
          id: '120050009',
          hidden: false,
          parentPath: '/product-refer/product-audit-progress',
        },
        name: 'product-audit-progress-detail',
      },
      {
        path: '/product-refer/product-progress/revision',
        component: () => import('@/pages/ProductionRefer/ProductProgress/Revision.vue'),
        meta: {
          title: '生产进度修订记录',
          code: '120050008',
          id: '120050008',
          hidden: false,
          parentPath: '/product-refer/product-progress',
        },
        name: 'product-progress-revision',
      },
      {
        path: '/product-refer/production-history/revision',
        component: () => import('@/pages/ProductionRefer/ProductionHistory/Revision.vue'),
        meta: {
          title: '生产历史修订记录',
          code: '120050001',
          id: '120050001',
          hidden: false,
          parentPath: '/product-refer/production-history',
        },
        name: 'production-history-revision',
      },
      {
        path: '/batch-release/management/version-management',
        component: () => import('@/pages/BatchRelease/Management/Detail.vue'),
        meta: {
          title: '版本管理',
          code: '120040003',
          id: '120040003',
          hidden: false,
          parentPath: '/batch-release/management',
        },
        name: 'batch-release-management-version-management',
      },
      {
        path: '/batch-records/management/version-management',
        component: () => import('@/pages/BatchRecords/Management/Detail.vue'),
        meta: {
          title: '版本管理',
          code: '120080002',
          id: '120080002',
          hidden: false,
          parentPath: '/batch-records/management',
        },
        name: 'batch-records-management-version-management',
      },
      {
        path: '/batch-release/review/schedule',
        component: () => import('@/pages/BatchRelease/Review/SchedulePage.vue'),
        meta: {
          title: '批签发审核进度',
          code: '120040005',
          id: '120040005',
          hidden: false,
          parentPath: '/batch-release/review',
        },
        name: 'batch-release-review-schedule',
      },
      {
        path: '/batch-records/review/schedule',
        component: () => import('@/pages/BatchRecords/Review/SchedulePage.vue'),
        meta: {
          title: '批记录审核进度',
          code: '120080003',
          id: '120080003',
          hidden: false,
          parentPath: '/batch-records/review',
        },
        name: 'batch-records-review-schedule',
      },
      {
        path: '/product-config/process-config/largeScreenDisplay',
        component: () => import('@/pages/ProductConfig/ProcessConfig/LargeScreenDisplay.vue'),
        meta: {
          title: '大屏显示',
          code: '120020006',
          id: '120020006',
          hidden: false,
          parentPath: '/product-config/process-config',
        },
        name: 'process-config-largeScreenDisplay',
      },
      {
        path: '/product-config/process-config/order',
        component: () => import('@/pages/ProductConfig/ProcessConfig/Order.vue'),
        meta: {
          title: '工序排序',
          code: '120020006',
          id: '120020006',
          hidden: false,
          parentPath: '/product-config/process-config',
        },
        name: 'process-config-order',
      },
      {
        path: '/data-set/manage/detail',
        component: () => import('@/pages/DataSet/Manage/Detail.vue'),
        meta: {
          title: '数据集管理',
          code: '120070001',
          id: '120070001',
          hidden: true,
          hiddenMenu: true,
          parentPath: '/data-set/manage',
        },
        name: 'data-set-manage-detail',
      },
      {
        path: '/inspectionManage/PleaseCheckConfig/detail',
        component: () => import('@/pages/InspectionManage/PleaseCheckConfig/Detail.vue'),
        meta: {
          title: '请验单配置',
          code: '120100001',
          id: '120100001',
          hidden: false,
          parentPath: '/inspectionManage/PleaseCheckConfig',
        },
        name: 'PleaseCheckConfigDetail',
      },
      {
        path: '/product-config/template-edit/:record_id/:record_type/:implement/:update/:recordId',
        component: () => import('../pages/TemplateEdit/index.vue'),
        meta: { title: '记录编辑', hidden: true, id: '120020001', hiddenMenu: true },
        name: 'TemplateEdit',
      },
      {
        path: '/product-config/formula-config/:record_id/:is_show/:implement/:update/:recordId',
        component: () => import('../pages/FormulaConfig/index.vue'),
        meta: { title: '公式编辑', hidden: true, id: '120020001', hiddenMenu: true },
        name: 'formula-config',
      },
      {
        path: '/product-config/process-config/process-flow',
        component: () => import('@/pages/ProductConfig/ProcessConfig/ProcessFlow/index.vue'),
        meta: { title: '工艺流程', hidden: true, id: '120020006', hiddenMenu: true },
        name: 'process-flow',
      },
      {
        path: '/product-config/process-config/procedure-flow',
        component: () => import('@/pages/ProductConfig/ProcessConfig/ProcedureFlow/index.vue'),
        meta: { title: '工序流程', hidden: true, id: '120020006', hiddenMenu: true },
        name: 'procedure-flow',
      },
      {
        path: '/product-config/process-config/procedure-step-config',
        component: () => import('@/pages/ProductConfig/ProcessConfig/ProcedureStepConfig/index.vue'),
        meta: { title: '批记录配置', hidden: true, id: '120020006', hiddenMenu: true },
        name: 'procedure-step-config',
      },
      // 生产计划-新建计划
      {
        path: '/production-management/product-plan/production-create',
        component: () => import('@/pages/ProductionManagement/ProductionPlan/CreatePlan/index.vue'),
        meta: { title: '新建计划', hiddenMenu: true },
        name: '',
      },
      // 生产计划-批量创建计划
      {
        path: '/production-management/product-plan/production-batch-create',
        component: () => import('@/pages/ProductionManagement/ProductionPlan/BatchCreate/index.vue'),
        meta: { title: '批量创建计划', hiddenMenu: true },
        name: '',
      },
      // 流程配置-新建流程
      {
        path: '/product-config/audit-config/add-flow',
        component: () => import('@/pages/ProductConfig/AuditConfig/AddFlow/index.vue'),
        meta: { title: '新建流程', id: '120020008', hiddenMenu: true },
        name: 'audit-config-add-flow',
      },
      // 生产BOM配置-新建生产BOM
      {
        path: '/product-config/formula-configuration/add-formula',
        component: () => import('@/pages/ProductConfig/FormulaConfiguration/AddFormula/index.vue'),
        meta: { title: '新建生产BOM', id: '120020004', hidden: true, hiddenMenu: true },
        name: 'formula-config-add-formula',
      },
      {
        path: '/product-config/formula-configuration/add-formula',
        component: () => import('@/pages/ProductConfig/FormulaConfiguration/AddFormula/index.vue'),
        meta: { title: '生产BOM审核', id: '120020005', hidden: true, hiddenMenu: true },
        name: 'formula-config-formula-approval',
      },
      {
        path: '/product-management/weighing-requirements/detail',
        component: () => import('@/pages/ProductionManagement/WeighingRequirements/Detail.vue'),
        meta: { title: '新增称量需求', id: '120030013', hidden: true },
        name: 'weighing-requirements-detail',
      },
      {
        path: '/product-management/weighing-requirements/record-detail',
        component: () => import('@/pages/ProductionManagement/WeighingRequirements/WeighingDetail/index.vue'),
        meta: { title: '称量详情', id: '120030013', hidden: true },
        name: 'weighing-requirements-record-detail',
      },
      {
        path: '/product-management/weighing-work-order-plan/manual-plan',
        component: () => import('@/pages/ProductionManagement/WeighingWorkOrderPlan/components/ManualPlan/index.vue'),
        meta: { title: '手动工单规划', id: '120030014', hidden: true },
        name: 'weighing-work-order-manual-plan',
      },
      {
        path: '/product-management/weighing-work-order-plan/edit-plan',
        component: () => import('@/pages/ProductionManagement/WeighingWorkOrderPlan/components/EditPlan/index.vue'),
        meta: { title: '编辑工单', hidden: true },
        name: 'weighing-work-order-edit-plan',
      },
      {
        path: '/product-management/weighing-work-order-plan/detail',
        component: () =>
          import('@/pages/ProductionManagement/WeighingWorkOrderPlan/components/WeighingDetail/index.vue'),
        meta: { title: '工单称量详情', hidden: true },
        name: 'weighing-work-order-detail',
      },
    ],
  },
];
