i18n:
  locations:
    - data-id: bims_exception_zh_CN.properties
      group: backend-i18n
    - data-id: bims_exception_en_US.properties
      group: backend-i18n
    - data-id: bims_enum_zh_CN.properties
      group: backend-i18n
    - data-id: bims_enum_en_US.properties
      group: backend-i18n 
    - data-id: bims_excel_zh_CN.properties
      group: backend-i18n
    - data-id: bims_excel_en_US.properties
      group: backend-i18n
    - data-id: bims_message_zh_CN.properties
      group: backend-i18n
    - data-id: bims_message_en_US.properties
      group: backend-i18n