package com.bmos.mes.service.plan.document.service.dto;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

/**
 * 归档自动生成批记录DTO
 */
@Getter
@Setter
@ApiModel("归档自动生成批记录DTO")
public class ArchiveAutoGenerateDTO {

    /**
     * 生产计划id
     */
    @ApiModelProperty("生产计划id")
    private Long planId;


}
