package com.bmos.mes.service.plan.document.service.dto;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import java.util.List;

/**
 * 批记录生成
 */
@Getter
@Setter
@ApiModel("批记录生成DTO")
public class ArchiveGenerateDTO extends ArchiveAutoGenerateDTO {

    /**
     * 模板版本id
     */
    @ApiModelProperty("模板版本id")
    private Long templateVersionId;

    /**
     * 排序生产计划id集合
     */
    @ApiModelProperty("排序生产计划id集合")
    private List<Long> sortPlanIdList;

}
