package com.bmos.mes.service.plan.document.mq;

import com.baomidou.mybatisplus.core.conditions.update.LambdaUpdateWrapper;
import com.baomidou.mybatisplus.core.conditions.update.UpdateWrapper;
import com.bmos.mes.common.enums.plan.PlanArchiveStatusEnum;
import com.bmos.mes.common.enums.plan.ProductPlanStartEnum;
import com.bmos.mes.mq.annotation.Consumer;
import com.bmos.mes.service.plan.document.service.BatchRecordArchiveService;
import com.bmos.mes.service.plan.document.service.IPlanArchiveService;
import com.bmos.mes.service.plan.document.service.dto.ArchiveAutoGenerateDTO;
import com.bmos.mes.service.plan.info.model.Plan;
import com.bmos.mes.service.plan.info.mq.message.PlanStatusChangeMessage;
import com.bmos.mes.service.plan.info.mq.topic.PlanStatusChangeTopic;
import com.bmos.mes.service.plan.info.service.PlanService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import javax.annotation.Resource;

/**
 * @author yigaohui
 * @date 2024/7/3
 **/
@Service
@Slf4j
@Consumer(groupId = "plan-archive-group-consumer")
public class PlanArchiveConsumer implements PlanStatusChangeTopic {

    @Resource
    private IPlanArchiveService planArchiveService;

    @Resource
    private PlanService planService;

    @Resource
    private BatchRecordArchiveService batchRecordArchiveService;

    @Override
    public void consume(PlanStatusChangeMessage message) {
        log.info("接收到计划状态改变的消息:{}", message);
        if (message.getCurrentPlanStatus() == ProductPlanStartEnum.END
                || message.getCurrentPlanStatus() == ProductPlanStartEnum.TERMINATION) {
            try {
                LambdaUpdateWrapper<Plan> lambda = new UpdateWrapper<Plan>().lambda();
                lambda.eq(Plan::getId, message.getPlan().getId())
                        .set(Plan::getArchiveStatus, PlanArchiveStatusEnum.ARCHIVE_ING);
                planService.update(lambda);
                planArchiveService.archive(message.getPlan().getId());
                LambdaUpdateWrapper<Plan> ul = new UpdateWrapper<Plan>().lambda();
                ul.eq(Plan::getId, message.getPlan().getId())
                        .set(Plan::getArchiveStatus, PlanArchiveStatusEnum.ARCHIVE_SUCCESS);
                planService.update(ul);
            } catch (Exception e) {
                LambdaUpdateWrapper<Plan> ul = new UpdateWrapper<Plan>().lambda();
                ul.eq(Plan::getId, message.getPlan().getId())
                        .set(Plan::getArchiveStatus, PlanArchiveStatusEnum.ARCHIVE_FAIL);
                planService.update(ul);
                log.error("归档计划失败", e);
            }
            // 数据集版本自动归档
            this.datasetArchive(message.getPlan().getId());
        }

    }

    private void datasetArchive(Long planId){
        try{
            ArchiveAutoGenerateDTO archiveAutoGenerateDTO = new ArchiveAutoGenerateDTO();
            archiveAutoGenerateDTO.setPlanId(planId);
            batchRecordArchiveService.autoGenerateArchive(archiveAutoGenerateDTO);
        } catch (Exception e){
            log.error("数据集版本自动归档失败 planId={}", planId, e);
        }

    }
}
