import type { NodeType } from '../types';

export enum HAS_FORM_BUSINESS_NODE {
  BUSINESS_FORMULA_INFO_MATERIAL = 'BUSINESS_FORMULA_INFO_MATERIAL',
  // 按批次领料
  BATCH_QUANTITY_PICK = 'BATCH_QUANTITY_PICK',
  // 按批次领料 汇总
  BATCH_QUANTITY_PICK_SUMMARY = 'BATCH_QUANTITY_PICK_SUMMARY',
  // 按物料量领料
  MATERIAL_QUANTITY_PICK = 'MATERIAL_QUANTITY_PICK',
  // 按物料量领料 分组
  MATERIAL_QUANTITY_PICK_MATERIAL = 'MATERIAL_QUANTITY_PICK_MATERIAL',
  // 领料接收 汇总
  PICKING_RECEIVING_SUMMARY = 'PICKING_RECEIVING_SUMMARY',
  // 配料计划
  INGREDIENTS_PLAN = 'INGREDIENTS_PLAN',
  // 配料计划 汇总
  INGREDIENTS_PLAN_MATERIAL = 'INGREDIENTS_PLAN_MATERIAL',
  // 配料称量
  WEIGHING_INGREDIENTS = 'WEIGHING_INGREDIENTS',
  // 配料称量 汇总
  WEIGHING_INGREDIENTS_SUMMARY = 'WEIGHING_INGREDIENTS_SUMMARY',
  // 配料投入
  INGREDIENTS_INPUT = 'INGREDIENTS_INPUT',
  // 配料投入 汇总
  INGREDIENTS_INPUT_SUMMARY = 'INGREDIENTS_INPUT_SUMMARY',
  // 设备信息
  EQUIPMENT_INFO = 'EQUIPMENT_INFO',
  // 设备信息 基础信息
  EQUIPMENT_INFO_BASIC = 'EQUIPMENT_INFO_BASIC',
  // 设备数采
  EQUIPMENT_DATA_ACQUISITION = 'EQUIPMENT_DATA_ACQUISITION',
  // 设备数采 数采点
  EQUIPMENT_DATA_ACQUISITION_POINT = 'EQUIPMENT_DATA_ACQUISITION_POINT',
  // 设备数采 时间
  EQUIPMENT_DATA_ACQUISITION_TIME = 'EQUIPMENT_DATA_ACQUISITION_TIME',
  // 生产投料
  FEED_RECYCLE = 'FEED_RECYCLE',
  // 生产投料 汇总
  FEED_RECYCLE_SUMMARY = 'FEED_RECYCLE_SUMMARY',
  // 产出称量
  OUTPUT_WEIGHING = 'OUTPUT_WEIGHING',
  // 产出称量 汇总
  OUTPUT_WEIGHING_SUMMARY = 'OUTPUT_WEIGHING_SUMMARY',
  // 成品产出
  PRODUCT_OUTPUT = 'PRODUCT_OUTPUT',
  // 清场执行
  CLEAN_IMPLEMENT = 'CLEAN_IMPLEMENT',
  // 清场检查
  CLEAN_CHECK = 'CLEAN_CHECK',
  // 清场信息
  CLEAN_INFO = 'CLEAN_INFO',
  // 物料预定
  MATERIAL_RESERVE = 'MATERIAL_RESERVE',
  // 物料预定 汇总
  MATERIAL_RESERVE_SUMMARY = 'MATERIAL_RESERVE_SUMMARY',
  // 物料预定 批次
  MATERIAL_RESERVE_BATCH = 'MATERIAL_RESERVE_BATCH',
  // 物料投入
  MATERIAL_INPUT = 'MATERIAL_INPUT',
  // 物料投入 汇总
  MATERIAL_INPUT_SUMMARY = 'MATERIAL_INPUT_SUMMARY',
  // 领料接受
  PICKING_RECEIVING = 'PICKING_RECEIVING',
  // 配液计划
  LIQUID_PREPARATION_PLAN = 'LIQUID_PREPARATION_PLAN',
  // 配液计划 汇总
  LIQUID_PREPARATION_PLAN_SUMMARY = 'LIQUID_PREPARATION_PLAN_SUMMARY',
  // 配液量取
  LIQUID_PREPARATION_MEASURE = 'LIQUID_PREPARATION_MEASURE',
  // 配液量取 汇总
  LIQUID_PREPARATION_MEASURE_SUMMARY = 'LIQUID_PREPARATION_MEASURE_SUMMARY',
  // 配液投入
  LIQUID_PREPARATION_INPUT = 'LIQUID_PREPARATION_INPUT',
  // 配液投入 汇总
  LIQUID_PREPARATION_INPUT_SUMMARY = 'LIQUID_PREPARATION_INPUT_SUMMARY',
  // 配液产出
  LIQUID_PREPARATION_OUTPUT = 'LIQUID_PREPARATION_OUTPUT',
  // 配液产出 汇总
  LIQUID_PREPARATION_OUTPUT_SUMMARY = 'LIQUID_PREPARATION_OUTPUT_SUMMARY',
  // 称量数据
  WEIGHING_DATA = 'WEIGHING_DATA',
  // 物料件信息
  MATERIAL_INFO = 'MATERIAL_INFO',
  // 设备数采绘图
  EQUIPMENT_DATA_DRAW_LIST = 'EQUIPMENT_DATA_DRAW_LIST',
  // 检验结果组件
  INSPECTION_RESULTS = 'INSPECTION_RESULTS',
}

export type HasFormBusinessNodeType = keyof typeof HAS_FORM_BUSINESS_NODE;

export type AllNodeType = NodeType | HasFormBusinessNodeType;
