truncate table bmos_platform.bp_business_parameter;

# 集中化lims用到的系统参数
INSERT INTO bmos_platform.bp_business_parameter (id, code, value, value_type, business_type, belong, description, sort, value_range, is_display, create_by, update_by, create_time, update_time, is_deleted) VALUES (1, 'application', null, null, null, null, null, null, '[{"label": "生产","value": "生产","URL": ""}, { "label": "平台","value": "平台","URL": "" }]', 0, '1', '1', '2024-03-08 18:17:52', '2024-03-08 18:17:52', 0);
INSERT INTO bmos_platform.bp_business_parameter (id, code, value, value_type, business_type, belong, description, sort, value_range, is_display, create_by, update_by, create_time, update_time, is_deleted) VALUES (100005, 'platform.sys.web-lock-screen-time', '15', 'NUMBER', 'BUSINESS', '平台', '网页端锁屏时间，单位：分钟', 100040, '', 1, '1', '1', '2024-03-08 18:17:52', '2024-03-08 18:17:52', 0);
INSERT INTO bmos_platform.bp_business_parameter (id, code, value, value_type, business_type, belong, description, sort, value_range, is_display, create_by, update_by, create_time, update_time, is_deleted) VALUES (100006, 'platform.sys.web-lock-screen-hotkey', '["Ctrl","L"]', 'JSON', 'BUSINESS', '平台', '网页端锁屏快捷键', 100050, '', 1, '1', '1', '2024-03-08 18:17:52', '2024-03-08 18:17:52', 0);
INSERT INTO bmos_platform.bp_business_parameter (id, code, value, value_type, business_type, belong, description, sort, value_range, is_display, create_by, update_by, create_time, update_time, is_deleted) VALUES (100007, 'platform.sys.client-name', '佰墨思', 'STRING', 'BUSINESS', '平台', '部门管理根节点名称', 100010, '', 1, '1', '1', '2024-03-08 18:17:52', '2024-03-08 18:17:52', 0);
INSERT INTO bmos_platform.bp_business_parameter (id, code, value, value_type, business_type, belong, description, sort, value_range, is_display, create_by, update_by, create_time, update_time, is_deleted) VALUES (100008, 'platform.sys.language', '{"中文":"zh_CN","英文":"en_US","俄文":"ru_RU"}', 'JSON', 'BUSINESS', '平台', '系统语言', 100080, '', 1, '1', '1', '2024-03-08 18:17:52', '2024-03-08 18:17:52', 0);
INSERT INTO bmos_platform.bp_business_parameter (id, code, value, value_type, business_type, belong, description, sort, value_range, is_display, create_by, update_by, create_time, update_time, is_deleted) VALUES (100011, 'platform.user.pwd-rule.character', '{
  "lowerCase": true,
  "upperCase": true,
  "digit": true,
  "specialCharacters": []
}', 'STRING', 'BUSINESS', '平台', '密码复杂度校验配置：lowerCase：是否必须有小写字母；upperCase：是否必须有大写字母；digit：是否必须有数字；specialCharacters：是否必须有specialCharacters配置的字符', 100110, '', 1, null, null, null, null, 0);
INSERT INTO bmos_platform.bp_business_parameter (id, code, value, value_type, business_type, belong, description, sort, value_range, is_display, create_by, update_by, create_time, update_time, is_deleted) VALUES (100012, 'platform.user.pwd-rule.minLen', '6', 'STRING', 'BUSINESS', '平台', '用户密码最小密码长度，限制6-24内整数', 100120, '', 1, null, null, null, null, 0);
INSERT INTO bmos_platform.bp_business_parameter (id, code, value, value_type, business_type, belong, description, sort, value_range, is_display, create_by, update_by, create_time, update_time, is_deleted) VALUES (100013, 'platform.user.pwd-rule.tryNum', '5', 'STRING', 'BUSINESS', '平台', '用户密码尝试次数，限制0-24内整数', 100130, '', 1, null, null, null, null, 0);
INSERT INTO bmos_platform.bp_business_parameter (id, code, value, value_type, business_type, belong, description, sort, value_range, is_display, create_by, update_by, create_time, update_time, is_deleted) VALUES (100014, 'platform.user.pwd-rule.hisNum', '0', 'STRING', 'BUSINESS', '平台', '用户历史密码个数，限制0-6内整数', 100140, '', 1, null, null, null, null, 0);
INSERT INTO bmos_platform.bp_business_parameter (id, code, value, value_type, business_type, belong, description, sort, value_range, is_display, create_by, update_by, create_time, update_time, is_deleted) VALUES (100015, 'platform.user.pwd-rule.validity', '365', 'STRING', 'BUSINESS', '平台', '用户密码有效期，单位为：天', 100150, '', 1, null, null, null, null, 0);
INSERT INTO bmos_platform.bp_business_parameter (id, code, value, value_type, business_type, belong, description, sort, value_range, is_display, create_by, update_by, create_time, update_time, is_deleted) VALUES (100018, 'platform.sys.web-msg-polling-time', '30', 'NUMBER', 'BUSINESS', '平台', '网页端消息轮询时间，单位：秒', 100170, '', 1, '1', '1', '2024-04-09 10:48:26', '2024-04-09 10:48:26', 0);
INSERT INTO bmos_platform.bp_business_parameter (id, code, value, value_type, business_type, belong, description, sort, value_range, is_display, create_by, update_by, create_time, update_time, is_deleted) VALUES (100019, 'platform.sys.project-config', '[{"label":"佰墨思","key":"bmos"},{"label":"白俄","key":"be"},{"label":"康盛科泰","key":"kskt"},{"label":"华兰生物","key":"hlsw"}]', 'JSON', 'BUSINESS', '平台', '系统项目配置', 100190, '', 1, '1', '1', '2024-04-09 10:48:26', '2024-04-09 10:48:26', 0);
INSERT INTO bmos_platform.bp_business_parameter (id, code, value, value_type, business_type, belong, description, sort, value_range, is_display, create_by, update_by, create_time, update_time, is_deleted) VALUES (100020, 'platform.sys.license.isRequired', 'true', 'STRING', 'BUSINESS', '平台', '系统是否需要授权', 100200, '', 1, '1', '1', '2024-06-12 16:09:06', '2024-06-12 16:09:06', 0);
INSERT INTO bmos_platform.bp_business_parameter (id, code, value, value_type, business_type, belong, description, sort, value_range, is_display, create_by, update_by, create_time, update_time, is_deleted) VALUES (100022, 'platform.sys.version', 'V2.1.1', 'STRING', 'BUSINESS', '平台', '系统版本号', 100220, '', 1, '1', '1', '2024-10-16 17:27:57', '2024-10-16 17:27:57', 0);

# 系统服务激活监测配置
INSERT INTO bmos_platform.bp_business_parameter (id, code, name, value, value_type, business_type, belong, description, sort, value_range, is_display, create_by, update_by, create_time, update_time, is_deleted) VALUES (100026, 'platform.sys.actived.service', '系统服务激活监测配置', '["PMP","MES","LIMS","WMS"]', 'STRING', 'BUSINESS', '平台', '配置系统信息菜单中监测的服务，示例：["PMP","MES","LIMS","WMS"]', 100260, '', 1, '1', '1', '2024-11-27 11:37:32', '2024-11-27 11:37:32', 0);

