# 配液量取和配液产出标签实例
INSERT INTO bmos_platform.bp_tag_instance (id, tag_name, tag_type_id, tag_scene_id, tag_define_id, config_fields, is_enable, create_time, update_time, create_by, update_by, is_deleted) VALUES (121001006, '原辅包配液量取打印标签', 1, 121001006, 1, '[{"label":"物料信息：","defineField":"field1","dataSourceField":"fullName","consumeValue":null},{"label":"物料批号：","defineField":"field2","dataSourceField":"materialBatchNo","consumeValue":null},{"label":"物料件号：","defineField":"field3","dataSourceField":"materialNo","consumeValue":null},{"label":"物料量：","defineField":"field4","dataSourceField":"quantityWithUnit","consumeValue":null},{"label":"操作人员：","defineField":"field5","dataSourceField":"measurerName","consumeValue":null},{"label":"操作时间：","defineField":"field6","dataSourceField":"measureTime","consumeValue":null},{"label":"产品名称：","defineField":"field7","dataSourceField":"productName","consumeValue":null},{"label":"产品规格：","defineField":"field8","dataSourceField":"productSpecification","consumeValue":null},{"label":"生产批号：","defineField":"field9","dataSourceField":"batchNo","consumeValue":null}]', 'TRUE', now(), now(), null, null, 0);
INSERT INTO bmos_platform.bp_tag_instance (id, tag_name, tag_type_id, tag_scene_id, tag_define_id, config_fields, is_enable, create_time, update_time, create_by, update_by, is_deleted) VALUES (121001007, '原辅包配液量取补打标签', 1, 121001007, 1, '[{"label":"物料信息：","defineField":"field1","dataSourceField":"fullName","consumeValue":null},{"label":"物料批号：","defineField":"field2","dataSourceField":"materialBatchNo","consumeValue":null},{"label":"物料件号：","defineField":"field3","dataSourceField":"materialNo","consumeValue":null},{"label":"物料量：","defineField":"field4","dataSourceField":"quantityWithUnit","consumeValue":null},{"label":"操作人员：","defineField":"field5","dataSourceField":"measurerName","consumeValue":null},{"label":"操作时间：","defineField":"field6","dataSourceField":"measureTime","consumeValue":null},{"label":"产品名称：","defineField":"field7","dataSourceField":"productName","consumeValue":null},{"label":"产品规格：","defineField":"field8","dataSourceField":"productSpecification","consumeValue":null},{"label":"生产批号：","defineField":"field9","dataSourceField":"batchNo","consumeValue":null}]', 'TRUE', now(), now(), null, null, 0);
INSERT INTO bmos_platform.bp_tag_instance (id, tag_name, tag_type_id, tag_scene_id, tag_define_id, config_fields, is_enable, create_time, update_time, create_by, update_by, is_deleted) VALUES (121002008, '中间品配液量取打印标签', 2, 121002008, 1, '[{"label":"物料信息：","defineField":"field1","dataSourceField":"fullName","consumeValue":null},{"label":"物料批号：","defineField":"field2","dataSourceField":"materialBatchNo","consumeValue":null},{"label":"物料件号：","defineField":"field3","dataSourceField":"materialNo","consumeValue":null},{"label":"物料量：","defineField":"field4","dataSourceField":"quantityWithUnit","consumeValue":null},{"label":"操作人员：","defineField":"field5","dataSourceField":"measurerName","consumeValue":null},{"label":"操作时间：","defineField":"field6","dataSourceField":"measureTime","consumeValue":null},{"label":"产品名称：","defineField":"field7","dataSourceField":"productName","consumeValue":null},{"label":"产品规格：","defineField":"field8","dataSourceField":"productSpecification","consumeValue":null},{"label":"生产批号：","defineField":"field9","dataSourceField":"batchNo","consumeValue":null}]', 'TRUE', now(), now(), null, null, 0);
INSERT INTO bmos_platform.bp_tag_instance (id, tag_name, tag_type_id, tag_scene_id, tag_define_id, config_fields, is_enable, create_time, update_time, create_by, update_by, is_deleted) VALUES (121002009, '中间品配液量取补打标签', 2, 121002009, 1, '[{"label":"物料信息：","defineField":"field1","dataSourceField":"fullName","consumeValue":null},{"label":"物料批号：","defineField":"field2","dataSourceField":"materialBatchNo","consumeValue":null},{"label":"物料件号：","defineField":"field3","dataSourceField":"materialNo","consumeValue":null},{"label":"物料量：","defineField":"field4","dataSourceField":"quantityWithUnit","consumeValue":null},{"label":"操作人员：","defineField":"field5","dataSourceField":"measurerName","consumeValue":null},{"label":"操作时间：","defineField":"field6","dataSourceField":"measureTime","consumeValue":null},{"label":"产品名称：","defineField":"field7","dataSourceField":"productName","consumeValue":null},{"label":"产品规格：","defineField":"field8","dataSourceField":"productSpecification","consumeValue":null},{"label":"生产批号：","defineField":"field9","dataSourceField":"batchNo","consumeValue":null}]', 'TRUE', now(), now(), null, null, 0);
INSERT INTO bmos_platform.bp_tag_instance (id, tag_name, tag_type_id, tag_scene_id, tag_define_id, config_fields, is_enable, create_time, update_time, create_by, update_by, is_deleted) VALUES (121002010, '中间品配液产出打印标签', 2, 121002010, 1, '[{"label":"物料信息：","defineField":"field1","dataSourceField":"fullName","consumeValue":null},{"label":"物料批号：","defineField":"field2","dataSourceField":"materialBatchNo","consumeValue":null},{"label":"物料件号：","defineField":"field3","dataSourceField":"materialNo","consumeValue":null},{"label":"物料量：","defineField":"field4","dataSourceField":"quantityWithUnit","consumeValue":null},{"label":"操作人员：","defineField":"field5","dataSourceField":"measurerName","consumeValue":null},{"label":"操作时间：","defineField":"field6","dataSourceField":"measureTime","consumeValue":null},{"label":"产品名称：","defineField":"field7","dataSourceField":"productName","consumeValue":null},{"label":"产品规格：","defineField":"field8","dataSourceField":"productSpecification","consumeValue":null},{"label":"生产批号：","defineField":"field9","dataSourceField":"batchNo","consumeValue":null}]', 'TRUE', now(), now(), null, null, 0);
INSERT INTO bmos_platform.bp_tag_instance (id, tag_name, tag_type_id, tag_scene_id, tag_define_id, config_fields, is_enable, create_time, update_time, create_by, update_by, is_deleted) VALUES (121002011, '中间品配液产出补打标签', 2, 121002011, 1, '[{"label":"物料信息：","defineField":"field1","dataSourceField":"fullName","consumeValue":null},{"label":"物料批号：","defineField":"field2","dataSourceField":"materialBatchNo","consumeValue":null},{"label":"物料件号：","defineField":"field3","dataSourceField":"materialNo","consumeValue":null},{"label":"物料量：","defineField":"field4","dataSourceField":"quantityWithUnit","consumeValue":null},{"label":"操作人员：","defineField":"field5","dataSourceField":"measurerName","consumeValue":null},{"label":"操作时间：","defineField":"field6","dataSourceField":"measureTime","consumeValue":null},{"label":"产品名称：","defineField":"field7","dataSourceField":"productName","consumeValue":null},{"label":"产品规格：","defineField":"field8","dataSourceField":"productSpecification","consumeValue":null},{"label":"生产批号：","defineField":"field9","dataSourceField":"batchNo","consumeValue":null}]', 'TRUE', now(), now(), null, null, 0);

# 称量中心物料称量标签实例
INSERT INTO bmos_platform.bp_tag_instance (id, tag_name, tag_type_id, tag_scene_id, tag_define_id, config_fields, is_enable, create_time, update_time, create_by, update_by, is_deleted) VALUES (121001008, '原辅包物料称量打印标签', 1, 121001008, 1, '[{"label":"物料信息：","defineField":"field1","dataSourceField":"fullName","consumeValue":null},{"label":"物料批号：","defineField":"field2","dataSourceField":"materialBatchNo","consumeValue":null},{"label":"物料件号：","defineField":"field3","dataSourceField":"materialNo","consumeValue":null},{"label":"称量重量：","defineField":"field4","dataSourceField":"netWeightWithUnit","consumeValue":null},{"label":"称量人员：","defineField":"field5","dataSourceField":"weigherName","consumeValue":null},{"label":"称量时间：","defineField":"field6","dataSourceField":"weighTime","consumeValue":null},{"label":"产品名称：","defineField":"field7","dataSourceField":"productName","consumeValue":null},{"label":"产品规格：","defineField":"field8","dataSourceField":"productSpecification","consumeValue":null},{"label":"生产批号：","defineField":"field9","dataSourceField":"batchNo","consumeValue":null}]', 'TRUE', now(), now(), null, null, 0);
INSERT INTO bmos_platform.bp_tag_instance (id, tag_name, tag_type_id, tag_scene_id, tag_define_id, config_fields, is_enable, create_time, update_time, create_by, update_by, is_deleted) VALUES (121001009, '原辅包物料称量补打标签', 1, 121001009, 1, '[{"label":"物料信息：","defineField":"field1","dataSourceField":"fullName","consumeValue":null},{"label":"物料批号：","defineField":"field2","dataSourceField":"materialBatchNo","consumeValue":null},{"label":"物料件号：","defineField":"field3","dataSourceField":"materialNo","consumeValue":null},{"label":"称量重量：","defineField":"field4","dataSourceField":"netWeightWithUnit","consumeValue":null},{"label":"称量人员：","defineField":"field5","dataSourceField":"weigherName","consumeValue":null},{"label":"称量时间：","defineField":"field6","dataSourceField":"weighTime","consumeValue":null},{"label":"产品名称：","defineField":"field7","dataSourceField":"productName","consumeValue":null},{"label":"产品规格：","defineField":"field8","dataSourceField":"productSpecification","consumeValue":null},{"label":"生产批号：","defineField":"field9","dataSourceField":"batchNo","consumeValue":null}]', 'TRUE', now(), now(), null, null, 0);
INSERT INTO bmos_platform.bp_tag_instance (id, tag_name, tag_type_id, tag_scene_id, tag_define_id, config_fields, is_enable, create_time, update_time, create_by, update_by, is_deleted) VALUES (121002012, '中间品物料称量打印标签', 2, 121002012, 1, '[{"label":"物料信息：","defineField":"field1","dataSourceField":"fullName","consumeValue":null},{"label":"物料批号：","defineField":"field2","dataSourceField":"materialBatchNo","consumeValue":null},{"label":"物料件号：","defineField":"field3","dataSourceField":"materialNo","consumeValue":null},{"label":"称量重量：","defineField":"field4","dataSourceField":"netWeightWithUnit","consumeValue":null},{"label":"称量人员：","defineField":"field5","dataSourceField":"weigherName","consumeValue":null},{"label":"称量时间：","defineField":"field6","dataSourceField":"weighTime","consumeValue":null},{"label":"产品名称：","defineField":"field7","dataSourceField":"productName","consumeValue":null},{"label":"产品规格：","defineField":"field8","dataSourceField":"productSpecification","consumeValue":null},{"label":"生产批号：","defineField":"field9","dataSourceField":"batchNo","consumeValue":null}]', 'TRUE', now(), now(), null, null, 0);
INSERT INTO bmos_platform.bp_tag_instance (id, tag_name, tag_type_id, tag_scene_id, tag_define_id, config_fields, is_enable, create_time, update_time, create_by, update_by, is_deleted) VALUES (121002013, '中间品物料称量补打标签', 2, 121002013, 1, '[{"label":"物料信息：","defineField":"field1","dataSourceField":"fullName","consumeValue":null},{"label":"物料批号：","defineField":"field2","dataSourceField":"materialBatchNo","consumeValue":null},{"label":"物料件号：","defineField":"field3","dataSourceField":"materialNo","consumeValue":null},{"label":"称量重量：","defineField":"field4","dataSourceField":"netWeightWithUnit","consumeValue":null},{"label":"称量人员：","defineField":"field5","dataSourceField":"weigherName","consumeValue":null},{"label":"称量时间：","defineField":"field6","dataSourceField":"weighTime","consumeValue":null},{"label":"产品名称：","defineField":"field7","dataSourceField":"productName","consumeValue":null},{"label":"产品规格：","defineField":"field8","dataSourceField":"productSpecification","consumeValue":null},{"label":"生产批号：","defineField":"field9","dataSourceField":"batchNo","consumeValue":null}]', 'TRUE', now(), now(), null, null, 0);

# 调整设备标签字段 by lilong 241125
UPDATE bmos_platform.bp_tag_instance SET config_fields = '[{"label":"设备名称：","defineField":"field1","dataSourceField":"equipmentName","consumeValue":null},{"label":"设备编号：","defineField":"field2","dataSourceField":"equipmentCode","consumeValue":null},{"label":"打印时间：","defineField":"field3","dataSourceField":"printDate","consumeValue":null},{"label":null,"defineField":"field4","dataSourceField":null,"consumeValue":null},{"label":null,"defineField":"field5","dataSourceField":null,"consumeValue":null},{"label":null,"defineField":"field6","dataSourceField":null,"consumeValue":null},{"label":null,"defineField":"field7","dataSourceField":null,"consumeValue":null},{"label":null,"defineField":"field8","dataSourceField":null,"consumeValue":null},{"label":null,"defineField":"field9","dataSourceField":null,"consumeValue":null}]' WHERE id = 160004001;
DELETE FROM bmos_platform.bp_tag_scene_field WHERE id IN (
'160004001003',
'160004001004',
'160004001005',
'160004001006'
);

# 屏蔽称量中心和配液功能的标签打印 by lilong 241211
DELETE FROM bmos_platform.bp_tag_instance WHERE bmos_platform.bp_tag_instance.id IN (
'121001008',
'121001009',
'121002012',
'121002013',
'121001006',
'121001007',
'121002008',
'121002009',
'121002010',
'121002011'
    );

