# 调整配液产出的标签信息 by lilong 250312
UPDATE bmos_platform.bp_tag_scene SET data_source_interface = '/api/app/mes/tag/print/PREPARATION_PRODUCE_STORAGE_MATERIAL' WHERE id = 121002010;
UPDATE bmos_platform.bp_tag_scene SET data_source_interface = '/api/app/mes/tag/print/PREPARATION_PRODUCE_STORAGE_MATERIAL' WHERE id = 121002011;
UPDATE bmos_platform.bp_tag_scene_field SET field = 'producerName', label = '产出人员' WHERE id = 121002010008;
UPDATE bmos_platform.bp_tag_scene_field SET field = 'produceTime', label = '操作时间' WHERE id = 121002010010;
UPDATE bmos_platform.bp_tag_scene_field SET field = 'producerName', label = '产出人员' WHERE id = 121002011008;
UPDATE bmos_platform.bp_tag_scene_field SET field = 'produceTime', label = '操作时间' WHERE id = 121002011010;
UPDATE bmos_platform.bp_tag_instance SET config_fields = '[{"label":"物料信息：","defineField":"field1","dataSourceField":"fullName","consumeValue":null},{"label":"物料批号：","defineField":"field2","dataSourceField":"materialBatchNo","consumeValue":null},{"label":"物料件号：","defineField":"field3","dataSourceField":"materialNo","consumeValue":null},{"label":"物料量：","defineField":"field4","dataSourceField":"quantityWithUnit","consumeValue":null},{"label":"产出人员：","defineField":"field5","dataSourceField":"producerName","consumeValue":null},{"label":"操作时间：","defineField":"field6","dataSourceField":"produceTime","consumeValue":null},{"label":"产品名称：","defineField":"field7","dataSourceField":"productName","consumeValue":null},{"label":"产品规格：","defineField":"field8","dataSourceField":"productSpecification","consumeValue":null},{"label":"生产批号：","defineField":"field9","dataSourceField":"batchNo","consumeValue":null}]' WHERE id = 121002010;
UPDATE bmos_platform.bp_tag_instance SET config_fields = '[{"label":"物料信息：","defineField":"field1","dataSourceField":"fullName","consumeValue":null},{"label":"物料批号：","defineField":"field2","dataSourceField":"materialBatchNo","consumeValue":null},{"label":"物料件号：","defineField":"field3","dataSourceField":"materialNo","consumeValue":null},{"label":"物料量：","defineField":"field4","dataSourceField":"quantityWithUnit","consumeValue":null},{"label":"产出人员：","defineField":"field5","dataSourceField":"producerName","consumeValue":null},{"label":"操作时间：","defineField":"field6","dataSourceField":"produceTime","consumeValue":null},{"label":"产品名称：","defineField":"field7","dataSourceField":"productName","consumeValue":null},{"label":"产品规格：","defineField":"field8","dataSourceField":"productSpecification","consumeValue":null},{"label":"生产批号：","defineField":"field9","dataSourceField":"batchNo","consumeValue":null}]' WHERE id = 121002011;
