package com.bmos.mes.service.plan.document.service;

import com.bmos.mes.service.plan.document.controller.vo.ArchiveAuditPageVO;
import com.bmos.mes.service.plan.document.controller.vo.BatchRecordArchiveVO;
import com.bmos.mes.service.plan.document.controller.vo.BatchRecordVersionVO;
import com.bmos.mes.service.plan.document.controller.vo.RecordArchiveTemplateVersionVO;
import com.bmos.mes.service.plan.document.model.BatchRecordArchive;
import com.bmos.mes.service.plan.document.service.dto.*;
import com.bmos.mes.service.product.vo.ProductCategoryTreeNodeVO;
import com.bmos.mybatis.page.CommonPage;

import javax.servlet.http.HttpServletResponse;
import java.util.List;

/**
 * 批记录档案服务
 */
public interface BatchRecordArchiveService {

    /**
     * 生成的批记录后进行回调
     *
     * @param dto
     */
    void generateCallBack(GenerateBatchRecordDTO dto);

    /**
     * 获取批记录页面产品树
     * @param categoryType
     * @param templateId
     * @return
     */
    List<ProductCategoryTreeNodeVO> getBatchArchiveProductTreeByTemplateId(Integer categoryType, Long templateId);

    /**
     * 分页查询生产批号的工艺绑定了哪些模板版本
     * @param dto
     * @return
     */
    CommonPage<RecordArchiveTemplateVersionVO> archivePage(RecordArchiveTemplateVersionDTO dto);

    /**
     * 版本管理
     *
     * @param dto
     * @return
     */
    BatchRecordVersionVO planInfo(RecordPlanInfoDTO dto);

    /**
     * [版本管理]生产信息下生成的批记录
     *
     * @param dto
     * @return
     */
    CommonPage<BatchRecordArchiveVO> planArchiveRecordPage(RecordArchivePageDTO dto);

    /**
     * 重新生成批记录
     *
     * @param dto
     * @return
     */
    Long reGenerate(BatchRecordArchiveOperateDTO dto);

    /**
     * 下载批记录
     *
     * @param dto
     * @param response
     */
    void download(BatchRecordArchiveOperateDTO dto, HttpServletResponse response);

    /**
     * 审批
     * @param dto
     */
    void auditArchive(BatchRecordArchiveOperateDTO dto);

    /**
     * 作废批记录
     * @param dto
     */
    void scrapArchive(BatchRecordArchiveOperateDTO dto);

    /**
     * 生成批记录
     *
     * @param dto
     * @return
     */
    Long generateArchive(ArchiveGenerateDTO dto);

    /**
     * 工艺完成后 归档自动生成批记录
     * @param dto
     */
    void autoGenerateArchive(ArchiveAutoGenerateDTO dto);

    /**
     * 根据minio路径下载批记录
     *
     * @param path
     * @param response
     */
    void downloadPath(String path, HttpServletResponse response);

    /**
     * 查询批记录审批流程页
     * @param dto
     * @return
     */
    CommonPage<ArchiveAuditPageVO> archiveFlowPage(ArchiveAuditPageDTO dto);

    /**
     * 批记录审核回调
     * @param dto
     */
    void auditCallBack(ArchiveAuditCallBackDTO dto);

    /**
     * 判断记录是否生成完成
     * @param generateId
     * @return
     */
    String judgeGenerate(Long generateId);

    /**
     * 模板验证
     * @param dto
     * @return
     */
    Long verifyTemplateVersion(TemplateVerifyDTO dto);

    /**
     * 待办任务条件
     * @param deptIdList
     * @return
     */
    List<String> selectBusinessKeys(List<Long> deptIdList);

    /**
     * 定时删除验证数据
     */
    void removeVerifyArchive();

    /**
     * 直接将编辑状态的批记录变为生效状态
     * @param dto
     */
    void effectiveArchive(BatchRecordArchiveOperateDTO dto);

    BatchRecordArchive selectById(Long businessId);
}
