package com.bmos.mes.service.plan.document.controller;

import com.bmos.common.response.ResponseInfo;
import com.bmos.common.validate.EnumValidate;
import com.bmos.logging.annotation.OperationLog;
import com.bmos.mes.common.enums.CategoryInfoTypeEnum;
import com.bmos.mes.service.plan.document.controller.vo.*;
import com.bmos.mes.service.plan.document.service.BatchRecordArchiveLogService;
import com.bmos.mes.service.plan.document.service.BatchRecordArchiveService;
import com.bmos.mes.service.plan.document.service.dto.*;
import com.bmos.mes.service.product.vo.ProductCategoryTreeNodeVO;
import com.bmos.mybatis.page.CommonPage;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpServletResponse;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import java.util.List;

/**
 * 归档生成的批记录档案
 */
@RestController
@RequestMapping("/plan/archive")
@Api(tags = "归档生成的批记录档案（用于归档）")
public class BatchRecordArchiveController {

    @Autowired
    BatchRecordArchiveService batchRecordArchiveService;

    @Autowired
    BatchRecordArchiveLogService batchRecordArchiveLogService;

    @GetMapping("/productTree")
    @ApiOperation("获取批记录产品树")
    public ResponseInfo<List<ProductCategoryTreeNodeVO>> getBatchArchiveProductTree(@RequestParam("categoryType") @EnumValidate(value = CategoryInfoTypeEnum.class) @NotNull Integer categoryType,
                                                                                    @RequestParam(value = "templateId", required = false) Long templateId){
        return ResponseInfo.success(batchRecordArchiveService.getBatchArchiveProductTreeByTemplateId(categoryType, templateId));
    }

    @ApiOperation(value = "分页查询生产批号的工艺绑定了哪些模板")
    @GetMapping("/page")
    public ResponseInfo<CommonPage<RecordArchiveTemplateVersionVO>> archivePage(RecordArchiveTemplateVersionDTO dto) {
        return ResponseInfo.success(batchRecordArchiveService.archivePage(dto));
    }

    @ApiOperation(value = "[版本管理]生产信息")
    @GetMapping("/list")
    public ResponseInfo<BatchRecordVersionVO> planInfo(RecordPlanInfoDTO dto) {
        return ResponseInfo.success(batchRecordArchiveService.planInfo(dto));
    }

    @ApiOperation(value = "[版本管理]生产信息下生成的批记录")
    @GetMapping("/record/page")
    public ResponseInfo<CommonPage<BatchRecordArchiveVO>> planArchiveRecordPage(RecordArchivePageDTO dto) {
        return ResponseInfo.success(batchRecordArchiveService.planArchiveRecordPage(dto));
    }

    @ApiOperation(value = "重新生成批记录")
    @PutMapping("/reGenerate")
    @OperationLog
    public ResponseInfo<Long> reGenerate(@RequestBody BatchRecordArchiveOperateDTO dto) {
        return ResponseInfo.success(batchRecordArchiveService.reGenerate(dto));
    }

    @ApiOperation("下载批记录")
    @GetMapping("/download")
    @OperationLog
    public ResponseInfo<Void> download(BatchRecordArchiveOperateDTO dto, HttpServletResponse response) {
        batchRecordArchiveService.download(dto, response);
        return ResponseInfo.success();
    }

    @ApiOperation("提交审批")
    @PutMapping("/audit")
    @OperationLog
    public ResponseInfo<Void> auditArchive(@RequestBody BatchRecordArchiveOperateDTO dto) {
        batchRecordArchiveService.auditArchive(dto);
        return ResponseInfo.success();
    }

    @ApiOperation("作废批记录")
    @PutMapping("/scrap")
    @OperationLog
    public ResponseInfo<Void> scrapArchive(@RequestBody BatchRecordArchiveOperateDTO dto) {
        batchRecordArchiveService.scrapArchive(dto);
        return ResponseInfo.success();
    }

    @ApiOperation("批记录生成")
    @PutMapping("/generate")
    @OperationLog
    public ResponseInfo<Long> generateArchive(@RequestBody ArchiveGenerateDTO dto) {
        return ResponseInfo.success(batchRecordArchiveService.generateArchive(dto));
    }

    @ApiOperation("判断记录是否生成完成")
    @GetMapping("/judge/generate")
    public ResponseInfo<String> judgeGenerate(@RequestParam("generateId") Long generateId) {
        return ResponseInfo.success(batchRecordArchiveService.judgeGenerate(generateId));
    }

    @ApiOperation("工艺完成后归档自动生成批记录")
    @PutMapping("/auto/generate")
    @OperationLog
    public ResponseInfo<Void> autoGenerateArchive(@RequestBody ArchiveAutoGenerateDTO dto) {
        batchRecordArchiveService.autoGenerateArchive(dto);
        return ResponseInfo.success();
    }

    @ApiOperation("查询批记录审批流程页")
    @GetMapping("/flow/page")
    public ResponseInfo<CommonPage<ArchiveAuditPageVO>> archiveFlowPage(ArchiveAuditPageDTO dto) {
        return ResponseInfo.success(batchRecordArchiveService.archiveFlowPage(dto));
    }

    @ApiOperation("查询批记录操作历史")
    @GetMapping("/history/list")
    public ResponseInfo<List<ArchiveHistoryVO>> archiveHistoryList(BatchRecordArchiveOperateDTO dto) {
        return ResponseInfo.success(batchRecordArchiveLogService.archiveHistoryList(dto));
    }

    @ApiOperation("根据路径下载批记录（在历史中使用）")
    @GetMapping("/path/download")
    public ResponseInfo<Void> downloadPath(@RequestParam("path") @NotEmpty String path, HttpServletResponse response) {
        batchRecordArchiveService.downloadPath(path, response);
        return ResponseInfo.success();
    }

    @ApiOperation("mock")
    @PostMapping("/mock")
    public ResponseInfo<Void> mock(@RequestBody GenerateBatchRecordDTO dto) {
        batchRecordArchiveService.generateCallBack(dto);
        return ResponseInfo.success();
    }


    @ApiOperation(value = "批记录模板验证")
    @PutMapping("/version/verify")
    public ResponseInfo<Long> verifyTemplateVersion(@RequestBody TemplateVerifyDTO dto) {
        return ResponseInfo.success(batchRecordArchiveService.verifyTemplateVersion(dto));
    }

    @ApiOperation(value = "批记录确认生效")
    @PutMapping("/effective")
    @OperationLog
    public ResponseInfo<Void> effectiveArchive(@RequestBody BatchRecordArchiveOperateDTO dto) {
        batchRecordArchiveService.effectiveArchive(dto);
        return ResponseInfo.success();
    }


}
