-- 稳定性考察计划表
CREATE TABLE `lm_stability_inspect_plan` (
  `id`                BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `code`              VARCHAR(32)  NOT NULL COMMENT '考察计划编号（T+9位序号，如T000000001）',
  `scheme_id`         BIGINT       NOT NULL COMMENT '关联稳定性方案ID',
  `scheme_name`       VARCHAR(200) NOT NULL COMMENT '稳定性方案名称（冗余）',
  `scheme_version_id` BIGINT       NOT NULL COMMENT '关联稳定性方案版本ID',
  `scheme_version_no` VARCHAR(50)  NOT NULL COMMENT '稳定性方案版本号（冗余）',
  `material_id`       BIGINT       NOT NULL COMMENT '检品ID（物料ID）',
  `material_name`     VARCHAR(200) NOT NULL COMMENT '检品名称（冗余）',
  `material_code`     VARCHAR(100) NOT NULL COMMENT '检品编码（冗余）',
  `material_spec`     VARCHAR(200) DEFAULT NULL COMMENT '检品规格',
  `status`            VARCHAR(20)  NOT NULL DEFAULT 'PENDING' COMMENT '计划状态（PENDING:待开始 IN_PROGRESS:进行中 COMPLETED:已完成 PAUSED:已暂停）',
  `start_date`        DATE         DEFAULT NULL COMMENT '计划开始时间（最早样品接收时间，自动计算）',
  `plan_end_date`     DATE         DEFAULT NULL COMMENT '计划结束时间（根据方案时间点计算）',
  `pause_time`        DATETIME     DEFAULT NULL COMMENT '暂停时间',
  `pause_by`          VARCHAR(64)  DEFAULT NULL COMMENT '暂停操作人ID',
  `pause_by_name`     VARCHAR(100) DEFAULT NULL COMMENT '暂停操作人姓名',
  `pause_reason`      VARCHAR(500) DEFAULT NULL COMMENT '暂停理由',
  `remark`            VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `create_by`         VARCHAR(64)  DEFAULT NULL COMMENT '创建人',
  `update_by`         VARCHAR(64)  DEFAULT NULL COMMENT '更新人',
  `create_time`       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time`       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted`        TINYINT(1)   NOT NULL DEFAULT 0 COMMENT '是否删除（0:否 1:是）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_code` (`code`),
  KEY `idx_scheme_id` (`scheme_id`),
  KEY `idx_material_id` (`material_id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='稳定性考察计划表';


-- 稳定性考察计划批次表
CREATE TABLE `lm_stability_inspect_plan_batch` (
  `id`                  BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `plan_id`             BIGINT       NOT NULL COMMENT '考察计划ID',
  `batch_no`            VARCHAR(100) NOT NULL COMMENT '批号',
  `production_date`     DATE         DEFAULT NULL COMMENT '批次生产日期',
  `sample_receive_date` DATE         DEFAULT NULL COMMENT '样品接收日期（样品接收完成后更新）',
  `sort`                INT          NOT NULL DEFAULT 1 COMMENT '排序',
  `create_by`           VARCHAR(64)  DEFAULT NULL COMMENT '创建人',
  `update_by`           VARCHAR(64)  DEFAULT NULL COMMENT '更新人',
  `create_time`         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time`         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted`          TINYINT(1)   NOT NULL DEFAULT 0 COMMENT '是否删除（0:否 1:是）',
  PRIMARY KEY (`id`),
  KEY `idx_plan_id` (`plan_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='稳定性考察计划批次表';


-- 稳定性考察计划样品表
CREATE TABLE `lm_stability_plan_sample` (
  `id`                    BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `plan_id`               BIGINT       NOT NULL COMMENT '考察计划ID',
  `batch_id`              BIGINT       NOT NULL COMMENT '批次ID（lm_stability_inspect_plan_batch.id）',
  `batch_no`              VARCHAR(100) NOT NULL COMMENT '批号（冗余）',
  `scheme_plan_id`        BIGINT       NOT NULL COMMENT '方案检验计划ID（lm_stability_scheme_plan.id）',
  `experiment_type`       VARCHAR(200) DEFAULT NULL COMMENT '试验类型（冗余）',
  `storage_condition`     VARCHAR(200) DEFAULT NULL COMMENT '储存条件（冗余）',
  `planned_sample_amount` DECIMAL(10,4) DEFAULT NULL COMMENT '计划取样量',
  `sample_unit`           VARCHAR(50)  DEFAULT NULL COMMENT '取样量单位',
  `status`                VARCHAR(20)  NOT NULL DEFAULT 'PENDING' COMMENT '样品状态（PENDING:待取样 SAMPLED:已取样 RECEIVED:已接收）',
  `actual_sample_amount`  DECIMAL(10,4) DEFAULT NULL COMMENT '实际取样量',
  `sample_id`             BIGINT       DEFAULT NULL COMMENT '关联lm_sample的ID（整体取样后创建的父样品）',
  `sample_no`             VARCHAR(100) DEFAULT NULL COMMENT '样品编号（冗余）',
  `sampler_id`            VARCHAR(64)  DEFAULT NULL COMMENT '取样人ID',
  `sampler_name`          VARCHAR(100) DEFAULT NULL COMMENT '取样人姓名',
  `sampling_time`         DATETIME     DEFAULT NULL COMMENT '取样时间',
  `receiver_id`           VARCHAR(64)  DEFAULT NULL COMMENT '接收人ID',
  `receiver_name`         VARCHAR(100) DEFAULT NULL COMMENT '接收人姓名',
  `receive_time`          DATETIME     DEFAULT NULL COMMENT '接收时间',
  `receive_date`          DATE         DEFAULT NULL COMMENT '样品接收日期（作为时间点计划日期计算的起点）',
  `create_by`             VARCHAR(64)  DEFAULT NULL COMMENT '创建人',
  `update_by`             VARCHAR(64)  DEFAULT NULL COMMENT '更新人',
  `create_time`           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time`           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted`            TINYINT(1)   NOT NULL DEFAULT 0 COMMENT '是否删除（0:否 1:是）',
  PRIMARY KEY (`id`),
  KEY `idx_plan_id` (`plan_id`),
  KEY `idx_batch_id` (`batch_id`),
  KEY `idx_scheme_plan_id` (`scheme_plan_id`),
  KEY `idx_sample_id` (`sample_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='稳定性考察计划整体样品表';


-- 稳定性考察计划时间点任务表
CREATE TABLE `lm_stability_plan_timepoint_task` (
  `id`                   BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `plan_id`              BIGINT       NOT NULL COMMENT '考察计划ID',
  `batch_id`             BIGINT       NOT NULL COMMENT '批次ID（lm_stability_inspect_plan_batch.id）',
  `sample_id`            BIGINT       DEFAULT NULL COMMENT '样品ID（lm_stability_plan_sample.id）',
  `scheme_plan_id`       BIGINT       NOT NULL COMMENT '方案检验计划ID（lm_stability_scheme_plan.id）',
  `scheme_timepoint_id`  BIGINT       NOT NULL COMMENT '方案时间点ID（lm_stability_scheme_plan_timepoint.id）',
  `experiment_type`      VARCHAR(200) DEFAULT NULL COMMENT '试验类型（冗余）',
  `storage_condition`    VARCHAR(200) DEFAULT NULL COMMENT '储存条件（冗余）',
  `time_value`           INT          DEFAULT NULL COMMENT '时间点数值（冗余）',
  `time_unit`            VARCHAR(20)  DEFAULT NULL COMMENT '时间单位（DAY/WEEK/MONTH/YEAR，冗余）',
  `planned_date`         DATE         DEFAULT NULL COMMENT '计划检验日期（样品接收日期 + 时间点偏移）',
  `sample_amount`        DECIMAL(10,4) DEFAULT NULL COMMENT '取样量',
  `sample_unit`          VARCHAR(50)  DEFAULT NULL COMMENT '取样量单位',
  `status`               VARCHAR(30)  NOT NULL DEFAULT 'NOT_STARTED' COMMENT '任务状态（NOT_STARTED/WAITING_SAMPLE/IN_PROGRESS/COMPLETED）',
  `inspection_order_id`  BIGINT       DEFAULT NULL COMMENT '关联检验单ID（发起检验后关联）',
  `completed_date`       DATE         DEFAULT NULL COMMENT '实际检验完成日期',
  `create_by`            VARCHAR(64)  DEFAULT NULL COMMENT '创建人',
  `update_by`            VARCHAR(64)  DEFAULT NULL COMMENT '更新人',
  `create_time`          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time`          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted`           TINYINT(1)   NOT NULL DEFAULT 0 COMMENT '是否删除（0:否 1:是）',
  PRIMARY KEY (`id`),
  KEY `idx_plan_id` (`plan_id`),
  KEY `idx_batch_id` (`batch_id`),
  KEY `idx_sample_id` (`sample_id`),
  KEY `idx_inspection_order_id` (`inspection_order_id`),
  KEY `idx_status` (`status`),
  KEY `idx_planned_date` (`planned_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='稳定性考察计划时间点任务表';
