-- 创建留样接收台账表
CREATE TABLE IF NOT EXISTS `lm_retention_receive_ledger` (
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `sample_id` BIGINT(20) NOT NULL COMMENT '样品ID',
    `sample_no` VARCHAR(100) NOT NULL COMMENT '样品编号',
    `batch_no` VARCHAR(100) DEFAULT NULL COMMENT '批号',
    `material_id` BIGINT(20) DEFAULT NULL COMMENT '物料ID',
    `material_name` VARCHAR(200) DEFAULT NULL COMMENT '物料名称',
    `material_code` VARCHAR(100) DEFAULT NULL COMMENT '物料编码',
    `material_spec` VARCHAR(200) DEFAULT NULL COMMENT '物料规格',
    `quantity` VARCHAR(50) DEFAULT NULL COMMENT '样品数量',
    `unit_id` BIGINT(20) DEFAULT NULL COMMENT '单位ID',
    `sampler_id` VARCHAR(50) DEFAULT NULL COMMENT '取样人ID',
    `sampler_name` VARCHAR(100) DEFAULT NULL COMMENT '取样人名称',
    `sampling_time` DATETIME DEFAULT NULL COMMENT '取样时间',
    `receiver_id` VARCHAR(50) DEFAULT NULL COMMENT '接收人ID',
    `receiver_name` VARCHAR(100) DEFAULT NULL COMMENT '接收人名称',
    `receive_time` DATETIME DEFAULT NULL COMMENT '接收时间',
    `storage_location` VARCHAR(200) DEFAULT NULL COMMENT '储存位置',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` VARCHAR(50) DEFAULT NULL COMMENT '创建人',
    `update_by` VARCHAR(50) DEFAULT NULL COMMENT '更新人',
    PRIMARY KEY (`id`),
    KEY `idx_sample_id` (`sample_id`),
    KEY `idx_sample_no` (`sample_no`),
    KEY `idx_batch_no` (`batch_no`),
    KEY `idx_receive_time` (`receive_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='留样接收台账表';

-- 创建留样销毁台账表
CREATE TABLE IF NOT EXISTS `lm_retention_destruction_ledger` (
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `sample_id` BIGINT(20) NOT NULL COMMENT '样品ID',
    `sample_no` VARCHAR(100) NOT NULL COMMENT '样品编号',
    `batch_no` VARCHAR(100) DEFAULT NULL COMMENT '批号',
    `material_id` BIGINT(20) DEFAULT NULL COMMENT '物料ID',
    `material_name` VARCHAR(200) DEFAULT NULL COMMENT '物料名称',
    `material_code` VARCHAR(100) DEFAULT NULL COMMENT '物料编码',
    `material_spec` VARCHAR(200) DEFAULT NULL COMMENT '物料规格',
    `quantity` VARCHAR(50) DEFAULT NULL COMMENT '销毁数量',
    `unit_id` BIGINT(20) DEFAULT NULL COMMENT '单位ID',
    `destruction_method` VARCHAR(200) DEFAULT NULL COMMENT '销毁方式',
    `destruction_location` VARCHAR(200) DEFAULT NULL COMMENT '销毁地点',
    `destruction_time` DATETIME DEFAULT NULL COMMENT '销毁时间',
    `remark` TEXT COMMENT '备注',
    `destructor_id` VARCHAR(50) DEFAULT NULL COMMENT '销毁人ID',
    `destructor_name` VARCHAR(100) DEFAULT NULL COMMENT '销毁人名称',
    `supervisor_id` VARCHAR(50) DEFAULT NULL COMMENT '监督人ID',
    `supervisor_name` VARCHAR(100) DEFAULT NULL COMMENT '监督人名称',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` VARCHAR(50) DEFAULT NULL COMMENT '创建人',
    `update_by` VARCHAR(50) DEFAULT NULL COMMENT '更新人',
    PRIMARY KEY (`id`),
    KEY `idx_sample_id` (`sample_id`),
    KEY `idx_sample_no` (`sample_no`),
    KEY `idx_batch_no` (`batch_no`),
    KEY `idx_destruction_time` (`destruction_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='留样销毁台账表';
