server:
  port: 61001
  servlet:
    context-path: /api/app/lims2
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  servlet:
    multipart:
      max-file-size: 20971520
      max-request-size: 20971520
  main:
    allow-circular-references: true
