package com.bmos.lims2.common.enums;

import cn.hutool.core.util.StrUtil;
import com.baomidou.mybatisplus.annotation.EnumValue;
import com.bmos.common.base.enums.CommonEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.AllArgsConstructor;
import lombok.Getter;

import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Getter
@AllArgsConstructor
@JsonFormat(shape = JsonFormat.Shape.OBJECT)
public enum BusinessComponentTypeEnum implements CommonEnum<String> {

    /**
     * 自定义字段
     */
    CUSTOM_FIELD("CUSTOM_FIELD", "CUSTOM_FIELD", Integer.MAX_VALUE, false, new String[]{}),

    /**
     * 生产信息
     */
    BUSINESS_PRODUCT_INFO("BUSINESS_PRODUCT_INFO", "生产信息", 0, false, new String[]{}),
    BUSINESS_PRODUCT_INFO_NAME("BUSINESS_PRODUCT_INFO_NAME", "产品名称", 2, false, new String[]{}),
    BUSINESS_PRODUCT_INFO_CODE("BUSINESS_PRODUCT_INFO_CODE", "产品编码", 2, false, new String[]{}),
    BUSINESS_PRODUCT_INFO_SPECIFICATION("BUSINESS_PRODUCT_INFO_SPECIFICATION", "产品规格", 2, false, new String[]{}),
    BUSINESS_PRODUCT_INFO_PROCESS_NAME("BUSINESS_PRODUCT_INFO_PROCESS_NAME", "工艺名称", 2, false, new String[]{}),
    BUSINESS_PRODUCT_INFO_BATCHNO("BUSINESS_PRODUCT_INFO_BATCHNO", "生产批号", 2, false, new String[]{}),
    BUSINESS_PRODUCT_INFO_BATCH("BUSINESS_PRODUCT_INFO_BATCH", "生产批量", 2, false, new String[]{}),
    BUSINESS_PRODUCT_INFO_UNIT("BUSINESS_PRODUCT_INFO_UNIT", "单位", 2, false, new String[]{}),
    BUSINESS_PRODUCT_INFO_REVISION_NUMBER("BUSINESS_PRODUCT_INFO_REVISION_NUMBER", "修订数量", 2, false, new String[]{}),

    /**
     * 配方信息
     */
    BUSINESS_FORMULA_INFO("BUSINESS_FORMULA_INFO", "配方信息", 0, false, new String[]{}),
    /**
     * 配方信息 --> 配方物料
     */
    BUSINESS_FORMULA_INFO_MATERIAL("BUSINESS_FORMULA_INFO_MATERIAL", "配方物料", 1, false, new String[]{}),
    BUSINESS_FORMULA_INFO_MATERIAL_NAME("BUSINESS_FORMULA_INFO_MATERIAL_NAME", "物料名称", 2, false, new String[]{}),
    BUSINESS_FORMULA_INFO_MATERIAL_CODE("BUSINESS_FORMULA_INFO_MATERIAL_CODE", "物料编码", 2, false, new String[]{}),
    BUSINESS_FORMULA_INFO_MATERIAL_SPECIFICATION("BUSINESS_FORMULA_INFO_MATERIAL_SPECIFICATION", "物料规格", 2, false, new String[]{}),
    BUSINESS_FORMULA_INFO_THEORETICAL_QUANTITY("BUSINESS_FORMULA_INFO_THEORETICAL_QUANTITY", "理论用量", 2, false, new String[]{}),
    BUSINESS_FORMULA_INFO_UNIT("BUSINESS_FORMULA_INFO_UNIT", "单位", 2, false, new String[]{}),

    /**
     * 按批次量领料
     */
    BATCH_QUANTITY_PICK("BATCH_QUANTITY_PICK", "按批次量领料", 0, false, new String[]{}),
    /**
     * 按批次量领料 --> 物料批次
     */
    BATCH_QUANTITY_PICK_BATCH("BATCH_QUANTITY_PICK_BATCH", "物料批次", 0, false, new String[]{}),
    BATCH_QUANTITY_PICK_BATCH_NAME("BATCH_QUANTITY_PICK_BATCH_NAME", "物料名称", 2, false, new String[]{}),
    BATCH_QUANTITY_PICK_BATCH_CODE("BATCH_QUANTITY_PICK_BATCH_CODE", "物料编码", 2, false, new String[]{}),
    BATCH_QUANTITY_PICK_BATCH_SPECIFICATION("BATCH_QUANTITY_PICK_BATCH_SPECIFICATION", "物料规格", 2, false, new String[]{}),
    BATCH_QUANTITY_PICK_BATCH_BATCHNO("BATCH_QUANTITY_PICK_BATCH_BATCHNO", "物料批号", 2, false, new String[]{}),
    BATCH_QUANTITY_PICK_PLAN_PICK("BATCH_QUANTITY_PICK_PLAN_PICK", "计划领料量", 2, false, new String[]{}),
    BATCH_QUANTITY_PICK_THEORY_MATERIAL("BATCH_QUANTITY_PICK_THEORY_MATERIAL", "理论物料量", 2, false, new String[]{}),
    BATCH_QUANTITY_PICK_UNIT("BATCH_QUANTITY_PICK_UNIT", "单位", 2, false, new String[]{}),
    BATCH_QUANTITY_PICK_MOISTURE("BATCH_QUANTITY_PICK_MOISTURE", "水分", 2, false, new String[]{}),
    BATCH_QUANTITY_PICK_CONTENT("BATCH_QUANTITY_PICK_CONTENT", "含量", 2, false, new String[]{}),
    BATCH_QUANTITY_PICK_SUPPLIER("BATCH_QUANTITY_PICK_SUPPLIER", "供应商", 2, false, new String[]{}),
    BATCH_QUANTITY_PICK_PRODUCER("BATCH_QUANTITY_PICK_PRODUCER", "生产商", 2, false, new String[]{}),
    BATCH_QUANTITY_PICK_ORIGIN_BATCHNO("BATCH_QUANTITY_PICK_ORIGIN_BATCHNO", "原厂批号", 2, false, new String[]{}),
    BATCH_QUANTITY_PICK_ORIGIN_CODE("BATCH_QUANTITY_PICK_ORIGIN_CODE", "原始编码", 2, false, new String[]{}),
    BATCH_QUANTITY_PICK_EXPIRATION_DATE("BATCH_QUANTITY_PICK_EXPIRATION_DATE", "有效日期", 2, false, new String[]{}),
    /**
     * 按批次量领料 --> 物料汇总
     */
    BATCH_QUANTITY_PICK_SUMMARY("BATCH_QUANTITY_PICK_SUMMARY", "物料汇总", 1, false, new String[]{}),
    BATCH_QUANTITY_PICK_BATCH_SUMMARY_NAME("BATCH_QUANTITY_PICK_BATCH_SUMMARY_NAME", "物料名称", 2, false, new String[]{}),
    BATCH_QUANTITY_PICK_BATCH_SUMMARY_CODE("BATCH_QUANTITY_PICK_BATCH_SUMMARY_CODE", "物料编码", 2, false, new String[]{}),
    BATCH_QUANTITY_PICK_BATCH_SUMMARY_SPECIFICATION("BATCH_QUANTITY_PICK_BATCH_SUMMARY_SPECIFICATION", "物料规格", 2, false, new String[]{}),
    BATCH_QUANTITY_PICK_BATCH_SUMMARY_PLAN_PICK("BATCH_QUANTITY_PICK_BATCH_SUMMARY_PLAN_PICK", "计划量合计", 2, false, new String[]{}),
    BATCH_QUANTITY_PICK_BATCH_SUMMARY_THEORY_MATERIAL("BATCH_QUANTITY_PICK_BATCH_SUMMARY_THEORY_MATERIAL", "理论量合计", 2, false, new String[]{}),
    BATCH_QUANTITY_PICK_BATCH_SUMMARY_UNIT("BATCH_QUANTITY_PICK_BATCH_SUMMARY_UNIT", "单位", 2, false, new String[]{}),

    /**
     * 按物料量领料
     */
    MATERIAL_QUANTITY_PICK("MATERIAL_QUANTITY_PICK", "按物料量领料", 0, false, new String[]{}),
    MATERIAL_QUANTITY_PICK_MATERIAL("MATERIAL_QUANTITY_PICK_MATERIAL", "物料", 1, false, new String[]{}),
    MATERIAL_QUANTITY_PICK_MATERIAL_NAME("MATERIAL_QUANTITY_PICK_MATERIAL_NAME", "物料名称", 2, false, new String[]{}),
    MATERIAL_QUANTITY_PICK_MATERIAL_CODE("MATERIAL_QUANTITY_PICK_MATERIAL_CODE", "物料编码", 2, false, new String[]{}),
    MATERIAL_QUANTITY_PICK_MATERIAL_SPECIFICATION("MATERIAL_QUANTITY_PICK_MATERIAL_SPECIFICATION", "物料规格", 2, false, new String[]{}),
    MATERIAL_QUANTITY_PICK_MATERIAL_PICK("MATERIAL_QUANTITY_PICK_MATERIAL_PICK", "领料量", 2, false, new String[]{}),
    MATERIAL_QUANTITY_PICK_MATERIAL_UNIT("MATERIAL_QUANTITY_PICK_MATERIAL_UNIT", "单位", 2, false, new String[]{}),
    MATERIAL_QUANTITY_PICK_MATERIAL_SUPPLIER("MATERIAL_QUANTITY_PICK_MATERIAL_SUPPLIER", "供应商", 2, false, new String[]{}),
    MATERIAL_QUANTITY_PICK_MATERIAL_MANUFACTURER("MATERIAL_QUANTITY_PICK_MATERIAL_MANUFACTURER", "生产商", 2, false, new String[]{}),

    /**
     * 配料计划 -->物料汇总
     */
    INGREDIENTS_PLAN("INGREDIENTS_PLAN", "配料计划", 0, false, new String[]{}),
    INGREDIENTS_PLAN_MATERIAL("INGREDIENTS_PLAN_MATERIAL", "物料汇总", 1, false, new String[]{}),
    INGREDIENTS_PLAN_MATERIAL_NAME("INGREDIENTS_PLAN_MATERIAL_NAME", "物料名称", 2, false, new String[]{}),
    INGREDIENTS_PLAN_MATERIAL_CODE("INGREDIENTS_PLAN_MATERIAL_CODE", "物料编码", 2, false, new String[]{}),
    INGREDIENTS_PLAN_MATERIAL_SPECIFICATION("INGREDIENTS_PLAN_MATERIAL_SPECIFICATION", "物料规格", 2, false, new String[]{}),
    INGREDIENTS_PLAN_MATERIAL_BATCHNO("INGREDIENTS_PLAN_MATERIAL_BATCHNO", "物料批号", 2, false, new String[]{}),
    INGREDIENTS_PLAN_MATERIAL_QUANTITY("INGREDIENTS_PLAN_MATERIAL_QUANTITY", "批次配料量", 2, false, new String[]{}),
    INGREDIENTS_PLAN_MATERIAL_TOTAL("INGREDIENTS_PLAN_MATERIAL_TOTAL", "物料配料总量", 2, false, new String[]{}),
    INGREDIENTS_PLAN_MATERIAL_UNIT("INGREDIENTS_PLAN_MATERIAL_UNIT", "单位", 2, false, new String[]{}),
    INGREDIENTS_PLAN_MATERIAL_MOISTURE("INGREDIENTS_PLAN_MATERIAL_MOISTURE", "水分", 2, false, new String[]{}),
    INGREDIENTS_PLAN_MATERIAL_CONTENT("INGREDIENTS_PLAN_MATERIAL_CONTENT", "含量", 2, false, new String[]{}),
    INGREDIENTS_PLAN_MATERIAL_SUPPLIER("INGREDIENTS_PLAN_MATERIAL_SUPPLIER", "供应商", 2, false, new String[]{}),
    INGREDIENTS_PLAN_MATERIAL_MANUFACTURER("INGREDIENTS_PLAN_MATERIAL_MANUFACTURER", "生产商", 2, false, new String[]{}),
    INGREDIENTS_PLAN_MATERIAL_ORIGINAL_BATCHNO("INGREDIENTS_PLAN_MATERIAL_ORIGINAL_BATCHNO", "原厂批号", 2, false, new String[]{}),
    INGREDIENTS_PLAN_MATERIAL_ORIGINAL_CODE("INGREDIENTS_PLAN_MATERIAL_ORIGINAL_CODE", "原始编码", 2, false, new String[]{}),
    INGREDIENTS_PLAN_MATERIAL_REPORT_NO("INGREDIENTS_PLAN_MATERIAL_REPORT_NO", "报告单编号", 2, false, new String[]{}),
    INGREDIENTS_PLAN_MATERIAL_RELEASE_NO("INGREDIENTS_PLAN_MATERIAL_RELEASE_NO", "放行单编号", 2, false, new String[]{}),
    INGREDIENTS_PLAN_MATERIAL_EXPIRATION_DATE("INGREDIENTS_PLAN_MATERIAL_EXPIRATION_DATE", "有效日期", 2, false, new String[]{}),


    /**
     * 领料接收
     */
    PICKING_RECEIVING("PICKING_RECEIVING", "领料接收", 0, false, new String[]{}),
    /**
     * 领料接收 --> 物料批次
     */
    PICKING_RECEIVING_BATCH("PICKING_RECEIVING_BATCH", "物料批次", 0, false, new String[]{}),
    PICKING_RECEIVING_BATCH_NAME("PICKING_RECEIVING_BATCH_NAME", "物料名称", 2, false, new String[]{}),
    PICKING_RECEIVING_BATCH_CODE("PICKING_RECEIVING_BATCH_CODE", "物料编码", 2, false, new String[]{}),
    PICKING_RECEIVING_BATCH_SPECIFICATION("PICKING_RECEIVING_BATCH_SPECIFICATION", "物料规格", 2, false, new String[]{}),
    PICKING_RECEIVING_BATCH_BATCHNO("PICKING_RECEIVING_BATCH_BATCHNO", "物料批号", 2, false, new String[]{}),
    PICKING_RECEIVING_BATCH_PICK("PICKING_RECEIVING_BATCH_PICK", "领料量", 2, false, new String[]{}),
    PICKING_RECEIVING_BATCH_UNIT("PICKING_RECEIVING_BATCH_UNIT", "单位", 2, false, new String[]{}),
    PICKING_RECEIVING_BATCH_SUPPLIER("PICKING_RECEIVING_BATCH_SUPPLIER", "供应商", 2, false, new String[]{}),
    PICKING_RECEIVING_BATCH_PRODUCER("PICKING_RECEIVING_BATCH_PRODUCER", "生产商", 2, false, new String[]{}),
    PICKING_RECEIVING_BATCH_ORIGINAL_BATCHNO("PICKING_RECEIVING_BATCH_ORIGINAL_BATCHNO", "原始批号", 2, false, new String[]{}),
    PICKING_RECEIVING_BATCH_ORIGINAL_CODE("PICKING_RECEIVING_BATCH_ORIGINAL_CODE", "原始编码", 2, false, new String[]{}),
    PICKING_RECEIVING_BATCH_EXPIRATION_DATE("PICKING_RECEIVING_BATCH_EXPIRATION_DATE", "有效日期", 2, false, new String[]{}),
    /**
     * 领料接收 --> 物料汇总
     */
    PICKING_RECEIVING_SUMMARY("PICKING_RECEIVING_SUMMARY", "物料汇总", 1, false, new String[]{}),
    PICKING_RECEIVING_SUMMARY_NAME("PICKING_RECEIVING_SUMMARY_NAME", "物料名称", 2, false, new String[]{}),
    PICKING_RECEIVING_SUMMARY_CODE("PICKING_RECEIVING_SUMMARY_CODE", "物料编码", 2, false, new String[]{}),
    PICKING_RECEIVING_SUMMARY_SPECIFICATION("PICKING_RECEIVING_SUMMARY_SPECIFICATION", "物料规格", 2, false, new String[]{}),
    PICKING_RECEIVING_SUMMARY_PICK("PICKING_RECEIVING_SUMMARY_PICK", "领料量", 2, false, new String[]{}),
    PICKING_RECEIVING_SUMMARY_UNIT("PICKING_RECEIVING_SUMMARY_UNIT", "单位", 2, false, new String[]{}),


    /**
     * 设备 --> 设备信息组件
     */
    EQUIPMENT_INFO("EQUIPMENT_INFO", "设备信息", 0, false, new String[]{}),
    EQUIPMENT_INFO_CODE("EQUIPMENT_INFO_CODE", "设备编号", 1, false, new String[]{}),
    EQUIPMENT_INFO_NAME("EQUIPMENT_INFO_NAME", "设备名称", 1, false, new String[]{}),

    /**
     * 设备 --> 数采组件
     */
    EQUIPMENT_DATA_ACQUISITION("EQUIPMENT_DATA_ACQUISITION", "设备数采", 0, true, new String[]{"dateFormat"}),
    EQUIPMENT_DATA_ACQUISITION_GROUP("EQUIPMENT_DATA_ACQUISITION_GROUP","数采组",1,false,new String[]{}),
    EQUIPMENT_DATA_ACQUISITION_TIME("EQUIPMENT_DATA_ACQUISITION_TIME", "数采时间", 2, false, new String[]{}),
    EQUIPMENT_DATA_ACQUISITION_DYNAMIC_TABLE("EQUIPMENT_DATA_ACQUISITION_DYNAMIC_TABLE", "扩展表格", 2, false, new String[]{}),

    /**
     * 物料件信息
     */
    MATERIAL_INFO("MATERIAL_INFO", "物料件信息", 0, false, new String[]{}),
    MATERIAL_INFO_MATERIAL_NAME("MATERIAL_INFO_MATERIAL_NAME", "物料名称", 1, false, new String[]{}),
    MATERIAL_INFO_MATERIAL_CODE("MATERIAL_INFO_MATERIAL_CODE", "物料编码", 1, false, new String[]{}),
    MATERIAL_INFO_MATERIAL_BATCHNO("MATERIAL_INFO_MATERIAL_BATCHNO", "物料批号", 1, false, new String[]{}),
    MATERIAL_INFO_MATERIAL_PARTNO("MATERIAL_INFO_MATERIAL_PARTNO", "物料件号", 1, false, new String[]{}),
    MATERIAL_INFO_MATERIAL_QUANTITY("MATERIAL_INFO_MATERIAL_QUANTITY", "物料量", 1, false, new String[]{}),
    MATERIAL_INFO_NET_WEIGHT("MATERIAL_INFO_NET_WEIGHT", "净重", 1, false, new String[]{}),
    MATERIAL_INFO_TARE_WEIGHT("MATERIAL_INFO_TARE_WEIGHT", "皮重", 1, false, new String[]{}),
    MATERIAL_INFO_GROSS_WEIGHT("MATERIAL_INFO_GROSS_WEIGHT", "毛重", 1, false, new String[]{}),
    MATERIAL_INFO_UNIT("MATERIAL_INFO_UNIT", "单位", 1, false, new String[]{}),

    /**
     * 称量数据
     */
    WEIGHING_DATA("WEIGHING_DATA", "称量数据", 0, false, new String[]{}),
    WEIGHING_DATA_DETAIL("WEIGHING_DATA_DETAIL", "称量数据", 1, false, new String[]{}),
    WEIGHING_DATA_DETAIL_WEIGHT("WEIGHING_DATA_DETAIL_WEIGHT", "重量", 2, false, new String[]{}),
    WEIGHING_DATA_DETAIL_UNIT("WEIGHING_DATA_DETAIL_UNIT", "单位", 2, false, new String[]{}),
    WEIGHING_DATA_DETAIL_OPERATOR("WEIGHING_DATA_DETAIL_OPERATOR", "称量人", 2, false, new String[]{}),
    WEIGHING_DATA_DETAIL_TIME("WEIGHING_DATA_DETAIL_TIME", "称量时间", 2, false, new String[]{}),

    /**
     * 投料回收 -->投料详情
     */
    FEED_RECYCLE("FEED_RECYCLE","投料回收",0, false, new String[]{}),
    FEED_RECYCLE_FEEDING_DETAILS("FEED_RECYCLE_FEEDING_DETAILS","投料详情",0, false, new String[]{}),
    FEED_RECYCLE_FEEDING_DETAILS_MATERIAL_NAME("FEED_RECYCLE_FEEDING_DETAILS_MATERIAL_NAME","物料名称",2, false, new String[]{}),
    FEED_RECYCLE_FEEDING_DETAILS_MATERIAL_CODE("FEED_RECYCLE_FEEDING_DETAILS_MATERIAL_CODE","物料编码",2, false, new String[]{}),
    FEED_RECYCLE_FEEDING_DETAILS_MATERIAL_SPECIFICATION("FEED_RECYCLE_FEEDING_DETAILS_MATERIAL_SPECIFICATION","物料规格",2, false, new String[]{}),
    FEED_RECYCLE_FEEDING_DETAILS_MATERIAL_BATCHNO("FEED_RECYCLE_FEEDING_DETAILS_MATERIAL_BATCHNO","物料批号",2, false, new String[]{}),
    FEED_RECYCLE_FEEDING_DETAILS_MATERIAL_PARTNO("FEED_RECYCLE_FEEDING_DETAILS_MATERIAL_PARTNO","物料件号",2, false, new String[]{}),
    FEED_RECYCLE_FEEDING_DETAILS_MATERIAL_QUANTITY("FEED_RECYCLE_FEEDING_DETAILS_MATERIAL_QUANTITY","物料量",2, false, new String[]{}),
    FEED_RECYCLE_FEEDING_DETAILS_UNIT("FEED_RECYCLE_FEEDING_DETAILS_UNIT","单位",2, false, new String[]{}),
    FEED_RECYCLE_FEEDING_DETAILS_OPERATION_TYPE("FEED_RECYCLE_FEEDING_DETAILS_OPERATION_TYPE","操作类型",2, false, new String[]{}),
    FEED_RECYCLE_FEEDING_DETAILS_OPERATOR("FEED_RECYCLE_FEEDING_DETAILS_OPERATOR","操作人",2, false, new String[]{}),
    FEED_RECYCLE_FEEDING_DETAILS_OPERATION_TIME("FEED_RECYCLE_FEEDING_DETAILS_OPERATION_TIME","操作时间",2, false, new String[]{}),
    FEED_RECYCLE_FEEDING_DETAILS_DEVICE_NAME("FEED_RECYCLE_FEEDING_DETAILS_DEVICE_NAME","设备名称",2, false, new String[]{}),
    FEED_RECYCLE_FEEDING_DETAILS_DEVICE_CODE("FEED_RECYCLE_FEEDING_DETAILS_DEVICE_CODE","设备编号",2, false, new String[]{}),
    /**
     * 投料回收 --> 物料汇总
     */
    FEED_RECYCLE_SUMMARY("FEED_RECYCLE_SUMMARY","物料汇总", 1, false, new String[]{}),
    FEED_RECYCLE_SUMMARY_MATERIAL_NAME("FEED_RECYCLE_SUMMARY_MATERIAL_NAME","物料名称",2, false, new String[]{}),
    FEED_RECYCLE_SUMMARY_MATERIAL_CODE("FEED_RECYCLE_SUMMARY_MATERIAL_CODE","物料编码",2, false, new String[]{}),
    FEED_RECYCLE_SUMMARY_MATERIAL_SPECIFICATION("FEED_RECYCLE_SUMMARY_MATERIAL_SPECIFICATION","物料规格",2, false, new String[]{}),
    FEED_RECYCLE_SUMMARY_TOTAL_QUANTITY("FEED_RECYCLE_SUMMARY_TOTAL_QUANTITY","投料总量",2, false, new String[]{}),
    FEED_RECYCLE_SUMMARY_RECYCLE_TOTAL_QUANTITY("FEED_RECYCLE_SUMMARY_RECYCLE_TOTAL_QUANTITY","回收总量",2, false, new String[]{}),
    FEED_RECYCLE_SUMMARY_USE_TOTAL_QUANTITY("FEED_RECYCLE_SUMMARY_USE_TOTAL_QUANTITY","使用总量",2, false, new String[]{}),
    FEED_RECYCLE_SUMMARY_UNIT("FEED_RECYCLE_SUMMARY_UNIT","单位",2, false, new String[]{}),
    FEED_RECYCLE_SUMMARY_TOTAL_NUMBER("FEED_RECYCLE_SUMMARY_TOTAL_NUMBER","投料件数",2, false, new String[]{}),
    FEED_RECYCLE_SUMMARY_RECYCLE_TOTAL_NUMBER("FEED_RECYCLE_SUMMARY_RECYCLE_TOTAL_NUMBER","回收件数",2, false, new String[]{}),

    /**
     * 成品产出 --> 产出详情
     */
    PRODUCT_OUTPUT("PRODUCT_OUTPUT","成品产出",0, false, new String[]{}),
    PRODUCT_OUTPUT_DETAILS("PRODUCT_OUTPUT_DETAILS","产出详情",0, false, new String[]{}),
    PRODUCT_OUTPUT_DETAILS_NAME("PRODUCT_OUTPUT_DETAILS_NAME","成品名称",2, false, new String[]{}),
    PRODUCT_OUTPUT_DETAILS_CODE("PRODUCT_OUTPUT_DETAILS_CODE","成品编码",2, false, new String[]{}),
    PRODUCT_OUTPUT_DETAILS_SPECIFICATION("PRODUCT_OUTPUT_DETAILS_SPECIFICATION","成品规格",2, false, new String[]{}),
    PRODUCT_OUTPUT_DETAILS_BATCH_NO("PRODUCT_OUTPUT_DETAILS_BATCH_NO","成品批号",2, false, new String[]{}),
    PRODUCT_OUTPUT_DETAILS_SINGLE_QUANTITY("PRODUCT_OUTPUT_DETAILS_SINGLE_QUANTITY","单件量",2, false, new String[]{}),
    PRODUCT_OUTPUT_DETAILS_UNIT("PRODUCT_OUTPUT_DETAILS_UNIT","单位",2, false, new String[]{}),
    PRODUCT_OUTPUT_DETAILS_SIZE("PRODUCT_OUTPUT_DETAILS_SIZE","产出件数",2, false, new String[]{}),
    PRODUCT_OUTPUT_DETAILS_OPERATOR("PRODUCT_OUTPUT_DETAILS_OPERATOR","操作人",2, false, new String[]{}),
    PRODUCT_OUTPUT_DETAILS_OPERATE_TIME("PRODUCT_OUTPUT_DETAILS_OPERATE_TIME","操作时间",2, false, new String[]{}),
    /**
     * 成品产出 --> 成品汇总
     */
    PRODUCT_OUTPUT_SUMMARY("PRODUCT_OUTPUT_SUMMARY","成品汇总",1, false, new String[]{}),
    PRODUCT_OUTPUT_SUMMARY_NAME("PRODUCT_OUTPUT_SUMMARY_NAME","成品名称",2, false, new String[]{}),
    PRODUCT_OUTPUT_SUMMARY_CODE("PRODUCT_OUTPUT_SUMMARY_CODE","成品编码",2, false, new String[]{}),
    PRODUCT_OUTPUT_SUMMARY_SPECIFICATION("PRODUCT_OUTPUT_SUMMARY_SPECIFICATION","成品规格",2, false, new String[]{}),
    PRODUCT_OUTPUT_SUMMARY_OUTPUT_TOTAL("PRODUCT_OUTPUT_SUMMARY_OUTPUT_TOTAL","产出总量",2, false, new String[]{}),
    PRODUCT_OUTPUT_SUMMARY_SIZE_TOTAL("PRODUCT_OUTPUT_SUMMARY_SIZE_TOTAL","总件数",2, false, new String[]{}),

    /**
     * 配料投入
     */
    INGREDIENTS_INPUT("INGREDIENTS_INPUT","配料投入",0, false, new String[]{}),
    /**
     * 配料投入 物料汇总
     */
    INGREDIENTS_INPUT_SUMMARY("INGREDIENTS_INPUT_SUMMARY","物料汇总",1, false, new String[]{}),
    INGREDIENTS_INPUT_SUMMARY_MATERIAL_NAME("INGREDIENTS_INPUT_SUMMARY_MATERIAL_NAME","物料名称",2, false, new String[]{}),
    INGREDIENTS_INPUT_SUMMARY_MATERIAL_CODE("INGREDIENTS_INPUT_SUMMARY_MATERIAL_CODE","物料编码",2, false, new String[]{}),
    INGREDIENTS_INPUT_SUMMARY_MATERIAL_SPECIFICATION("INGREDIENTS_INPUT_SUMMARY_MATERIAL_SPECIFICATION","物料规格",2, false, new String[]{}),
    INGREDIENTS_INPUT_SUMMARY_TOTAL_QUANTITY("INGREDIENTS_INPUT_SUMMARY_TOTAL_QUANTITY","投料总量",2, false, new String[]{}),
    INGREDIENTS_INPUT_SUMMARY_UNIT("INGREDIENTS_INPUT_SUMMARY_UNIT","单位",2, false, new String[]{}),
    INGREDIENTS_INPUT_SUMMARY_TOTAL_NUMBER("INGREDIENTS_INPUT_SUMMARY_TOTAL_NUMBER","总件数",2, false, new String[]{}),
    /**
     * 配料投入 投料详情
     */
    INGREDIENTS_INPUT_FEEDING_DETAILS("INGREDIENTS_INPUT_FEEDING_DETAILS","投料详情",0, false, new String[]{}),
    INGREDIENTS_INPUT_FEEDING_DETAILS_MATERIAL_NAME("INGREDIENTS_INPUT_FEEDING_DETAILS_MATERIAL_NAME","物料名称",2, false, new String[]{}),
    INGREDIENTS_INPUT_FEEDING_DETAILS_MATERIAL_CODE("INGREDIENTS_INPUT_FEEDING_DETAILS_MATERIAL_CODE","物料编码",2, false, new String[]{}),
    INGREDIENTS_INPUT_FEEDING_DETAILS_MATERIAL_SPECIFICATION("INGREDIENTS_INPUT_FEEDING_DETAILS_MATERIAL_SPECIFICATION","物料规格",2, false, new String[]{}),
    INGREDIENTS_INPUT_FEEDING_DETAILS_MATERIAL_BATCHNO("INGREDIENTS_INPUT_FEEDING_DETAILS_MATERIAL_BATCHNO","物料批号",2, false, new String[]{}),
    INGREDIENTS_INPUT_FEEDING_DETAILS_MATERIAL_PARTNO("INGREDIENTS_INPUT_FEEDING_DETAILS_MATERIAL_PARTNO","物料件号",2, false, new String[]{}),
    INGREDIENTS_INPUT_FEEDING_DETAILS_MATERIAL_QUANTITY("INGREDIENTS_INPUT_FEEDING_DETAILS_MATERIAL_QUANTITY","物料量",2, false, new String[]{}),
    INGREDIENTS_INPUT_FEEDING_DETAILS_UNIT("INGREDIENTS_INPUT_FEEDING_DETAILS_UNIT","单位",2, false, new String[]{}),
    INGREDIENTS_INPUT_FEEDING_DETAILS_FEEDER("INGREDIENTS_INPUT_FEEDING_DETAILS_FEEDER","投料人",2, false, new String[]{}),
    INGREDIENTS_INPUT_FEEDING_DETAILS_FEEDING_TIME("INGREDIENTS_INPUT_FEEDING_DETAILS_FEEDING_TIME","投料时间",2, false, new String[]{}),
    INGREDIENTS_INPUT_FEEDING_DETAILS_DEVICE_NAME("INGREDIENTS_INPUT_FEEDING_DETAILS_DEVICE_NAME","设备名称",2, false, new String[]{}),
    INGREDIENTS_INPUT_FEEDING_DETAILS_DEVICE_CODE("INGREDIENTS_INPUT_FEEDING_DETAILS_DEVICE_CODE","设备编号",2, false, new String[]{}),

    // 配料称量
    WEIGHING_INGREDIENTS("WEIGHING_INGREDIENTS", "配料称量", 0, false, new String[]{}),
    // 配料称量详情
    WEIGHING_INGREDIENTS_DETAILS("WEIGHING_INGREDIENTS_DETAILS", "配料称量详情", 0, false, new String[]{}),
    // 配料称量详情相关字段
    WEIGHING_INGREDIENTS_DETAILS_NAME("WEIGHING_INGREDIENTS_DETAILS_NAME", "物料名称", 2, false, new String[]{}),
    WEIGHING_INGREDIENTS_DETAILS_CODE("WEIGHING_INGREDIENTS_DETAILS_CODE", "物料编码", 2, false, new String[]{}),
    WEIGHING_INGREDIENTS_DETAILS_SPECIFICATION("WEIGHING_INGREDIENTS_DETAILS_SPECIFICATION", "物料规格", 2, false, new String[]{}),
    WEIGHING_INGREDIENTS_DETAILS_BATCHNO("WEIGHING_INGREDIENTS_DETAILS_BATCHNO", "物料批号", 2, false, new String[]{}),
    WEIGHING_INGREDIENTS_DETAILS_PART_NUMBER("WEIGHING_INGREDIENTS_DETAILS_PART_NUMBER", "物料件号", 2, false, new String[]{}),
    WEIGHING_INGREDIENTS_DETAILS_NET_WEIGHT("WEIGHING_INGREDIENTS_DETAILS_NET_WEIGHT", "净重", 2, false, new String[]{}),
    WEIGHING_INGREDIENTS_DETAILS_TARE_WEIGHT("WEIGHING_INGREDIENTS_DETAILS_TARE_WEIGHT", "皮重", 2, false, new String[]{}),
    WEIGHING_INGREDIENTS_DETAILS_GROSS_WEIGHT("WEIGHING_INGREDIENTS_DETAILS_GROSS_WEIGHT", "毛重", 2, false, new String[]{}),
    WEIGHING_INGREDIENTS_DETAILS_UNIT("WEIGHING_INGREDIENTS_DETAILS_UNIT", "单位", 2, false, new String[]{}),
    WEIGHING_INGREDIENTS_DETAILS_WEIGHER("WEIGHING_INGREDIENTS_DETAILS_WEIGHER", "称量人", 2, false, new String[]{}),
    WEIGHING_INGREDIENTS_DETAILS_REVIEWER("WEIGHING_INGREDIENTS_DETAILS_REVIEWER", "复核人", 2, false, new String[]{}),
    WEIGHING_INGREDIENTS_DETAILS_WEIGHING_TIME("WEIGHING_INGREDIENTS_DETAILS_WEIGHING_TIME", "称量时间", 2, false, new String[]{}),

    // 配料称量汇总
    WEIGHING_INGREDIENTS_SUMMARY("WEIGHING_INGREDIENTS_SUMMARY", "配料称量汇总", 1, false, new String[]{}),
    // 配料称量汇总相关字段
    WEIGHING_INGREDIENTS_SUMMARY_NAME("WEIGHING_INGREDIENTS_SUMMARY_NAME", "物料名称", 2, false, new String[]{}),
    WEIGHING_INGREDIENTS_SUMMARY_CODE("WEIGHING_INGREDIENTS_SUMMARY_CODE", "物料编码", 2, false, new String[]{}),
    WEIGHING_INGREDIENTS_SUMMARY_SPECIFICATION("WEIGHING_INGREDIENTS_SUMMARY_SPECIFICATION", "物料规格", 2, false, new String[]{}),
    WEIGHING_INGREDIENTS_SUMMARY_NET_WEIGHT("WEIGHING_INGREDIENTS_SUMMARY_NET_WEIGHT", "总净重", 2, false, new String[]{}),
    WEIGHING_INGREDIENTS_SUMMARY_TARE_WEIGHT("WEIGHING_INGREDIENTS_SUMMARY_TARE_WEIGHT", "总皮重", 2, false, new String[]{}),
    WEIGHING_INGREDIENTS_SUMMARY_GROSS_WEIGHT("WEIGHING_INGREDIENTS_SUMMARY_GROSS_WEIGHT", "总毛重", 2, false, new String[]{}),
    WEIGHING_INGREDIENTS_SUMMARY_UNIT("WEIGHING_INGREDIENTS_SUMMARY_UNIT", "单位", 2, false, new String[]{}),
    WEIGHING_INGREDIENTS_SUMMARY_TOTAL_NUMBER("WEIGHING_INGREDIENTS_SUMMARY_TOTAL_NUMBER", "总件数", 2, false, new String[]{}),


    // 产出称量
    OUTPUT_WEIGHING("OUTPUT_WEIGHING", "产出称量", 0, false, new String[]{}),
    // 产出称量详情
    OUTPUT_WEIGHING_DETAILS("OUTPUT_WEIGHING_DETAILS", "产出称量详情", 0, false, new String[]{}),
    // 产出称量详情相关字段
    OUTPUT_WEIGHING_DETAILS_NAME("OUTPUT_WEIGHING_DETAILS_NAME", "物料名称", 2, false, new String[]{}),
    OUTPUT_WEIGHING_DETAILS_CODE("OUTPUT_WEIGHING_DETAILS_CODE", "物料编码", 2, false, new String[]{}),
    OUTPUT_WEIGHING_DETAILS_SPECIFICATION("OUTPUT_WEIGHING_DETAILS_SPECIFICATION", "物料规格", 2, false, new String[]{}),
    OUTPUT_WEIGHING_DETAILS_BATCHNO("OUTPUT_WEIGHING_DETAILS_BATCHNO", "物料批号", 2, false, new String[]{}),
    OUTPUT_WEIGHING_DETAILS_PART_NUMBER("OUTPUT_WEIGHING_DETAILS_PART_NUMBER", "物料件号", 2, false, new String[]{}),
    OUTPUT_WEIGHING_DETAILS_QUANTITY("OUTPUT_WEIGHING_DETAILS_QUANTITY", "物料量", 2, false, new String[]{}),
    OUTPUT_WEIGHING_DETAILS_NET_WEIGHT("OUTPUT_WEIGHING_DETAILS_NET_WEIGHT", "净重", 2, false, new String[]{}),
    OUTPUT_WEIGHING_DETAILS_TARE_WEIGHT("OUTPUT_WEIGHING_DETAILS_TARE_WEIGHT", "皮重", 2, false, new String[]{}),
    OUTPUT_WEIGHING_DETAILS_GROSS_WEIGHT("OUTPUT_WEIGHING_DETAILS_GROSS_WEIGHT", "毛重", 2, false, new String[]{}),
    OUTPUT_WEIGHING_DETAILS_UNIT("OUTPUT_WEIGHING_DETAILS_UNIT", "单位", 2, false, new String[]{}),
    OUTPUT_WEIGHING_DETAILS_WEIGHER("OUTPUT_WEIGHING_DETAILS_WEIGHER", "称量人", 2, false, new String[]{}),
    OUTPUT_WEIGHING_DETAILS_REVIEWER("OUTPUT_WEIGHING_DETAILS_REVIEWER", "复核人", 2, false, new String[]{}),
    OUTPUT_WEIGHING_DETAILS_WEIGHING_TIME("OUTPUT_WEIGHING_DETAILS_WEIGHING_TIME", "称量时间", 2, false, new String[]{}),

    // 产出称量汇总
    OUTPUT_WEIGHING_SUMMARY("OUTPUT_WEIGHING_SUMMARY", "产出称量汇总", 1, false, new String[]{}),
    // 产出称量汇总相关字段
    OUTPUT_WEIGHING_SUMMARY_NAME("OUTPUT_WEIGHING_SUMMARY_NAME", "物料名称", 2, false, new String[]{}),
    OUTPUT_WEIGHING_SUMMARY_CODE("OUTPUT_WEIGHING_SUMMARY_CODE", "物料编码", 2, false, new String[]{}),
    OUTPUT_WEIGHING_SUMMARY_SPECIFICATION("OUTPUT_WEIGHING_SUMMARY_SPECIFICATION", "物料规格", 2, false, new String[]{}),
    OUTPUT_WEIGHING_SUMMARY_TOTAL_QUANTITY("OUTPUT_WEIGHING_SUMMARY_TOTAL_QUANTITY", "物料总量", 2, false, new String[]{}),
    OUTPUT_WEIGHING_SUMMARY_NET_WEIGHT("OUTPUT_WEIGHING_SUMMARY_NET_WEIGHT", "总净重", 2, false, new String[]{}),
    OUTPUT_WEIGHING_SUMMARY_TARE_WEIGHT("OUTPUT_WEIGHING_SUMMARY_TARE_WEIGHT", "总皮重", 2, false, new String[]{}),
    OUTPUT_WEIGHING_SUMMARY_GROSS_WEIGHT("OUTPUT_WEIGHING_SUMMARY_GROSS_WEIGHT", "总毛重", 2, false, new String[]{}),
    OUTPUT_WEIGHING_SUMMARY_UNIT("OUTPUT_WEIGHING_SUMMARY_UNIT", "单位", 2, false, new String[]{}),
    OUTPUT_WEIGHING_SUMMARY_TOTAL_NUMBER("OUTPUT_WEIGHING_SUMMARY_TOTAL_NUMBER", "总件数", 2, false, new String[]{}),

    // *************************** 清场信息组件 ********************************
    CLEAN_INFO("CLEAN_INFO", "清场信息", 1, false, new String[]{}),
    CLEAN_INFO_GROUP("CLEAN_INFO_GROUP", "清场信息组", 2, false, new String[]{}),
    CLEAN_INFO_BATCHNO("CLEAN_INFO_BATCHNO", "生产批号", 3, false, new String[]{}),
    CLEAN_INFO_PRODUCT_NAME("CLEAN_INFO_PRODUCT_NAME", "产品名称", 3, false, new String[]{}),
    CLEAN_INFO_PRODUCT_NO("CLEAN_INFO_PRODUCT_NO", "产品编号", 3, false, new String[]{}),
    CLEAN_INFO_PROCEDURE("CLEAN_INFO_PROCEDURE", "工序", 3, false, new String[]{}),
    CLEAN_INFO_ROOM_NAME("CLEAN_INFO_ROOM_NAME", "房间名称", 3, false, new String[]{}),
    CLEAN_INFO_ROOM_CODE("CLEAN_INFO_ROOM_CODE", "房间编码", 3, false, new String[]{}),
    CLEAN_INFO_START_TIME("CLEAN_INFO_START_TIME", "清场开始时间", 3, false, new String[]{}),
    CLEAN_INFO_END_TIME("CLEAN_INFO_END_TIME", "清场结束时间", 3, false, new String[]{}),
    CLEAN_INFO_CLEAN_DATE("CLEAN_INFO_CLEAN_DATE", "清场日期", 3, false, new String[]{}),
    CLEAN_INFO_EXPIRATION_DATE("CLEAN_INFO_EXPIRATION_DATE", "有效期至", 3, false, new String[]{}),
    CLEAN_INFO_CLEAN_PERSON("CLEAN_INFO_CLEAN_PERSON", "清场人", 3, false, new String[]{}),
    CLEAN_INFO_QUALITY_INSPECTION_PERSON("CLEAN_INFO_QUALITY_INSPECTION_PERSON", "质检人", 3, false, new String[]{}),
    CLEAN_INFO_ROOM_QUALITY_INSPECTION_DATE("CLEAN_INFO_ROOM_QUALITY_INSPECTION_DATE", "质检日期", 3, false, new String[]{}),
    // *************************** 清场执行组件 ********************************
    CLEAN_IMPLEMENT_PRODUCT("CLEAN_IMPLEMENT", "清场执行", 1, false, new String[]{}),
    CLEAN_IMPLEMENT_PRODUCT_GROUP("CLEAN_IMPLEMENT_PRODUCT_GROUP", "清场执行信息组", 2, false, new String[]{}),
    CLEAN_IMPLEMENT_BATCHNO("CLEAN_IMPLEMENT_BATCHNO", "生产批号", 3, false, new String[]{}),
    CLEAN_IMPLEMENT_PRODUCT_NAME("CLEAN_IMPLEMENT_PRODUCT_NAME", "产品名称", 3, false, new String[]{}),
    CLEAN_IMPLEMENT_PRODUCT_NO("CLEAN_IMPLEMENT_PRODUCT_NO", "产品编号", 3, false, new String[]{}),
    CLEAN_IMPLEMENT_PROCEDURE("CLEAN_IMPLEMENT_PROCEDURE", "工序", 3, false, new String[]{}),
    CLEAN_IMPLEMENT_ROOM_NAME("CLEAN_IMPLEMENT_ROOM_NAME", "房间名称", 3, false, new String[]{}),
    CLEAN_IMPLEMENT_ROOM_CODE("CLEAN_IMPLEMENT_ROOM_CODE", "房间编码", 3, false, new String[]{}),
    CLEAN_IMPLEMENT_START_TIME("CLEAN_IMPLEMENT_START_TIME", "清场开始时间", 3, false, new String[]{}),
    CLEAN_IMPLEMENT_END_TIME("CLEAN_IMPLEMENT_END_TIME", "清场结束时间", 3, false, new String[]{}),
    CLEAN_IMPLEMENT_CLEAN_DATE("CLEAN_IMPLEMENT_CLEAN_DATE", "清场日期", 3, false, new String[]{}),
    CLEAN_IMPLEMENT_EXPIRATION_DATE("CLEAN_IMPLEMENT_EXPIRATION_DATE", "有效期至", 3, false, new String[]{}),
    CLEAN_IMPLEMENT_CLEAN_PERSON("CLEAN_IMPLEMENT_CLEAN_PERSON", "清场人", 3, false, new String[]{}),
    CLEAN_IMPLEMENT_QUALITY_INSPECTION_PERSON("CLEAN_IMPLEMENT_QUALITY_INSPECTION_PERSON", "质检人", 3, false, new String[]{}),
    CLEAN_IMPLEMENT_ROOM_QUALITY_INSPECTION_DATE("CLEAN_IMPLEMENT_ROOM_QUALITY_INSPECTION_DATE", "质检日期", 3, false, new String[]{}),
    // *************************** 清场检查组件 ********************************
    CLEAN_CHECK_ROOM("CLEAN_CHECK", "清场检查", 1, false, new String[]{}),
    CLEAN_CHECK_ROOM_GROUP("CLEAN_CHECK_ROOM_GROUP", "清场检查组", 2, false, new String[]{}),
    CLEAN_CHECK_BATCHNO("CLEAN_CHECK_BATCHNO", "生产批号", 3, false, new String[]{}),
    CLEAN_CHECK_PRODUCT_NAME("CLEAN_CHECK_PRODUCT_NAME", "产品名称", 3, false, new String[]{}),
    CLEAN_CHECK_PRODUCT_NO("CLEAN_CHECK_PRODUCT_NO", "产品编号", 3, false, new String[]{}),
    CLEAN_CHECK_PROCEDURE("CLEAN_CHECK_PROCEDURE", "工序", 3, false, new String[]{}),
    CLEAN_CHECK_ROOM_NAME("CLEAN_CHECK_ROOM_NAME", "房间名称", 2, false, new String[]{}),
    CLEAN_CHECK_ROOM_CODE("CLEAN_CHECK_ROOM_CODE", "房间编码", 3, false, new String[]{}),
    CLEAN_CHECK_START_TIME("CLEAN_CHECK_START_TIME", "清场开始时间", 3, false, new String[]{}),
    CLEAN_CHECK_END_TIME("CLEAN_CHECK_END_TIME", "清场结束时间", 3, false, new String[]{}),
    CLEAN_CHECK_CLEAN_DATE("CLEAN_CHECK_CLEAN_DATE", "清场日期", 3, false, new String[]{}),
    CLEAN_CHECK_EXPIRATION_DATE("CLEAN_CHECK_EXPIRATION_DATE", "有效期至", 3, false, new String[]{}),
    CLEAN_CHECK_CLEAN_PERSON("CLEAN_CHECK_CLEAN_PERSON", "清场人", 3, false, new String[]{}),
    CLEAN_CHECK_QUALITY_INSPECTION_PERSON("CLEAN_CHECK_QUALITY_INSPECTION_PERSON", "质检人", 3, false, new String[]{}),
    CLEAN_CHECK_ROOM_QUALITY_INSPECTION_DATE("CLEAN_CHECK_ROOM_QUALITY_INSPECTION_DATE", "质检日期", 3, false, new String[]{}),

    /**
     * 物料预定组件 -->物料汇总
     */
    MATERIAL_RESERVE("MATERIAL_RESERVE","物料预定",0, false, new String[]{}),
    MATERIAL_RESERVE_SUMMARY("MATERIAL_RESERVE_SUMMARY","物料汇总",1, false, new String[]{}),
    MATERIAL_RESERVE_MATERIAL_NAME("MATERIAL_RESERVE_MATERIAL_NAME","物料名称",2, false, new String[]{}),
    MATERIAL_RESERVE_MATERIAL_CODE("MATERIAL_RESERVE_MATERIAL_CODE","物料编码",2, false, new String[]{}),
    MATERIAL_RESERVE_MATERIAL_SPECIFICATION("MATERIAL_RESERVE_MATERIAL_SPECIFICATION","物料规格",2, false, new String[]{}),
    MATERIAL_RESERVE_BATCH_NO("MATERIAL_RESERVE_BATCH_NO","物料批号",2, false, new String[]{}),
    MATERIAL_RESERVE_BATCH_RESERVE_QUANTITY("MATERIAL_RESERVE_BATCH_RESERVE_QUANTITY","批次预定量",2, false, new String[]{}),
    MATERIAL_RESERVE_RESERVE_TOTAL_QUANTITY("MATERIAL_RESERVE_RESERVE_TOTAL_QUANTITY","物料预定总量",2, false, new String[]{}),
    MATERIAL_RESERVE_UNIT("MATERIAL_RESERVE_UNIT","单位",2, false, new String[]{}),
    MATERIAL_RESERVE_MOISTURE("MATERIAL_RESERVE_MOISTURE","水分",2, false, new String[]{}),
    MATERIAL_RESERVE_CONTENT("MATERIAL_RESERVE_CONTENT","含量",2, false, new String[]{}),
    MATERIAL_RESERVE_SUPPLIER("MATERIAL_RESERVE_SUPPLIER","供应商",2, false, new String[]{}),
    MATERIAL_RESERVE_MANUFACTURER("MATERIAL_RESERVE_MANUFACTURER","生产商",2, false, new String[]{}),
    MATERIAL_RESERVE_ORIGINAL_BATCH_NO("MATERIAL_RESERVE_ORIGINAL_BATCH_NO","原厂批号",2, false, new String[]{}),
    MATERIAL_RESERVE_ORIGINAL_CODE("MATERIAL_RESERVE_ORIGINAL_CODE","原始编码",2, false, new String[]{}),
    MATERIAL_RESERVE_REPORT_NO("MATERIAL_RESERVE_REPORT_NO","报告单编号",2, false, new String[]{}),
    MATERIAL_RESERVE_RELEASE_NO("MATERIAL_RESERVE_RELEASE_NO","放行单编号",2, false, new String[]{}),
    MATERIAL_RESERVE_EXPIRATION_DATE("MATERIAL_RESERVE_EXPIRATION_DATE","有效期至",2, false, new String[]{}),
    MATERIAL_RESERVE_BATCH_CURRENT_RESERVE_QUANTITY("MATERIAL_RESERVE_BATCH_CURRENT_RESERVE_QUANTITY","批次当前预订量",2, false, new String[]{}),
    MATERIAL_RESERVE_CURRENT_RESERVE_TOTAL_QUANTITY("MATERIAL_RESERVE_CURRENT_RESERVE_TOTAL_QUANTITY","物料当前预订总量",2, false, new String[]{}),

    /**
     * 物料预定组件 --> 物料批次
     */
    MATERIAL_RESERVE_BATCH("MATERIAL_RESERVE_BATCH","物料批次",0, false, new String[]{}),
    MATERIAL_RESERVE_BATCH_MATERIAL_NAME("MATERIAL_RESERVE_BATCH_MATERIAL_NAME","物料名称",2, false, new String[]{}),
    MATERIAL_RESERVE_BATCH_MATERIAL_CODE("MATERIAL_RESERVE_BATCH_MATERIAL_CODE","物料编码",2, false, new String[]{}),
    MATERIAL_RESERVE_BATCH_MATERIAL_SPECIFICATION("MATERIAL_RESERVE_BATCH_MATERIAL_SPECIFICATION","物料规格",2, false, new String[]{}),
    MATERIAL_RESERVE_BATCH_BATCH_NO("MATERIAL_RESERVE_BATCH_BATCH_NO","物料批号",2, false, new String[]{}),
    MATERIAL_RESERVE_BATCH_BATCH_RESERVE_QUANTITY("MATERIAL_RESERVE_BATCH_BATCH_RESERVE_QUANTITY","批次预定量",2, false, new String[]{}),
    MATERIAL_RESERVE_BATCH_UNIT("MATERIAL_RESERVE_BATCH_UNIT","单位",2, false, new String[]{}),
    MATERIAL_RESERVE_BATCH_MOISTURE("MATERIAL_RESERVE_BATCH_MOISTURE","水分",2, false, new String[]{}),
    MATERIAL_RESERVE_BATCH_CONTENT("MATERIAL_RESERVE_BATCH_CONTENT","含量",2, false, new String[]{}),
    MATERIAL_RESERVE_BATCH_SUPPLIER("MATERIAL_RESERVE_BATCH_SUPPLIER","供应商",2, false, new String[]{}),
    MATERIAL_RESERVE_BATCH_MANUFACTURER("MATERIAL_RESERVE_BATCH_MANUFACTURER","生产商",2, false, new String[]{}),
    MATERIAL_RESERVE_BATCH_ORIGINAL_BATCH_NO("MATERIAL_RESERVE_BATCH_ORIGINAL_BATCH_NO","原厂批号",2, false, new String[]{}),
    MATERIAL_RESERVE_BATCH_ORIGINAL_CODE("MATERIAL_RESERVE_BATCH_ORIGINAL_CODE","原始编码",2, false, new String[]{}),
    MATERIAL_RESERVE_BATCH_REPORT_NO("MATERIAL_RESERVE_BATCH_REPORT_NO","报告单编号",2, false, new String[]{}),
    MATERIAL_RESERVE_BATCH_RELEASE_NO("MATERIAL_RESERVE_BATCH_RELEASE_NO","放行单编号",2, false, new String[]{}),
    MATERIAL_RESERVE_BATCH_EXPIRATION_DATE("MATERIAL_RESERVE_BATCH_EXPIRATION_DATE","有效期至",2, false, new String[]{}),
    MATERIAL_RESERVE_BATCH_CURRENT_BATCH_RESERVE_QUANTITY("MATERIAL_RESERVE_BATCH_CURRENT_BATCH_RESERVE_QUANTITY","批次当前预订量",2, false, new String[]{}),

    /**
     * 物料投入
     */
    MATERIAL_INPUT("MATERIAL_INPUT","物料投入",0, false, new String[]{}),
    /**
     * 物料投入 投料详情
     */
    MATERIAL_INPUT_DETAILS("MATERIAL_INPUT_DETAILS","投料详情",0, false, new String[]{}),
    MATERIAL_INPUT_DETAILS_MATERIAL_NAME("MATERIAL_INPUT_DETAILS_MATERIAL_NAME","物料名称",2, false, new String[]{}),
    MATERIAL_INPUT_DETAILS_MATERIAL_CODE("MATERIAL_INPUT_DETAILS_MATERIAL_CODE","物料编码",2, false, new String[]{}),
    MATERIAL_INPUT_DETAILS_MATERIAL_SPECIFICATION("MATERIAL_INPUT_DETAILS_MATERIAL_SPECIFICATION","物料规格",2, false, new String[]{}),
    MATERIAL_INPUT_DETAILS_MATERIAL_BATCHNO("MATERIAL_INPUT_DETAILS_MATERIAL_BATCHNO","物料批号",2, false, new String[]{}),
    MATERIAL_INPUT_DETAILS_MATERIAL_PARTNO("MATERIAL_INPUT_DETAILS_MATERIAL_PARTNO","物料件号",2, false, new String[]{}),
    MATERIAL_INPUT_DETAILS_MATERIAL_QUANTITY("MATERIAL_INPUT_DETAILS_MATERIAL_QUANTITY","物料量",2, false, new String[]{}),
    MATERIAL_INPUT_DETAILS_UNIT("MATERIAL_INPUT_DETAILS_UNIT","单位",2, false, new String[]{}),
    MATERIAL_INPUT_DETAILS_FEEDER("MATERIAL_INPUT_DETAILS_FEEDER","投料人",2, false, new String[]{}),
    MATERIAL_INPUT_DETAILS_FEEDING_TIME("MATERIAL_INPUT_DETAILS_FEEDING_TIME","投料时间",2, false, new String[]{}),
    MATERIAL_INPUT_DETAILS_DEVICE_NAME("MATERIAL_INPUT_DETAILS_DEVICE_NAME","设备名称",2, false, new String[]{}),
    MATERIAL_INPUT_DETAILS_DEVICE_CODE("MATERIAL_INPUT_DETAILS_DEVICE_CODE","设备编号",2, false, new String[]{}),
    /**
     * 物料投入 物料汇总
     */
    MATERIAL_INPUT_SUMMARY("MATERIAL_INPUT_SUMMARY","物料汇总",1, false, new String[]{}),
    MATERIAL_INPUT_SUMMARY_MATERIAL_NAME("MATERIAL_INPUT_SUMMARY_MATERIAL_NAME","物料名称",2, false, new String[]{}),
    MATERIAL_INPUT_SUMMARY_MATERIAL_CODE("MATERIAL_INPUT_SUMMARY_MATERIAL_CODE","物料编码",2, false, new String[]{}),
    MATERIAL_INPUT_SUMMARY_MATERIAL_SPECIFICATION("MATERIAL_INPUT_SUMMARY_MATERIAL_SPECIFICATION","物料规格",2, false, new String[]{}),
    MATERIAL_INPUT_SUMMARY_TOTAL_QUANTITY("MATERIAL_INPUT_SUMMARY_TOTAL_QUANTITY","投料总量",2, false, new String[]{}),
    MATERIAL_INPUT_SUMMARY_UNIT("MATERIAL_INPUT_SUMMARY_UNIT","单位",2, false, new String[]{}),
    MATERIAL_INPUT_SUMMARY_TOTAL_NUMBER("MATERIAL_INPUT_SUMMARY_TOTAL_NUMBER","总件数",2, false, new String[]{}),
    /**
     * 用户手写签名
     */
    HANDLE_SUBMIT_SIGN("HANDLE_SUBMIT_SIGN", "手写签名", 0, false, new String[]{}),
    HANDLE_REVIEW_SIGN("HANDLE_REVIEW_SIGN", "手写复合签名", 0, false, new String[]{}),

        /**
         * 结论组件（根据布尔值生成结论内容）
         * componentDetail 配置格式：
         * [{"field":"符合规定","value":"true"},{"field":"不符合规定","value":"false"}]
         */
    CONCLUSION("CONCLUSION", "结论组件", 0, false, new String[]{}),

    /**
     * 配液计划-物料批次
     */
    LIQUID_PREPARATION_PLAN("LIQUID_PREPARATION_PLAN", "配液计划", 0, false, new String[]{}),
    LIQUID_PREPARATION_PLAN_BATCH("LIQUID_PREPARATION_PLAN_BATCH", "配液计划-物料批次", 0, false, new String[]{}),
    LIQUID_PREPARATION_PLAN_BATCH_NAME("LIQUID_PREPARATION_PLAN_BATCH_NAME", "物料名称", 2, false, new String[]{}),
    LIQUID_PREPARATION_PLAN_BATCH_CODE("LIQUID_PREPARATION_PLAN_BATCH_CODE", "物料编码", 2, false, new String[]{}),
    LIQUID_PREPARATION_PLAN_BATCH_SPECIFICATION("LIQUID_PREPARATION_PLAN_BATCH_SPECIFICATION", "物料规格", 2, false, new String[]{}),
    LIQUID_PREPARATION_PLAN_BATCH_BATCHNO("LIQUID_PREPARATION_PLAN_BATCH_BATCHNO", "物料批号", 2, false, new String[]{}),
    LIQUID_PREPARATION_PLAN_BATCH_QUANTITY("LIQUID_PREPARATION_PLAN_BATCH_QUANTITY", "批次配液量", 2, false, new String[]{}),
    LIQUID_PREPARATION_PLAN_BATCH_UNIT("LIQUID_PREPARATION_PLAN_BATCH_UNIT", "单位", 2, false, new String[]{}),
    LIQUID_PREPARATION_PLAN_BATCH_EXPIRY_DATE("LIQUID_PREPARATION_PLAN_BATCH_EXPIRY_DATE", "有效期至", 2, false, new String[]{}),
    LIQUID_PREPARATION_PLAN_BATCH_SUPPLIER("LIQUID_PREPARATION_PLAN_BATCH_SUPPLIER", "供应商", 2, false, new String[]{}),
    LIQUID_PREPARATION_PLAN_BATCH_MANUFACTURER("LIQUID_PREPARATION_PLAN_BATCH_MANUFACTURER", "生产商", 2, false, new String[]{}),
    LIQUID_PREPARATION_PLAN_BATCH_ORIGINAL_BATCHNO("LIQUID_PREPARATION_PLAN_BATCH_ORIGINAL_BATCHNO", "原厂批号", 2, false, new String[]{}),
    LIQUID_PREPARATION_PLAN_BATCH_ORIGINAL_CODE("LIQUID_PREPARATION_PLAN_BATCH_ORIGINAL_CODE", "原始编码", 2, false, new String[]{}),
    LIQUID_PREPARATION_PLAN_BATCH_REPORT_NO("LIQUID_PREPARATION_PLAN_BATCH_REPORT_NO", "报告单编号", 2, false, new String[]{}),
    LIQUID_PREPARATION_PLAN_BATCH_RELEASE_NO("LIQUID_PREPARATION_PLAN_BATCH_RELEASE_NO", "放行单编号", 2, false, new String[]{}),
    /**
     * 配液计划--汇总
     */
    LIQUID_PREPARATION_PLAN_SUMMARY("LIQUID_PREPARATION_PLAN_SUMMARY", "配液计划-物料汇总", 1, false, new String[]{}),
    LIQUID_PREPARATION_PLAN_SUMMARY_NAME("LIQUID_PREPARATION_PLAN_SUMMARY_NAME", "物料名称", 2, false, new String[]{}),
    LIQUID_PREPARATION_PLAN_SUMMARY_CODE("LIQUID_PREPARATION_PLAN_SUMMARY_CODE", "物料编码", 2, false, new String[]{}),
    LIQUID_PREPARATION_PLAN_SUMMARY_SPECIFICATION("LIQUID_PREPARATION_PLAN_SUMMARY_SPECIFICATION", "物料规格", 2, false, new String[]{}),
    LIQUID_PREPARATION_PLAN_SUMMARY_BATCHNO("LIQUID_PREPARATION_PLAN_SUMMARY_BATCHNO", "物料批号", 2, false, new String[]{}),
    LIQUID_PREPARATION_PLAN_SUMMARY_QUANTITY("LIQUID_PREPARATION_PLAN_SUMMARY_QUANTITY", "批次配液量", 2, false, new String[]{}),
    LIQUID_PREPARATION_PLAN_SUMMARY_TOTAL_QUANTITY("LIQUID_PREPARATION_PLAN_SUMMARY_TOTAL_QUANTITY", "物料配液总量", 2, false, new String[]{}),
    LIQUID_PREPARATION_PLAN_SUMMARY_UNIT("LIQUID_PREPARATION_PLAN_SUMMARY_UNIT", "单位", 2, false, new String[]{}),
    LIQUID_PREPARATION_PLAN_SUMMARY_EXPIRY_DATE("LIQUID_PREPARATION_PLAN_SUMMARY_EXPIRY_DATE", "有效期至", 2, false, new String[]{}),
    LIQUID_PREPARATION_PLAN_SUMMARY_SUPPLIER("LIQUID_PREPARATION_PLAN_SUMMARY_SUPPLIER", "供应商", 2, false, new String[]{}),
    LIQUID_PREPARATION_PLAN_SUMMARY_MANUFACTURER("LIQUID_PREPARATION_PLAN_SUMMARY_MANUFACTURER", "生产商", 2, false, new String[]{}),
    LIQUID_PREPARATION_PLAN_SUMMARY_ORIGINAL_BATCHNO("LIQUID_PREPARATION_PLAN_SUMMARY_ORIGINAL_BATCHNO", "原厂批号", 2, false, new String[]{}),
    LIQUID_PREPARATION_PLAN_SUMMARY_ORIGINAL_CODE("LIQUID_PREPARATION_PLAN_SUMMARY_ORIGINAL_CODE", "原始编码", 2, false, new String[]{}),
    LIQUID_PREPARATION_PLAN_SUMMARY_REPORT_NO("LIQUID_PREPARATION_PLAN_SUMMARY_REPORT_NO", "报告单编号", 2, false, new String[]{}),
    LIQUID_PREPARATION_PLAN_SUMMARY_RELEASE_NO("LIQUID_PREPARATION_PLAN_SUMMARY_RELEASE_NO", "放行单编号", 2, false, new String[]{}),

    /**
     * 配液量取 -- 量取详情
     */
    LIQUID_PREPARATION_MEASURE("LIQUID_PREPARATION_MEASURE", "配液量取", 0, false ,new String[]{}),
    LIQUID_PREPARATION_MEASURE_DETAIL("LIQUID_PREPARATION_MEASURE_DETAIL", "量取详情", 0, false, new String[]{}),
    LIQUID_PREPARATION_MEASURE_DETAIL_NAME("LIQUID_PREPARATION_MEASURE_DETAIL_NAME", "物料名称", 2, false, new String[]{}),
    LIQUID_PREPARATION_MEASURE_DETAIL_CODE("LIQUID_PREPARATION_MEASURE_DETAIL_CODE", "物料编码", 2, false, new String[]{}),
    LIQUID_PREPARATION_MEASURE_DETAIL_SPECIFICATION("LIQUID_PREPARATION_MEASURE_DETAIL_SPECIFICATION", "物料规格", 2, false, new String[]{}),
    LIQUID_PREPARATION_MEASURE_DETAIL_BATCHNO("LIQUID_PREPARATION_MEASURE_DETAIL_BATCHNO", "物料批号", 2, false, new String[]{}),
    LIQUID_PREPARATION_MEASURE_DETAIL_PARTNO("LIQUID_PREPARATION_MEASURE_DETAIL_PARTNO", "物料件号", 2, false, new String[]{}),
    LIQUID_PREPARATION_MEASURE_DETAIL_QUANTITY("LIQUID_PREPARATION_MEASURE_DETAIL_QUANTITY", "物料量", 2, false, new String[]{}),
    LIQUID_PREPARATION_MEASURE_DETAIL_UNIT("LIQUID_PREPARATION_MEASURE_DETAIL_UNIT", "单位", 2, false, new String[]{}),
    LIQUID_PREPARATION_MEASURE_DETAIL_OPERATOR("LIQUID_PREPARATION_MEASURE_DETAIL_OPERATOR", "操作人", 2, false, new String[]{}),
    LIQUID_PREPARATION_MEASURE_DETAIL_REVIEWER("LIQUID_PREPARATION_MEASURE_DETAIL_REVIEWER", "复核人", 2, false, new String[]{}),
    LIQUID_PREPARATION_MEASURE_DETAIL_OPERATION_TIME("LIQUID_PREPARATION_MEASURE_DETAIL_OPERATION_TIME", "操作时间", 2, false, new String[]{}),

    /**
     * 配液量取 -- 量取汇总
     */
    LIQUID_PREPARATION_MEASURE_SUMMARY("LIQUID_PREPARATION_MEASURE_SUMMARY", "量取汇总", 1, false, new String[]{}),
    LIQUID_PREPARATION_MEASURE_SUMMARY_NAME("LIQUID_PREPARATION_MEASURE_SUMMARY_NAME", "物料名称", 2, false, new String[]{}),
    LIQUID_PREPARATION_MEASURE_SUMMARY_CODE("LIQUID_PREPARATION_MEASURE_SUMMARY_CODE", "物料编码", 2, false, new String[]{}),
    LIQUID_PREPARATION_MEASURE_SUMMARY_SPECIFICATION("LIQUID_PREPARATION_MEASURE_SUMMARY_SPECIFICATION", "物料规格", 2, false, new String[]{}),
    LIQUID_PREPARATION_MEASURE_SUMMARY_TOTAL_QUANTITY("LIQUID_PREPARATION_MEASURE_SUMMARY_TOTAL_QUANTITY", "物料总量", 2, false, new String[]{}),
    LIQUID_PREPARATION_MEASURE_SUMMARY_UNIT("LIQUID_PREPARATION_MEASURE_SUMMARY_UNIT", "单位", 2, false, new String[]{}),
    LIQUID_PREPARATION_MEASURE_SUMMARY_TOTAL_COUNT("LIQUID_PREPARATION_MEASURE_SUMMARY_TOTAL_COUNT", "总件数", 2, false, new String[]{}),

    /**
     * 配液投入
     */
    LIQUID_PREPARATION_INPUT("LIQUID_PREPARATION_INPUT", "配液投入", 0, false, new String[]{}),
    // 配液投入详情
    LIQUID_PREPARATION_INPUT_DETAIL("LIQUID_PREPARATION_INPUT_DETAIL", "配液投入详情", 0, false, new String[]{}),
    LIQUID_PREPARATION_INPUT_DETAIL_NAME("LIQUID_PREPARATION_INPUT_DETAIL_NAME", "物料名称", 2, false, new String[]{}),
    LIQUID_PREPARATION_INPUT_DETAIL_CODE("LIQUID_PREPARATION_INPUT_DETAIL_CODE", "物料编码", 2, false, new String[]{}),
    LIQUID_PREPARATION_INPUT_DETAIL_SPECIFICATION("LIQUID_PREPARATION_INPUT_DETAIL_SPECIFICATION", "物料规格", 2, false, new String[]{}),
    LIQUID_PREPARATION_INPUT_DETAIL_BATCH_NO("LIQUID_PREPARATION_INPUT_DETAIL_BATCH_NO", "物料批号", 2, false, new String[]{}),
    LIQUID_PREPARATION_INPUT_DETAIL_PART_NO("LIQUID_PREPARATION_INPUT_DETAIL_PART_NO", "物料件号", 2, false, new String[]{}),
    LIQUID_PREPARATION_INPUT_DETAIL_QUANTITY("LIQUID_PREPARATION_INPUT_DETAIL_QUANTITY", "物料量", 2, false, new String[]{}),
    LIQUID_PREPARATION_INPUT_DETAIL_UNIT("LIQUID_PREPARATION_INPUT_DETAIL_UNIT", "单位", 2, false, new String[]{}),
    LIQUID_PREPARATION_INPUT_DETAIL_IMPORTER("LIQUID_PREPARATION_INPUT_DETAIL_IMPORTER", "投料人", 2, false, new String[]{}),
    LIQUID_PREPARATION_INPUT_DETAIL_INPUT_TIME("LIQUID_PREPARATION_INPUT_DETAIL_INPUT_TIME", "操作时间", 2, false, new String[]{}),
    LIQUID_PREPARATION_INPUT_DETAIL_DEVICE_NO("LIQUID_PREPARATION_INPUT_DETAIL_DEVICE_NO", "设备编号", 2, false, new String[]{}),
    LIQUID_PREPARATION_INPUT_DETAIL_DEVICE_NAME("LIQUID_PREPARATION_INPUT_DETAIL_CONTAINER_NAME", "设备名称", 2, false, new String[]{}),
    // 配液投入汇总
    LIQUID_PREPARATION_INPUT_SUMMARY("LIQUID_PREPARATION_INPUT_SUMMARY", "配液投入汇总", 1, false, new String[]{}),
    LIQUID_PREPARATION_INPUT_SUMMARY_NAME("LIQUID_PREPARATION_INPUT_SUMMARY_NAME", "物料名称", 2, false, new String[]{}),
    LIQUID_PREPARATION_INPUT_SUMMARY_CODE("LIQUID_PREPARATION_INPUT_SUMMARY_CODE", "物料编码", 2, false, new String[]{}),
    LIQUID_PREPARATION_INPUT_SUMMARY_SPECIFICATION("LIQUID_PREPARATION_INPUT_SUMMARY_SPECIFICATION", "物料规格", 2, false, new String[]{}),
    LIQUID_PREPARATION_INPUT_SUMMARY_TOTAL_QUANTITY("LIQUID_PREPARATION_INPUT_SUMMARY_TOTAL_QUANTITY", "投料总量", 2, false, new String[]{}),
    LIQUID_PREPARATION_INPUT_SUMMARY_UNIT("LIQUID_PREPARATION_INPUT_SUMMARY_UNIT", "单位", 2, false, new String[]{}),
    LIQUID_PREPARATION_INPUT_SUMMARY_TOTAL_COUNT("LIQUID_PREPARATION_INPUT_SUMMARY_TOTAL_COUNT", "总件数", 2, false, new String[]{}),

    // 配液产出
    LIQUID_PREPARATION_OUTPUT("LIQUID_PREPARATION_PRODUCE", "配液产出", 0, false, new String[]{}),
    // 配液产出详情
    LIQUID_PREPARATION_OUTPUT_DETAILS("LIQUID_PREPARATION_OUTPUT_DETAILS", "配液产出详情", 0, false, new String[]{}),
    LIQUID_PREPARATION_OUTPUT_DETAILS_NAME("LIQUID_PREPARATION_OUTPUT_DETAILS_NAME", "物料名称", 2, false, new String[]{}),
    LIQUID_PREPARATION_OUTPUT_DETAILS_CODE("LIQUID_PREPARATION_OUTPUT_DETAILS_CODE", "物料编码", 2, false, new String[]{}),
    LIQUID_PREPARATION_OUTPUT_DETAILS_SPECIFICATION("LIQUID_PREPARATION_OUTPUT_DETAILS_SPECIFICATION", "物料规格", 2, false, new String[]{}),
    LIQUID_PREPARATION_OUTPUT_DETAILS_BATCHNO("LIQUID_PREPARATION_OUTPUT_DETAILS_BATCHNO", "物料批号", 2, false, new String[]{}),
    LIQUID_PREPARATION_OUTPUT_DETAILS_PARTNO("LIQUID_PREPARATION_OUTPUT_DETAILS_PARTNO", "物料件号", 2, false, new String[]{}),
    LIQUID_PREPARATION_OUTPUT_DETAILS_QUANTITY("LIQUID_PREPARATION_OUTPUT_DETAILS_QUANTITY", "物料量", 2, false, new String[]{}),
    LIQUID_PREPARATION_OUTPUT_DETAILS_UNIT("LIQUID_PREPARATION_OUTPUT_DETAILS_UNIT", "单位", 2, false, new String[]{}),
    LIQUID_PREPARATION_OUTPUT_DETAILS_OPERATOR("LIQUID_PREPARATION_OUTPUT_DETAILS_OPERATOR", "产出人", 2, false, new String[]{}),
    LIQUID_PREPARATION_OUTPUT_DETAILS_OUTPUT_TIME("LIQUID_PREPARATION_OUTPUT_DETAILS_OUTPUT_TIME", "操作时间", 2, false, new String[]{}),
    LIQUID_PREPARATION_OUTPUT_DETAILS_REVIEWER("LIQUID_PREPARATION_OUTPUT_DETAILS_REVIEWER", "复核人", 2, false, new String[]{}),
    // 配液产出汇总
    LIQUID_PREPARATION_OUTPUT_SUMMARY("LIQUID_PREPARATION_OUTPUT_SUMMARY", "配液产出汇总", 1, false, new String[]{}),
    LIQUID_PREPARATION_OUTPUT_SUMMARY_NAME("LIQUID_PREPARATION_OUTPUT_SUMMARY_NAME", "物料名称", 2, false, new String[]{}),
    LIQUID_PREPARATION_OUTPUT_SUMMARY_CODE("LIQUID_PREPARATION_OUTPUT_SUMMARY_CODE", "物料编码", 2, false, new String[]{}),
    LIQUID_PREPARATION_OUTPUT_SUMMARY_SPECIFICATION("LIQUID_PREPARATION_OUTPUT_SUMMARY_SPECIFICATION", "物料规格", 2, false, new String[]{}),
    LIQUID_PREPARATION_OUTPUT_SUMMARY_TOTAL_QUANTITY("LIQUID_PREPARATION_OUTPUT_SUMMARY_TOTAL_QUANTITY", "产出总量", 2, false, new String[]{}),
    LIQUID_PREPARATION_OUTPUT_SUMMARY_UNIT("LIQUID_PREPARATION_OUTPUT_SUMMARY_UNIT", "单位", 2, false, new String[]{}),
    LIQUID_PREPARATION_OUTPUT_SUMMARY_PARTNO("LIQUID_PREPARATION_OUTPUT_SUMMARY_PARTNO", "总件数", 2, false, new String[]{}),

    // 设备数采绘图组件
    EQUIPMENT_DATA_DRAW_LIST("EQUIPMENT_DATA_DRAW_LIST", "设备数采绘图", 0, false, new String[]{}),
    EQUIPMENT_DATA_DRAW("EQUIPMENT_DATA_DRAW", "设备数采绘图子组件", 0, false, new String[]{}),

    // 请验结果组件
    INSPECTION_RESULTS("INSPECTION_RESULTS", "请验结果", 0, false, new String[]{}),
    BATCH_INSPECTION_RESULTS("BATCH_INSPECTION_RESULTS","批次检验结果", 1, false, new String[]{}),
    INSPECT_PLEASE_CHECK_NO("INSPECT_PLEASE_CHECK_NO", "请验单号", 2, false, new String[]{}),
    INSPECT_MATERIAL_NAME("INSPECT_MATERIAL_NAME", "物料名称", 2, false, new String[]{}),
    INSPECT_MATERIAL_CODE("INSPECT_MATERIAL_CODE", "物料编码", 2, false, new String[]{}),
    INSPECT_MATERIAL_SPECIFICATION("INSPECT_MATERIAL_SPECIFICATION", "物料规格", 2, false, new String[]{}),
    INSPECT_MATERIAL_BATCH_NUMBER("INSPECT_MATERIAL_BATCH_NUMBER", "物料批号", 2, false, new String[]{}),
    INSPECT_VERIFY_USER("INSPECT_VERIFY_USER", "请验人", 2, false, new String[]{}),
    INSPECT_VERIFY_DATE("INSPECT_VERIFY_DATE", "请验时间", 2, false, new String[]{}),

    ;




    @EnumValue
    private final String value;

    private final String name;

    /**
     * 在同级节点下排序
     */
    private final int sort;

    /**
     * 配置是否要求必填
     */
    private final boolean configRequired;

    /**
     * 若组件要求配置必填 此处设置必须配置的字段
     */
    private final String[] requiredProperties;

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static BusinessComponentTypeEnum getEnumByValue(String value) {
        return Arrays.stream(BusinessComponentTypeEnum.values())
                .filter(statusEnum -> statusEnum.getValue().equals(value))
                .findFirst()
                .orElse(null);
    }

    public static List<BusinessComponentTypeEnum> getRequiredConfigEnums(){
        return Arrays.stream(BusinessComponentTypeEnum.values())
                .filter(BusinessComponentTypeEnum::isConfigRequired)
                .collect(Collectors.toList());
    }

    public static BusinessComponentTypeEnum[] getComponentTypeByPrefix(String componentTypePrefix){
        if (StrUtil.isBlank(componentTypePrefix)){
            return BusinessComponentTypeEnum.values();
        }
        return Arrays.stream(BusinessComponentTypeEnum.values())
                .filter(componentTypeEnum -> componentTypeEnum.getValue().startsWith(componentTypePrefix))
                .toArray(BusinessComponentTypeEnum[]::new);
    }

    public static Map<String, Integer> getSortMap() {
        return Arrays.stream(BusinessComponentTypeEnum.values())
                .collect(Collectors.toMap(BusinessComponentTypeEnum::getValue, BusinessComponentTypeEnum::getSort));
    }
}
